Repository IntersectMBO/plutus, pull requests merged in 2020-10, with the labels that each got.

#2350 SCP-1233 - Make JavaScript Marlowe constructors closer by using capital first letters
  marlowe-playground-client/src/Examples/JS/Contracts.purs
  marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
  marlowe-playground-client/src/StaticData.purs
Labels: Meadow

#2353 SCP-1270 - Send to simulator button in JS doesn't work
  marlowe-playground-client/src/MainFrame.purs
Labels: Meadow

#2354 SCP-1232 - Expand tutorial section about JavaScript
  marlowe-playground-client/src/Examples/JS/Contracts.purs
  marlowe/doc/javascript-embedding.adoc
Labels: Marlowe, Meadow, Tutorials

#2386 SCP-1332 - Introduce On and Off state for Simulation
  marlowe-playground-client/src/JSEditor.purs
  marlowe-playground-client/src/Marlowe/Gists.purs
  marlowe-playground-client/src/Simulation.purs
  marlowe-playground-client/src/Simulation/BottomPanel.purs
  marlowe-playground-client/src/Simulation/State.purs
  marlowe-playground-client/src/Simulation/Types.purs
  marlowe-playground-client/src/Wallet.purs
  marlowe-playground-client/test/Marlowe/ContractTests.purs
  secrets/pablo/plutus/githubClientId.gpg
  secrets/pablo/plutus/githubClientSecret.gpg
  secrets/pablo/plutus/jwtSignature.gpg
Labels: Meadow, User experience

#2390 Address reviews to #2386 by @shmish111
  marlowe-playground-client/src/Simulation.purs
  marlowe-playground-client/src/Simulation/BottomPanel.purs
  marlowe-playground-client/src/Simulation/State.purs
  web-common/src/Data/Lens/Extra.purs
Labels: Meadow

#2393 Revert usages of `has`
  marlowe-playground-client/src/Simulation.purs
Labels: Meadow, bug

#2408 SCP-1245 - Cannot reduce contract when it doesn't start with When
  marlowe-playground-client/src/Simulation.purs
  marlowe-playground-client/src/Simulation/BottomPanel.purs
  marlowe-playground-client/src/Simulation/State.purs
  marlowe-playground-client/src/Simulation/Types.purs
  marlowe-playground-client/src/Wallet.purs
  marlowe-playground-client/static/css/panels.scss
  marlowe-playground-client/test/Marlowe/ContractTests.purs
Labels: Marlowe, Meadow, User experience

#2421 SCP-1211 - Show warning for non-hexit error in playground
  marlowe-playground-client/grammar.ne
  marlowe-playground-client/src/Marlowe/Gen.purs
  marlowe-playground-client/src/Marlowe/Semantics.purs
Labels: Marlowe, Meadow, User experience

#2414 nofib-hs was benchmarking compilation times, not execution times
  nix/stack.materialized/plutus-benchmark.nix
  plutus-benchmark/README.md
  plutus-benchmark/nofib/bench/BenchHaskell.hs
  plutus-benchmark/nofib/src/Plutus/Benchmark/Knights/ChessSetList.hs
  plutus-benchmark/nofib/src/Plutus/Benchmark/Prime.hs
  plutus-benchmark/nofib/src/Plutus/Benchmark/Queens.hs
  plutus-benchmark/plutus-benchmark.cabal
Labels: Benchmarks

#2425 SCP-1171 - Fix Haskell to Marlowe conversion of PK hashes
  marlowe/src/Language/Marlowe/Pretty.hs
Labels: Marlowe, Meadow, bug
