Repository IntersectMBO/plutus, pull requests merged in 2022-06, with the labels that each got.

#4668 [TypeCheck] Add 'Renamed' and clean things up
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Normalize.hs
  plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/Rename.hs
  plutus-core/plutus-core/src/PlutusCore/Rename/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-ir/src/PlutusIR/Normalize.hs
Labels: Type checking, Refactoring

#4666 [Refactoring] Remove some unused pragmas and imports
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/prelude/PlutusPrelude.hs
Labels: Refactoring

#4667 Improve the error messages from the CEK machine
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/diFullyApplied.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.uplc.golden
Labels: needs backport

#4674 [Builtins] Pull 'DefaultMachineParameters' into 'plutus-core'
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/DeferredMachineParameters.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/ImmediateMachineParameters.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
Labels: Refactoring, Builtins, User experience, Don't look here yet

#4682 [TypeCheck] Drop 'Maybe' from 'BuiltinTypes'
  plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-core/test/TypeSynthesis/Spec.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
  plutus-metatheory/test/TestNEAT.hs
Labels: Type checking, Refactoring

#4681 [Builtins] Add 'fromValue' and 'fromValueOf'
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/prelude/PlutusPrelude.hs
Labels: Refactoring, Builtins, Don't look here yet

#4686 [TypeCheck] Clean up constraints
  plutus-core/plutus-core/src/PlutusCore/Normalize.hs
  plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
Labels: Type checking, Refactoring

#4696 [PIR] [Test] Add a 'factorial' example
  plutus-core/plutus-ir/test/Spec.hs
  plutus-core/plutus-ir/test/recursion/factorial
  plutus-core/plutus-ir/test/recursion/factorial.golden
  plutus-core/testlib/PlutusIR/Test.hs
Labels: Test, Plutus IR

#4708 [Docs] [Builtins] Clean up internal documentation
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/TypeScheme.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteAtIntegerWrongCondType.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteAtIntegerWrongCondType.uplc.golden
Labels: Docs, Refactoring, Builtins

#4724 [Builtins] Fix rendering of universes
  plutus-conformance/README.md
  plutus-conformance/uplc/evaluation/builtin/mkNilData/mkNilData.uplc.expected
  plutus-conformance/uplc/evaluation/builtin/mkNilPairData/mkNilPairData.uplc.expected
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Default.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty/PrettyConst.hs
  plutus-core/plutus-core/test/Evaluation/Spec.hs
  plutus-core/plutus-core/test/Pretty/Golden/Readable/Examples/Data/ofoldrData.plc.golden
  plutus-core/plutus-core/test/Pretty/Golden/Readable/StdLib/Data/Data/caseData.plc.golden
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Error.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-ir/src/PlutusIR/Error.hs
  plutus-core/testlib/PlutusIR/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Default.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Error.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Lib.hs
  plutus-tx/src/PlutusTx/Code.hs
  plutus-tx/src/PlutusTx/Lift.hs
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: Refactoring, Builtins, Textual representation

#4725 Kwxm/plt 201
  plutus-core/cost-model/CostModelGeneration.md
Labels: Docs, Costs
