Repository IntersectMBO/plutus, pull requests merged in 2022-05, with the labels that each got.

#4591 Kwxm/costing/secp256k1
  doc/reference/builtin-parameters.csv
  plutus-core/cost-model/budgeting-bench/Benchmarks/Bool.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/CryptoAndHashes.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching.csv
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/Crypto.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-tx/src/PlutusTx/Prelude.hs
Labels: Costs, needs backport

#4593 [Builtins] Drop 'CekValEnv' from 'VBuiltin'
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: Evaluation, Builtins

#4588 [Evaluation] Bang 'Term's in 'CekValue'
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: Evaluation, Performance

#4601 [Names] Make 'NamedDeBruijn' strict
  plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
Labels: Evaluation, Name handling

#4595 SCP-3935: rename verifySignature
  doc/reference/builtin-parameters.csv
  plutus-core/cost-model/budgeting-bench/Benchmarks/CryptoAndHashes.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching.csv
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core/src/Crypto.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-core/plutus-core/test/types/verifyIdentity.plc
  plutus-core/testlib/PlutusCore/Generators/NEAT/Term.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/src/Plutus/ApiCommon.hs
  plutus-metatheory/src/Algorithmic.lagda
  plutus-metatheory/src/Algorithmic/CC.lagda.md
  plutus-metatheory/src/Algorithmic/CEKV.lagda.md
  plutus-metatheory/src/Algorithmic/Erasure/Reduction.lagda
  plutus-metatheory/src/Algorithmic/ReductionEC.lagda.md
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Builtin/Signature.lagda.md
  plutus-metatheory/src/Declarative.lagda.md
  plutus-metatheory/src/Raw.lagda
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
  plutus-tx-plugin/test/Plugin/Primitives/verify.plc.golden
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Prelude.hs
Labels: Builtins

#4603 Remove EcdsaSecp256k1,SchnorrSecp256k1 from costparamnames
  plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
Labels: needs backport

#4587 [Builtins] Optimize 'MakeKnownM'
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/test/Evaluation/Spec.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: Evaluation, Builtins, Performance, Don't look here yet

#4613 Update cost model for Vasil release
  plutus-benchmark/nofib/test/formulaBudget.budget.golden
  plutus-benchmark/nofib/test/knightsBudget.budget.golden
  plutus-benchmark/nofib/test/queens4budget.budget.golden
  plutus-benchmark/nofib/test/queens5budget.budget.golden
  plutus-core/cost-model/data/benching.csv
  plutus-core/cost-model/data/benching.csv-new-models
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/cost-model/data/builtinCostModel.json-new-models
  plutus-core/cost-model/data/cekMachineCosts.json
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/Fib/1.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/Fib/2.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/Fib/3.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IdNat/0.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IdNat/3.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IdNat/6.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IdNat/9.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IfThenElse/0.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IfThenElse/1.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IfThenElse/2.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IfThenElse/3.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IfThenElse/4.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Budget/IfThenElse/5.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Tallying/Fib/1.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Tallying/Fib/2.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/Tallying/Fib/3.plc.golden
  plutus-tx-plugin/test/Budget/any.budget.golden
  plutus-tx-plugin/test/Budget/applicative.budget.golden
  plutus-tx-plugin/test/Budget/elem.budget.golden
  plutus-tx-plugin/test/Budget/filter.budget.golden
  plutus-tx-plugin/test/Budget/find.budget.golden
  plutus-tx-plugin/test/Budget/monadicDo.budget.golden
  plutus-tx-plugin/test/Budget/patternMatch.budget.golden
  plutus-tx-plugin/test/Budget/sum.budget.golden
Labels: Costs

#4626 [Docs] [Builtins] Mention '-fpedantic-bottoms'
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
Labels: Docs, Builtins, Costs

#4627 [Docs] [Builtins] Mention making 'Data' strict
  plutus-core/plutus-core/src/PlutusCore/Data.hs
Labels: Docs, Evaluation, Builtins

#4605 [Docs] [Builtins] Add Note [Builtins and Plutus type checking]
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-core/test/TypeSynthesis/Golden/IdIntegerAsBool.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/IsConstant.plc.golden
Labels: Do not merge, Docs, Builtins

#4632 [Refactoring] Move junk out of 'PlutusCore'
  plutus-core/executables/Common.hs
  plutus-core/executables/plc/Main.hs
  plutus-core/plutus-core/src/PlutusCore.hs
  plutus-core/plutus-core/src/PlutusCore/Parser.hs
  plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Parser.hs
  plutus-core/testlib/Test/Tasty/Extras.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
Labels: Refactoring

#4636 [Refactoring] Clean up reexports of 'PlutusCore'
  plutus-benchmark/cek-calibration/Main.hs
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/lists/exe/Main.hs
  plutus-benchmark/nofib/exe/Main.hs
  plutus-benchmark/validation/Common.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/executables/Common.hs
  plutus-core/executables/plc/Main.hs
  plutus-core/executables/uplc/Main.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore.hs
  plutus-core/plutus-core/test/CostModelInterface/Spec.hs
  plutus-core/plutus-core/test/Evaluation/Machines.hs
  plutus-core/testlib/PlutusCore/Generators/Internal/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SECP256k1.hs
  plutus-core/untyped-plutus-core/test/Evaluation/FreeVars.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
  plutus-ledger-api/src/Plutus/ApiCommon.hs
  plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
  plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs
  plutus-ledger-api/src/Plutus/V2/Ledger/EvaluationContext.hs
  plutus-ledger-api/testlib/Plutus/Ledger/Test/EvaluationContext.hs
  plutus-metatheory/test/TestNEAT.hs
  plutus-tx-plugin/test/Lib.hs
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: Plutus Core, Refactoring

#4619 PLT-250: mkEvaluationContext now lives in (MonadError CostModelApplyError)
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
  plutus-core/plutus-core/test/CostModelInterface/Spec.hs
  plutus-ledger-api/src/Plutus/ApiCommon.hs
  plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs
  plutus-ledger-api/src/Plutus/V1/Ledger/EvaluationContext.hs
  plutus-ledger-api/src/Plutus/V2/Ledger/Api.hs
  plutus-ledger-api/testlib/Plutus/Ledger/Test/EvaluationContext.hs
Labels: needs backport

#4649 [Builtins] Add 'MakeBuiltinMeaning' and type errors doctests
  plutus-core/plutus-core/src/PlutusCore/Builtin/Debug.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Elaborate.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
Labels: Builtins, User experience

#4648 [Builtins] Add detection of applied type variables to the elaboration machinery
  plutus-core/plutus-core/src/PlutusCore/Builtin/Debug.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Elaborate.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
Labels: Builtins, User experience

#4663 [TypeCheck] Remove all calls to 'rename' from the PIR type checker
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
  plutus-core/plutus-ir/test/types/listMatch.golden
  plutus-core/plutus-ir/test/types/maybe.golden
  plutus-core/plutus-ir/test/types/mutuallyRecursiveTypes.golden
Labels: Type checking

#4665 [Test] [TypeCheck] Add a data escaping test
  plutus-core/plutus-ir/test/Spec.hs
  plutus-core/plutus-ir/test/datatypes/dataEscape
  plutus-core/plutus-ir/test/datatypes/dataEscape.golden
Labels: Test, Plutus IR, Type checking
