Repository IntersectMBO/plutus, pull requests merged in 2023-12, with the labels that each got.

#5662 Kwxm/conformance/more polymorphism tests
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/data/dataMap/dataMap.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/data/dataMap/dataMap.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/list/illTypedList1/illTypedList1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/list/illTypedList1/illTypedList1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/list/illTypedList2/illTypedList2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/list/illTypedList2/illTypedList2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/pair/illTypedPair1/illTypedPair1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/pair/illTypedPair1/illTypedPair1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/pair/illTypedPair2/illTypedPair2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/pair/illTypedPair2/illTypedPair2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataByteString/chooseDataByteString.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataByteString/chooseDataByteString.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataConstr/chooseDataConstr.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataConstr/chooseDataConstr.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataInteger/chooseDataInteger.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataInteger/chooseDataInteger.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataList/chooseDataList.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataList/chooseDataList.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataMap/chooseDataMap.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataMap/chooseDataMap.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-1/ifThenElse-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-1/ifThenElse-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-2/ifThenElse-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-2/ifThenElse-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-3/ifThenElse-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-bad-cond-1/ifThenElse-bad-cond-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-bad-cond-1/ifThenElse-bad-cond-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-bad-cond-2/ifThenElse-bad-cond-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-bad-cond-2/ifThenElse-bad-cond-2.uplc.expected
Labels: Test, Builtins, No Changelog Required

#5653 PLT-1567 Extend agda executable to handle costing reporting features
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Cost.lagda.md
  plutus-metatheory/src/Main.lagda
  plutus-metatheory/src/Opts.hs
  plutus-metatheory/src/Raw.hs
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
  plutus-metatheory/src/Utils/Reflection.lagda.md
Labels: No Changelog Required

#5667 1.18.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20231206_051204_unsafeFixIO.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20231109_113944_kenneth.mackenzie_better_range_errors.md
  plutus-tx-plugin/changelog.d/20231121_151437_unsafeFixIO_opaque.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20231109_113820_kenneth.mackenzie_better_range_errors.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5668 Fix Haddock error
  plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
Labels: No Changelog Required

#5672 Add a multilet test case for the PIR inliner
  plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/multilet
  plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/multilet.golden
Labels: No Changelog Required

#5680 Add budget tests for Value
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-ledger-api/test-plugin/Spec.hs
  plutus-ledger-api/test-plugin/Spec/Budget.hs
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq1-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq1.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq2-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq2.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq3-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq3.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq4-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq4.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq5-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/geq5.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt.pir.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt1-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt1.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt2-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt2.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt3-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt3.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt4-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt4.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt5-budget.eval.golden
  plutus-ledger-api/test-plugin/Spec/Budget/9.6/gt5.eval.golden
  plutus-ledger-api/test-plugin/Spec/Value.hs
  plutus-ledger-api/test-plugin/Spec/Value/9.6/Long.stat.golden
  plutus-ledger-api/test-plugin/Spec/Value/9.6/Short.stat.golden
  plutus-ledger-api/test-plugin/Spec/golden/9.6/Long.stat.golden
  plutus-ledger-api/test-plugin/Spec/golden/9.6/Short.stat.golden
Labels: No Changelog Required

#5679 PLT-1566 Add cost semantics for basic builtins
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Cost.lagda.md
  plutus-metatheory/src/Cost/Base.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
Labels: No Changelog Required

#5687 Add a missing INLINABLE pragma
  plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
Labels: No Changelog Required

#5690 Kwxm/spec/no flat for bls
  doc/plutus-core-spec/cardano/builtins1.tex
  doc/plutus-core-spec/cardano/builtins4.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/notation.tex
  doc/plutus-core-spec/untyped-grammar.tex
Labels: Specification, No Changelog Required

#5693 1.19
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20231113_165738_unsafeFixIO_cse.md
  plutus-core/changelog.d/20231204_155446_michael.peyton-jones_non_representable_constants.md
  plutus-core/changelog.d/20231206_134418_kenneth.mackenzie_bls_flat_uncompression.md
  plutus-core/changelog.d/20231211_142943_unsafeFixIO_inline_multilet.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20231211_183849_unsafeFixIO_geq.md
  plutus-ledger-api/changelog.d/20231212_070128_unsafeFixIO_lovelace.md
  plutus-ledger-api/changelog.d/20231213_133936_unsafeFixIO_lovelace.md
  plutus-ledger-api/changelog.d/20231218_154908_unsafeFixIO_helper.md
  plutus-ledger-api/changelog.d/20231220_082347_unsafeFixIO_constitution_script_hash.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20231206_140130_kenneth.mackenzie_bls_flat_uncompression.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20231206_135019_kenneth.mackenzie_bls_flat_uncompression.md
  plutus-tx/changelog.d/20231208_144400_michael.peyton-jones_fromData_bugs.md
  plutus-tx/changelog.d/20231209_192321_unsafeFixIO_assocmap.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required
