Repository IntersectMBO/plutus, pull requests merged in 2023-05, with the labels that each got.

#5273 PLT-5279 Rewrite Decidable predicates to avoid PM on many constructors.
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Algorithmic/Erasure.lagda
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Builtin/Constant/AtomicType.lagda.md
  plutus-metatheory/src/Builtin/Constant/Type.lagda.md
  plutus-metatheory/src/Check.lagda.md
  plutus-metatheory/src/Declarative/Erasure.lagda.md
  plutus-metatheory/src/Raw.lagda
  plutus-metatheory/src/RawU.lagda.md
  plutus-metatheory/src/Scoped.lagda
  plutus-metatheory/src/Scoped/Extrication.lagda
  plutus-metatheory/src/Untyped.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-metatheory/src/Utils/Decidable.lagda.md
  plutus-metatheory/src/Utils/Reflection.lagda.md
Labels: No Changelog Required

#5276 Bump iohk-nix and remove now-unneeded hack
  flake.lock
  nix/cells/plutus/library/make-plutus-project.nix
Labels: No Changelog Required

#5281 Add some budget tests for short-circuiting functions
  plutus-tx-plugin/test/Budget/Spec.hs
  plutus-tx-plugin/test/Budget/andCheap.budget.golden
  plutus-tx-plugin/test/Budget/andCheap.plc.golden
  plutus-tx-plugin/test/Budget/andExpensive.budget.golden
  plutus-tx-plugin/test/Budget/andExpensive.plc.golden
  plutus-tx-plugin/test/Budget/elemCheap.budget.golden
  plutus-tx-plugin/test/Budget/elemCheap.plc.golden
  plutus-tx-plugin/test/Budget/elemExpensive.budget.golden
  plutus-tx-plugin/test/Budget/elemExpensive.plc.golden
  plutus-tx-plugin/test/Budget/notElemCheap.budget.golden
  plutus-tx-plugin/test/Budget/notElemCheap.plc.golden
  plutus-tx-plugin/test/Budget/notElemExpensive.budget.golden
  plutus-tx-plugin/test/Budget/notElemExpensive.plc.golden
  plutus-tx-plugin/test/Budget/null.budget.golden
  plutus-tx-plugin/test/Budget/null.plc.golden
  plutus-tx-plugin/test/Budget/orCheap.budget.golden
  plutus-tx-plugin/test/Budget/orCheap.plc.golden
  plutus-tx-plugin/test/Budget/orExpensive.budget.golden
  plutus-tx-plugin/test/Budget/orExpensive.plc.golden
Labels: No Changelog Required

#5282 [plutus-tx-plugin] No scopestack is needed
  plutus-tx-plugin/src/PlutusTx/Compiler/Binders.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Names.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Types.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
Labels: No Changelog Required

#5287 Build all haddock in CI
  nix/cells/automation/ciJobs.nix
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/DebugDriver.hs
Labels: No Changelog Required

#5279 PLT-1030 Implemented SOPs for UPLC
  plutus-conformance/agda/Spec.hs
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/RawU.lagda.md
  plutus-metatheory/src/Untyped.hs
  plutus-metatheory/src/Untyped.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-metatheory/src/Untyped/RenamingSubstitution.lagda.md
Labels: No Changelog Required

#5289 Update note of `sm_pre_inline`.
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
Labels: No Changelog Required

#5295 1.6.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20230407_134939_unsafeFixIO_cokc.md
  plutus-core/changelog.d/20230414_110912_marty.stumpf_plt_5439_ensure_global_uniqueness.md
  plutus-core/changelog.d/20230414_163043_michael.peyton-jones_products_and_sums_4_real_batch_2.md
  plutus-core/changelog.d/20230418_193516_effectfully_newtype_intercept_and_slope.md
  plutus-core/changelog.d/20230424_114427_michael.peyton-jones_generic_constant_fold.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20230418_152734_michael.peyton-jones_plutus_v3_in_conway.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20230414_163204_michael.peyton-jones_products_and_sums_4_real_batch_2.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20230414_163112_michael.peyton-jones_products_and_sums_4_real_batch_2.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5296 Address some comments
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
Labels: No Changelog Required

#5291 [Textual] Propagate 'PrettyReadable' throughout everything
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Default.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty/Classic.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty/Extra.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty/Readable.hs
  plutus-core/plutus-core/test/Evaluation/Spec.hs
  plutus-core/plutus-core/test/Pretty/Golden/Readable/Examples/Data/ofoldrData.golden
  plutus-core/plutus-core/test/Pretty/Golden/Readable/StdLib/Data/Data/caseData.golden
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Error.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-ir/src/PlutusIR/Error.hs
  plutus-core/testlib/PlutusIR/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Default.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/CommonAPI.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Error.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Lib.hs
  plutus-tx/src/PlutusTx/Lift.hs
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: Textual representation, No Changelog Required

#5305 Add Eq for CostModelApplyError
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
Labels: No Changelog Required

#5314 1.6.1.0
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
Labels: No Changelog Required

#5275 Update the spec for SOPs
  doc/plutus-core-spec/builtins-alonzo.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/plutus-core-specification.pdf
  doc/plutus-core-spec/plutus-core-specification.tex
  doc/plutus-core-spec/untyped-cek-machine.tex
  doc/plutus-core-spec/untyped-grammar.tex
  doc/plutus-core-spec/untyped-reduction.tex
  doc/plutus-core-spec/untyped-values.tex
Labels: No Changelog Required

#5297 Bump to GHC 9.2.7 and bump haskell.nix
  flake.lock
  flake.nix
  nix/cells/plutus/devshells/plutus-shell-92.nix
  nix/cells/plutus/library/ghc-compiler-nix-name.nix
  nix/cells/plutus/library/plutus-project-92.nix
  plutus-tx-plugin/test/Budget/show.budget.golden
  plutus-tx-plugin/test/Budget/show.pir-readable.golden
  plutus-tx-plugin/test/Budget/show.uplc.golden
Labels: No Changelog Required

#5311 [PlutusTx] [Test] Add 'InterList'
  plutus-tx-plugin/test/Lib.hs
  plutus-tx-plugin/test/Plugin/Data/Spec.hs
  plutus-tx-plugin/test/Plugin/Data/recursive/interListConstruct.tplc.golden
  plutus-tx-plugin/test/Plugin/Data/recursive/processInterListEval.ueval.golden
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: Test, Plutus Tx, No Changelog Required

#5304 [Refactoring] Prettify 'Pretty' constraints
  plutus-core/executables/uplc/Main.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Default.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-core/src/PlutusCore/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty/PrettyConst.hs
  plutus-core/plutus-core/test/Evaluation/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Error.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-ir/src/PlutusIR/Error.hs
  plutus-core/testlib/PlutusIR/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Default.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/CommonAPI.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Debug.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Error.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Lib.hs
  plutus-tx/src/PlutusTx/Lift.hs
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: Refactoring, Textual representation, No Changelog Required

#5298 Address comments from PR #5251
  plutus-core/plutus-core/src/PlutusCore/Check/Uniques.hs
  plutus-core/plutus-ir/test/TransformSpec.hs
Labels: No Changelog Required

#5318 [PlutusIR] [Compile] Replace a lambda with 'unveilDatatype'
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
  plutus-core/plutus-ir/test/datatypes/listMatch.golden
  plutus-core/plutus-ir/test/datatypes/maybe.golden
  plutus-core/plutus-ir/test/recursion/even3.golden
  plutus-core/plutus-ir/test/recursion/stupidZero.golden
  plutus-tx-plugin/test/Plugin/Data/recursive/interListConstruct.tplc.golden
Labels: Plutus IR, Refactoring, No Changelog Required

#5320 Update style guide regarding indentation and type signature
  STYLEGUIDE.adoc
Labels: No Changelog Required

#5326 Stop publishing haddock for releases
  .github/workflows/haddock.yml
Labels: No Changelog Required

#5327 Add Data instance for CostModelApplyError for easier testing
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
Labels: No Changelog Required

#5330 hex-text got updated on Hackage
  cabal.project
  flake.lock
Labels: No Changelog Required

#5332 Try to fix the longitudinal benchmarking job
  scripts/run-longitudinal-benchmarks.sh
Labels: No Changelog Required

#5317 Enable editorconfig checker and reduce indentation for a few modules
  plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty/Readable.hs
  plutus-core/plutus-core/src/Prettyprinter/Custom.hs
  plutus-core/plutus-ir/src/PlutusIR/Analysis/Usages.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Definitions.hs
  plutus-core/plutus-ir/src/PlutusIR/Mark.hs
  plutus-core/plutus-ir/src/PlutusIR/Subst.hs
Labels: No Changelog Required

#5336 Update plutus-benchmark.cabal
  plutus-benchmark/plutus-benchmark.cabal
Labels: No Changelog Required

#5334 Add --silent option to plc/pir/uplc commands
  plutus-core/executables/pir/Main.hs
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
  plutus-core/executables/src/PlutusCore/Executable/Types.hs
Labels: No Changelog Required

#5338 Format and line lengths for some modules
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Analysis/Dependencies.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/LetFloatIn.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/Substitute.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/testlib/PlutusIR/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/FloatDelay.hs
  plutus-core/untyped-plutus-core/test/DeBruijn/Common.hs
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: No Changelog Required

#5321 [Costing] Fix rendering in budgeting benchmarks
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/cost-model/data/benching.csv
  plutus-core/cost-model/data/models.R
Labels: Costs, No Changelog Required

#5342 Run script-evaluation-test on default GH runner instead of plutus-benchmark
  .github/workflows/script-evaluation-test.yml
Labels: No Changelog Required

#5343 [Test] [Builtins] Use 'BuiltinsRuntime' in no-exceptions tests
  plutus-core/plutus-core/test/Evaluation/Spec.hs
Labels: Test, Refactoring, Builtins, No Changelog Required

#5341 Prepare release 1.7
  doc/read-the-docs-site/RELEASE.adoc
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20230504_085210_marty.stumpf_add_fn_to_exec.md
  plutus-core/changelog.d/20230506_130703_unsafeFixIO_float_delay.md
  plutus-core/changelog.d/20230512_073658_marty.stumpf_add_err_msg.md
  plutus-core/changelog.d/20230517_182732_effectfully_improve_readable_pretty_printing.md
  plutus-core/changelog.d/20230518_105650_michael.peyton-jones_plugin_9_6.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20230518_105719_michael.peyton-jones_plugin_9_6.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20230518_105617_michael.peyton-jones_plugin_9_6.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20230503_111617_unsafeFixIO_fold.md
  plutus-tx/changelog.d/20230504_121943_unsafeFixIO_lift_pir.md
  plutus-tx/changelog.d/20230518_105705_michael.peyton-jones_plugin_9_6.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
  scripts/prepare-release.sh
Labels: No Changelog Required

#5346 Bump inline-r and remove s-r-p
  cabal.project
  flake.lock
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#5349 Add nofib and lists to the list of longitudinal benchmarks
  .github/workflows/longitudinal-benchmark.yml
Labels: No Changelog Required

#5351 Don't build much on aarch64-darwin
  nix/cells/automation/ciJobs.nix
Labels: No Changelog Required

#5344 PLT-6006: Purge the use of int-cast lib
  cabal.project
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/GHC/Natural/Extras.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Flat.hs
Labels: No Changelog Required

#5356 [Builtins] [Evaluation] Retain 'cost' in a different way
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
Labels: No Changelog Required
