Repository IntersectMBO/plutus, pull requests merged in 2023-07, with the labels that each got.

#5413 Add Typeable and IsData instances for BLS12-381 types (PLT-6512)
  plutus-tx/src/PlutusTx/IsData/Class.hs
  plutus-tx/src/PlutusTx/Lift/Class.hs
Labels: No Changelog Required

#5411 Kwxm/costing/linear in x and y
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
Labels: No Changelog Required

#5405 Kwxm/spec/bls12 381
  doc/plutus-core-spec/Makefile
  doc/plutus-core-spec/builtins-future.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/notation.tex
  doc/plutus-core-spec/plutus-core-specification.bib
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: Specification, Builtins, No Changelog Required

#5418 Fix some typos
  doc/plutus-core-spec/builtins-future.tex
  doc/plutus-core-spec/header.tex
Labels: No Changelog Required

#5417 Fix safeToBetaReduce in PIR call site inliner
  plutus-benchmark/lists/test/Sum/left-fold-data.budget.golden
  plutus-benchmark/lists/test/Sum/right-fold-data.budget.golden
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/CallSiteInline.hs
  plutus-core/plutus-ir/test/transform/inline/callsite-non-trivial-body
  plutus-core/plutus-ir/test/transform/inline/callsite-non-trivial-body.golden
  plutus-tx-plugin/test/Budget/show.budget.golden
  plutus-tx-plugin/test/Budget/show.pir-readable.golden
  plutus-tx-plugin/test/Budget/show.uplc-readable.golden
Labels: No Changelog Required

#5422 Bump lower bound on cardano-crypto-class
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#5410 Remove outdated info and fix alignment in Release.adoc
  doc/read-the-docs-site/RELEASE.adoc
Labels: No Changelog Required

#5424 Bump hackage and fix some issues
  cabal.project
  flake.lock
  plutus-core/plutus-core.cabal
  plutus-metatheory/plutus-metatheory.cabal
Labels: No Changelog Required

#5420 Fix safeToBetaReduce in UPLC inliner and update uplc test.
  plutus-benchmark/nofib/test/Spec.hs
  plutus-benchmark/nofib/test/formulaBudget.budget.golden
  plutus-benchmark/nofib/test/knightsBudget.budget.golden
  plutus-benchmark/nofib/test/queens4budget.budget.golden
  plutus-benchmark/nofib/test/queens5budget.budget.golden
  plutus-benchmark/script-contexts/test/Spec.hs
  plutus-benchmark/script-contexts/test/checkScriptContext1-20.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext1-4.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2-20.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2-4.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContextEqualityTerm-20.budget.golden
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
  plutus-core/untyped-plutus-core/test/Transform/callsiteInline.uplc.golden
  plutus-tx-plugin/test/Budget/show.budget.golden
  plutus-tx-plugin/test/Budget/show.uplc-readable.golden
  plutus-tx-plugin/test/Budget/toFromData.budget.golden
  plutus-tx-plugin/test/Budget/toFromData.uplc-readable.golden
  plutus-tx-plugin/test/size/Main.hs
Labels: No Changelog Required

#5425 Revert mistaken change
  plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
  plutus-ledger-api/test/Spec/Versions.hs
Labels: No Changelog Required

#5423 Fix rolepayout benchmarks.
  plutus-benchmark/marlowe/bench/Bench.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics/Types.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/RolePayout.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/Semantics.hs
Labels: No Changelog Required

#5383 More Bls benchmark tests
  plutus-benchmark/bls12-381-costs/bench/Bench.hs
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/RunTests.hs
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/bls12-381-costs/test/bls12-381-costs.golden
  plutus-benchmark/plutus-benchmark.cabal
Labels: No Changelog Required

#5428 Update golden files for BLS12-381 tests
  plutus-benchmark/bls12-381-costs/test/bls12-381-costs.golden
Labels: No Changelog Required

#5432 1.5.0.1
  flake.nix
  plutus-core/plutus-core.cabal
  plutus-ledger-api/test/Spec/Versions.hs
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#5430 Fix Vulnerability issue in read-the-docs-site
  doc/read-the-docs-site/requirements.txt
Labels: No Changelog Required

#5435 Address more comments on the SOPs in PIR
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
Labels: No Changelog Required

#5434 [Builtins] Make elaboration customizable and unhardcode 'mkTyBuiltin'
  plutus-core/changelog.d/20230724_195443_effectfully_make_elaboration_of_builtins_customizable.md
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Unit.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Data/Data.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Data/InterList.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Data/Shad.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Data/Vec.hs
  plutus-core/plutus-core/src/PlutusCore.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Debug.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Elaborate.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/TestKnown.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/TypeScheme.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Type.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/MkPlc.hs
  plutus-core/plutus-core/src/Universe/Core.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Bool.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Data.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Integer.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/List.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Nat.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Pair.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/ScottList.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Unit.hs
  plutus-core/plutus-core/test/TypeSynthesis/Spec.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Builtin.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Denotation.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Entity.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/ShrinkTypes.hs
  plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx/src/PlutusTx/Lift/Class.hs
  plutus-tx/src/PlutusTx/Show.hs
Labels: Refactoring, Builtins

#5431 Keccak-256 and Blake2b-224 (PLT-6305, PLT-6306, PLT-6311, PLT-6820)
  plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
  plutus-core/changelog.d/20230720_184504_kenneth.mackenzie_keccak256.md
  plutus-core/cost-model/budgeting-bench/Benchmarks/Crypto.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching.csv
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Crypto/Hash.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/plutus-core/test/CostModelInterface/Spec.hs
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-core/plutus-ir/src/PlutusIR/Transform/CommuteFnWithConst.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Denotation.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Term.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/changelog.d/20230720_184626_kenneth.mackenzie_keccak256.md
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-metatheory/src/Algorithmic/CEK.lagda.md
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx/changelog.d/20230720_184825_kenneth.mackenzie_keccak256.md
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Prelude.hs
Labels: Builtins, Crypto

#5439 Update longitudinal-benchmark.yml
  .github/workflows/longitudinal-benchmark.yml
Labels: No Changelog Required

#5444 Improve error messages in ScriptContext benchmarks
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-benchmark/script-contexts/test/Spec.hs
Labels: No Changelog Required

#5445 Fix doc links for another hydra move
  README.adoc
Labels: No Changelog Required

#5446 Add missing golden files
  plutus-core/plutus-core/test/TypeSynthesis/Golden/Blake2b_224.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/Keccak_256.plc.golden
Labels: No Changelog Required
