Repository IntersectMBO/plutus, pull requests merged in 2023-09, with the labels that each got.

#5507 Update the download link and the date on the specification
  doc/plutus-core-spec/Makefile
  doc/plutus-core-spec/README.md
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: No Changelog Required

#5514 Fix longitudinal benchmark
  plutus-benchmark/validation/Common.hs
Labels: No Changelog Required

#5513 Improve an error message of the compiler.
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Let.hs
  plutus-core/plutus-ir/test/errors/recursiveTypeBind.golden
Labels: No Changelog Required

#5517 Fix semantic merge conflict in test output
  plutus-tx-plugin/test/Plugin/Patterns/9.2/psym1.pir-readable.golden
  plutus-tx-plugin/test/Plugin/Patterns/9.2/psymRec.pir-readable.golden
  plutus-tx-plugin/test/Plugin/Patterns/9.6/psym1.pir-readable.golden
  plutus-tx-plugin/test/Plugin/Patterns/9.6/psymRec.pir-readable.golden
Labels: No Changelog Required

#5522 Remove use of Data.ByteArray.convert
  plutus-metatheory/src/Builtin.lagda.md
Labels: Metatheory, No Changelog Required

#5524 Fix testReduce
  plutus-tx-plugin/test/StdLib/Spec.hs
Labels: No Changelog Required

#5523 Add Documentation on GHC Extensions, Flags and Pragmas
  doc/read-the-docs-site/extensions-flags-pragmas.rst
  doc/read-the-docs-site/index.rst
Labels: No Changelog Required

#5526 Add workflow to run the cost model benchmark.
  .github/workflows/cost-model-bench.yml
Labels: No Changelog Required

#5506 Kwxm/cost model representations
  doc/notes/cost-model-representations/cost-model-representations.md
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
Labels: Docs, Costs, No Changelog Required

#5529 Change commit used when running benchmarks
  scripts/ci-plutus-benchmark.sh
Labels: No Changelog Required

#5528 PLT-6722 Convert `fitsInto` tests to golden tests
  plutus-benchmark/nofib/test/Bt.uplc-size.golden
  plutus-benchmark/nofib/test/Spec.hs
  plutus-benchmark/nofib/test/depth10-4x4.uplc-size.golden
  plutus-benchmark/nofib/test/formula1.uplc-size.golden
  plutus-benchmark/script-contexts/test/Spec.hs
  plutus-benchmark/script-contexts/test/checkScriptContext1.uplc-size.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2.uplc-size.golden
  plutus-tx-plugin/abs-specialized.uplc-size.golden
  plutus-tx-plugin/compare.uplc-size.golden
  plutus-tx-plugin/denominator.uplc-size.golden
  plutus-tx-plugin/equal.uplc-size.golden
  plutus-tx-plugin/fromBuiltinData.uplc-size.golden
  plutus-tx-plugin/fromInteger.uplc-size.golden
  plutus-tx-plugin/greater-than-equal.uplc-size.golden
  plutus-tx-plugin/greater-than.uplc-size.golden
  plutus-tx-plugin/less-than-equal.uplc-size.golden
  plutus-tx-plugin/less-than.uplc-size.golden
  plutus-tx-plugin/max.uplc-size.golden
  plutus-tx-plugin/min.uplc-size.golden
  plutus-tx-plugin/minus.uplc-size.golden
  plutus-tx-plugin/negate-specialized.uplc-size.golden
  plutus-tx-plugin/not-equal.uplc-size.golden
  plutus-tx-plugin/numerator.uplc-size.golden
  plutus-tx-plugin/one.uplc-size.golden
  plutus-tx-plugin/plus.uplc-size.golden
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/properFraction.uplc-size.golden
  plutus-tx-plugin/ratio.uplc-size.golden
  plutus-tx-plugin/recip.uplc-size.golden
  plutus-tx-plugin/round.uplc-size.golden
  plutus-tx-plugin/scale.uplc-size.golden
  plutus-tx-plugin/test/size/Main.hs
  plutus-tx-plugin/times.uplc-size.golden
  plutus-tx-plugin/toBuiltinData.uplc-size.golden
  plutus-tx-plugin/truncate.uplc-size.golden
  plutus-tx-plugin/unsafeFromBuiltinData.uplc-size.golden
  plutus-tx-plugin/unsafeRatio.uplc-size.golden
  plutus-tx-plugin/zero.uplc-size.golden
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: No Changelog Required

#5531 Fix JS regex syntax
  .github/workflows/benchmark.yml
Labels: No Changelog Required

#5532 AsData: transfer deriving clauses from the quoted declaration
  plutus-tx-plugin/test/IsData/Spec.hs
  plutus-tx/src/PlutusTx/AsData.hs
Labels: No Changelog Required

#5533 Produce more sensible matcher names
  plutus-benchmark/nofib/test/formulaBudget.pir-readable.golden
  plutus-benchmark/nofib/test/knightsBudget.pir-readable.golden
  plutus-benchmark/script-contexts/test/checkScriptContext1.pir-readable.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2.pir-readable.golden
  plutus-core/plutus-ir/test/transform/knownCon/list
  plutus-core/plutus-ir/test/transform/knownCon/list.golden
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
  plutus-tx-plugin/test/Budget/9.2/allCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/allEmptyList.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/allExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/andCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/andExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/anyCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/anyEmptyList.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/anyExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/elemCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/elemExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/filter.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/findCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/findEmptyList.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/findExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/findIndexCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/findIndexEmptyList.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/findIndexExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/notElemCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/notElemExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/null.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/orCheap.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/orExpensive.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/show.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.2/sum.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/show.budget.golden
  plutus-tx-plugin/test/Budget/9.6/show.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/show.uplc-readable.golden
  plutus-tx-plugin/test/IsData/9.2/dataToData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.2/fieldAccessor.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.2/matchAsData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.2/recordAsData.pir-readable.golden
  plutus-tx-plugin/test/Optimization/9.2/matchAsData.pir-readable.golden
  plutus-tx-plugin/test/Plugin/Data/9.2/families/basicData.pir.golden
  plutus-tx-plugin/test/Plugin/Data/9.2/recursive/listConstruct.pir.golden
  plutus-tx-plugin/test/Plugin/Data/9.2/recursive/listConstruct2.pir.golden
  plutus-tx-plugin/test/Plugin/Data/9.2/recursive/listConstruct3.pir.golden
  plutus-tx-plugin/test/Plugin/Data/9.2/recursive/listMatch.pir.golden
  plutus-tx-plugin/test/Plugin/Data/9.2/recursive/sameEmptyRose.uplc.golden
  plutus-tx-plugin/test/Plugin/Data/9.6/families/basicData.pir.golden
  plutus-tx-plugin/test/Plugin/Functions/9.2/recursive/lazyLength.pir.golden
  plutus-tx-plugin/test/Plugin/Functions/9.2/recursive/strictLength.pir.golden
  plutus-tx-plugin/test/Plugin/Functions/9.2/recursive/sum.pir.golden
  plutus-tx-plugin/test/Plugin/Functions/9.2/unfoldings/allDirect.pir.golden
  plutus-tx-plugin/test/Plugin/Functions/9.2/unfoldings/polyMap.pir.golden
  plutus-tx-plugin/test/Plugin/Primitives/9.2/deconstructorData2.pir.golden
  plutus-tx-plugin/test/Plugin/Typeclasses/9.2/concatTest.pir.golden
  plutus-tx-plugin/test/Plugin/Typeclasses/9.2/fmapDefaultTest.pir.golden
  plutus-tx-plugin/test/Plugin/Typeclasses/9.2/sequenceTest.pir.golden
  plutus-tx-plugin/test/Plugin/Typeclasses/9.2/sumTest.pir.golden
Labels: No Changelog Required

#5534 Make BLS, keccak, blake primitives available in conwayPV
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
Labels: No Changelog Required

#5535 Backport #5534 to 1.9
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
Labels: No Changelog Required

#5537 [Test] Add forgotten budget golden files
  plutus-tx-plugin/test/Budget/9.6/constAccL.budget.golden
  plutus-tx-plugin/test/Budget/9.6/constAccL.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constAccL.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constAccR.budget.golden
  plutus-tx-plugin/test/Budget/9.6/constAccR.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constAccR.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constElL.budget.golden
  plutus-tx-plugin/test/Budget/9.6/constElL.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constElL.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constElR.budget.golden
  plutus-tx-plugin/test/Budget/9.6/constElR.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/constElR.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/gte0.budget.golden
  plutus-tx-plugin/test/Budget/9.6/gte0.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/gte0.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/lte0.budget.golden
  plutus-tx-plugin/test/Budget/9.6/lte0.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/lte0.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/recursiveGte0.budget.golden
  plutus-tx-plugin/test/Budget/9.6/recursiveGte0.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/recursiveGte0.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/recursiveLte0.budget.golden
  plutus-tx-plugin/test/Budget/9.6/recursiveLte0.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/recursiveLte0.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/sumL.budget.golden
  plutus-tx-plugin/test/Budget/9.6/sumL.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/sumL.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/sumR.budget.golden
  plutus-tx-plugin/test/Budget/9.6/sumR.pir-readable.golden
  plutus-tx-plugin/test/Budget/9.6/sumR.uplc-readable.golden
Labels: Test, Plutus Tx, No Changelog Required

#5536 1.9.1.0
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5525 [Docs] [Builtins] Bring docs up to date
  plutus-core/docs/BuiltinsIntro.md
  plutus-core/docs/BuiltinsOverview.md
  plutus-core/plutus-core/src/PlutusCore/Builtin/Elaborate.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/TypeScheme.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: No Changelog Required

#5544 Prepare release 1.13
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20230718_092435_marty.stumpf_drop_fully_inline_cond_pir.md
  plutus-core/changelog.d/20230901_114457_kenneth.mackenzie_builtin_semantics_option.md
  plutus-core/changelog.d/20230905_103624_bezirg_cmparams_testing.md
  plutus-core/changelog.d/20230907_110347_michael.peyton-jones_effectful_term.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20230904_141042_bezirg_fix_1_11.md
  plutus-ledger-api/changelog.d/20230905_103632_bezirg_cmparams_testing.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20230901_163607_michael.peyton-jones_plugin_pattern_synonyms.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20230901_174602_michael.peyton-jones_asData.md
  plutus-tx/changelog.d/20230904_141050_bezirg_fix_1_11.md
  plutus-tx/changelog.d/20230915_113114_michael.peyton-jones_strictness_isdata.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5550 Speed up AsData
  plutus-tx-plugin/test/Budget/9.2/matchAsDataE.budget.golden
  plutus-tx-plugin/test/Budget/9.6/matchAsDataE.budget.golden
  plutus-tx-plugin/test/Budget/Spec.hs
  plutus-tx-plugin/test/IsData/9.2/dataToData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.2/fieldAccessor.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.2/matchAsData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.2/matchAsDataE.ueval.golden
  plutus-tx-plugin/test/IsData/9.2/recordAsData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.6/dataToData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.6/fieldAccessor.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.6/matchAsData.pir-readable.golden
  plutus-tx-plugin/test/IsData/9.6/matchAsDataE.ueval.golden
  plutus-tx-plugin/test/IsData/9.6/recordAsData.pir-readable.golden
  plutus-tx-plugin/test/Optimization/9.2/matchAsData.pir-readable.golden
  plutus-tx-plugin/test/Optimization/9.2/unsafeDeconstructData.pir-readable.golden
  plutus-tx-plugin/test/Optimization/9.6/matchAsData.pir-readable.golden
  plutus-tx-plugin/test/Optimization/9.6/unsafeDeconstructData.pir-readable.golden
  plutus-tx-plugin/test/Optimization/Spec.hs
  plutus-tx/src/PlutusTx/AsData.hs
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/IsData/TH.hs
Labels: No Changelog Required

#5558 Update copyright year
  doc/read-the-docs-site/NOTICE
  doc/read-the-docs-site/conf.py
  plutus-benchmark/NOTICE
  plutus-conformance/NOTICE
  plutus-core/NOTICE
  plutus-ledger-api/NOTICE
  plutus-metatheory/NOTICE
  plutus-tx-plugin/NOTICE
  plutus-tx/NOTICE
  prettyprinter-configurable/NOTICE
  stubs/plutus-ghc-stub/NOTICE
Labels: No Changelog Required

#5541 Redo UPLC purity analysis to match PIR
  plutus-benchmark/bls12-381-costs/test/bls12-381-costs.golden
  plutus-benchmark/ed25519-costs/test/ed25519-costs.golden
  plutus-benchmark/nofib/test/Bt.uplc-size.golden
  plutus-benchmark/nofib/test/depth10-4x4.uplc-size.golden
  plutus-benchmark/nofib/test/formula1.uplc-size.golden
  plutus-benchmark/nofib/test/formulaBudget.budget.golden
  plutus-benchmark/nofib/test/knightsBudget.budget.golden
  plutus-benchmark/nofib/test/queens4budget.budget.golden
  plutus-benchmark/nofib/test/queens5budget.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext1-20.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext1-4.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext1.uplc-size.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2-20.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2-4.budget.golden
  plutus-benchmark/script-contexts/test/checkScriptContext2.uplc-size.golden
  plutus-benchmark/script-contexts/test/checkScriptContextEqualityTerm-20.budget.golden
  plutus-core/plutus-core.cabal
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Purity.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
  plutus-core/untyped-plutus-core/test/Analysis/Spec.hs
  plutus-core/untyped-plutus-core/test/Analysis/evalOrder/letFun.golden
  plutus-core/untyped-plutus-core/test/Analysis/evalOrder/letImpure.golden
  plutus-core/untyped-plutus-core/test/Spec.hs
  plutus-core/untyped-plutus-core/test/Transform/Simplify.hs
  plutus-core/untyped-plutus-core/test/Transform/inlinePure4.uplc.golden
  plutus-tx-plugin/test/Budget/9.2/matchAsDataE.budget.golden
  plutus-tx-plugin/test/Budget/9.2/show.budget.golden
  plutus-tx-plugin/test/Budget/9.2/show.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.2/sumL.budget.golden
  plutus-tx-plugin/test/Budget/9.2/sumL.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.2/sumR.budget.golden
  plutus-tx-plugin/test/Budget/9.2/sumR.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.2/toFromData.budget.golden
  plutus-tx-plugin/test/Budget/9.2/toFromData.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/matchAsDataE.budget.golden
  plutus-tx-plugin/test/Budget/9.6/show.budget.golden
  plutus-tx-plugin/test/Budget/9.6/show.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/sumL.budget.golden
  plutus-tx-plugin/test/Budget/9.6/sumL.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/sumR.budget.golden
  plutus-tx-plugin/test/Budget/9.6/sumR.uplc-readable.golden
  plutus-tx-plugin/test/Budget/9.6/toFromData.budget.golden
  plutus-tx-plugin/test/Budget/9.6/toFromData.uplc-readable.golden
  plutus-tx-plugin/test/Plugin/Strict/9.2/issue4645.eval-cek-log.golden
  plutus-tx-plugin/test/Plugin/Strict/9.6/issue4645.eval-cek-log.golden
  plutus-tx-plugin/test/Plugin/Strict/Spec.hs
  plutus-tx-plugin/test/size/fromBuiltinData.uplc-size.golden
  plutus-tx-plugin/test/size/minus.uplc-size.golden
  plutus-tx-plugin/test/size/plus.uplc-size.golden
  plutus-tx-plugin/test/size/properFraction.uplc-size.golden
  plutus-tx-plugin/test/size/ratio.uplc-size.golden
  plutus-tx-plugin/test/size/recip.uplc-size.golden
  plutus-tx-plugin/test/size/round.uplc-size.golden
  plutus-tx-plugin/test/size/scale.uplc-size.golden
  plutus-tx-plugin/test/size/times.uplc-size.golden
  plutus-tx-plugin/test/size/unsafeFromBuiltinData.uplc-size.golden
  plutus-tx-plugin/test/size/unsafeRatio.uplc-size.golden
Labels: No Changelog Required

#5556 Add plutus-cert and wire it up, alternative version
  cabal.project
  nix/cells/plutus/library/make-plutus-project.nix
  nix/cells/plutus/library/make-plutus-shell.nix
  plutus-core/plutus-core.cabal
  plutus-core/plutus-ir/cert-stub/PlutusIR/Certifier.hs
  plutus-core/plutus-ir/cert/PlutusIR/Certifier.hs
Labels: No Changelog Required

#5563 Add testing section to CONTRIBUTING
  CONTRIBUTING.adoc
Labels: No Changelog Required

#5567 1.14.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20230920_113238_michael.peyton-jones_varinfo.md
  plutus-core/changelog.d/20230925_151749_bezirg_fix_thunkrecursions.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20230913_145648_unsafeFixIO_ledger_api.md
  plutus-ledger-api/changelog.d/20230915_103539_unsafeFixIO_major.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5569 Switch up cabal flag setup to avoid cabal bug
  cabal.project
Labels: No Changelog Required
