Repository IntersectMBO/plutus, pull requests merged in 2023-02, with the labels that each got.

#5126 [WIP] Add check-changelog.yml workflow
  .github/workflows/check-changelog.yml
  .github/workflows/pre-commit-check.yml
  .gitignore
  CONTRIBUTING.adoc
Labels: No Changelog Required

#5131 Update to 9.2.5
  nix/README.md
  nix/cells/automation/ciJobs.nix
  nix/cells/plutus/devshells/default.nix
  nix/cells/plutus/devshells/plutus-shell-924.nix
  nix/cells/plutus/devshells/plutus-shell-925.nix
  nix/cells/plutus/library/agda-packages.nix
  nix/cells/plutus/library/cabal-project-index-state.nix
  nix/cells/plutus/library/default.nix
  nix/cells/plutus/library/ghc-compiler-nix-name.nix
  nix/cells/plutus/library/plutus-project-924.nix
  nix/cells/plutus/library/plutus-project-925.nix
  nix/cells/plutus/packages/combined-plutus-haddock.nix
  nix/cells/plutus/packages/ghc.nix
  plutus-tx-plugin/test/Budget/show.budget.golden
  plutus-tx-plugin/test/Budget/show.plc.golden
Labels: No Changelog Required

#5136 Small updates to CONTRIBUTING.adoc
  CONTRIBUTING.adoc
  doc/read-the-docs-site/troubleshooting.rst
Labels: No Changelog Required

#5137 Update S3 link in script-evaluaton-test.yml
  .github/workflows/script-evaluation-test.yml
Labels: No Changelog Required

#5140 Removed obsolete inputs from the flake
  flake.lock
  flake.nix
  nix/README.md
  nix/cells/plutus/library/make-plutus-shell.nix
Labels: No Changelog Required

#5139 [WIP] Integrate Slack Webhook with script-evaluation-test.yml
  .github/workflows/script-evaluation-test.yml
Labels: No Changelog Required

#5143 [Ledger API] Expose 'mkTermToEvaluate'
  plutus-ledger-api/changelog.d/20230215_170512_effectfully_expose_mkTermToEvaluate.md
  plutus-ledger-api/src/PlutusLedgerApi/Common.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
Labels: User experience, Ledger

#5061 PLT-1432: [Builtins] Make 'geq' inlinable
  plutus-core/changelog.d/20230215_190332_effectfully_inlinable_geq.md
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
Labels: Evaluation, Builtins, Performance, Don't look here yet

#5149 Add Slack Notifications for script-evaluation-test Workflow
  .github/workflows/script-evaluation-test.yml
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#5158 Publish Haddock for each release
  .github/workflows/haddock.yml
Labels: No Changelog Required

#5162 Added note on pre-commit to contributing.adoc
  CONTRIBUTING.adoc
Labels: No Changelog Required

#5164 Update of the builtin document
  doc/notes/plutus-core/Builtins_Overview.md
Labels: No Changelog Required

#5165 Update version bounds for cardano-crypto-class
  cabal.project
  flake.lock
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#5167 PLT-1539: Add some budget tests related to Foldable and Bool
  plutus-tx-plugin/test/Budget/Spec.hs
  plutus-tx-plugin/test/Budget/allCheap.budget.golden
  plutus-tx-plugin/test/Budget/allCheap.plc.golden
  plutus-tx-plugin/test/Budget/allEmptyList.budget.golden
  plutus-tx-plugin/test/Budget/allEmptyList.plc.golden
  plutus-tx-plugin/test/Budget/allExpensive.budget.golden
  plutus-tx-plugin/test/Budget/allExpensive.plc.golden
  plutus-tx-plugin/test/Budget/anyCheap.budget.golden
  plutus-tx-plugin/test/Budget/anyCheap.plc.golden
  plutus-tx-plugin/test/Budget/anyEmptyList.budget.golden
  plutus-tx-plugin/test/Budget/anyEmptyList.plc.golden
  plutus-tx-plugin/test/Budget/anyExpensive.budget.golden
  plutus-tx-plugin/test/Budget/anyExpensive.plc.golden
  plutus-tx-plugin/test/Budget/findCheap.budget.golden
  plutus-tx-plugin/test/Budget/findCheap.plc.golden
  plutus-tx-plugin/test/Budget/findEmptyList.budget.golden
  plutus-tx-plugin/test/Budget/findEmptyList.plc.golden
  plutus-tx-plugin/test/Budget/findExpensive.budget.golden
  plutus-tx-plugin/test/Budget/findExpensive.plc.golden
Labels: No Changelog Required

#5172 Update "Note [Differences from PIR inliner]"
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Labels: No Changelog Required

#5175 Explain publishing Haddock in the release doc
  doc/read-the-docs-site/RELEASE.adoc
Labels: No Changelog Required

#5169 Update s3 bucket link in script-evaluation-test.yml
  .github/workflows/script-evaluation-test.yml
Labels: No Changelog Required

#5177 Fix small bug in benchmark.yml
  .github/workflows/benchmark.yml
Labels: No Changelog Required

#5171 Use unique-less readable PIR for Budget.Spec
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty/Readable.hs
  plutus-tx-plugin/test/Budget/Spec.hs
  plutus-tx-plugin/test/Budget/allCheap.plc.golden
  plutus-tx-plugin/test/Budget/allEmptyList.plc.golden
  plutus-tx-plugin/test/Budget/allExpensive.plc.golden
  plutus-tx-plugin/test/Budget/anyCheap.plc.golden
  plutus-tx-plugin/test/Budget/anyEmptyList.plc.golden
  plutus-tx-plugin/test/Budget/anyExpensive.plc.golden
  plutus-tx-plugin/test/Budget/applicative.plc.golden
  plutus-tx-plugin/test/Budget/elem.plc.golden
  plutus-tx-plugin/test/Budget/filter.plc.golden
  plutus-tx-plugin/test/Budget/findCheap.plc.golden
  plutus-tx-plugin/test/Budget/findEmptyList.plc.golden
  plutus-tx-plugin/test/Budget/findExpensive.plc.golden
  plutus-tx-plugin/test/Budget/ifThenElse1.plc.golden
  plutus-tx-plugin/test/Budget/ifThenElse2.plc.golden
  plutus-tx-plugin/test/Budget/monadicDo.plc.golden
  plutus-tx-plugin/test/Budget/patternMatch.plc.golden
  plutus-tx-plugin/test/Budget/show.plc.golden
  plutus-tx-plugin/test/Budget/sum.plc.golden
  plutus-tx-plugin/test/Budget/toFromData.plc.golden
  plutus-tx/plutus-tx.cabal
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: No Changelog Required
