Repository IntersectMBO/plutus, pull requests merged in 2023-04, with the labels that each got.

#5243 List the packages that require changelogs
  CONTRIBUTING.adoc
Labels: No Changelog Required

#5241 PLT-115 Merge CK and CEK BUILTIN function
  plutus-metatheory/src/Algorithmic/BehaviouralEquivalence/CKvsCEK.lagda.md
  plutus-metatheory/src/Algorithmic/ReductionEC.lagda.md
Labels: No Changelog Required

#5189 Kwxm/expose optimisers 3 (PLT-1145)
  plutus-core/changelog.d/20230220_085551_kenneth.mackenzie_expose_optimisers.md
  plutus-core/executables/pir/Main.hs
  plutus-core/executables/plc/Main.hs
  plutus-core/executables/src/PlutusCore/Executable/AstIO.hs
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
  plutus-core/executables/src/PlutusCore/Executable/Types.hs
  plutus-core/executables/uplc/Main.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/Pretty.hs
  plutus-core/plutus-core/src/PlutusCore/Subst.hs
  plutus-core/plutus-core/test/Names/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty/Readable.hs
  plutus-metatheory/src/Main.lagda
Labels: Plutus IR, Plutus Exe

#5247 Some cleanup
  .gitattributes
  .gitignore
  .ignore
  NOTICE
  doc/read-the-docs-site/README.md
  nix/cells/plutus/packages/pre-commit-check.nix
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-ledger-api/plutus-ledger-api.cabal
Labels: No Changelog Required

#5254 UPLC inliner should not think force is cost-okay
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Labels: No Changelog Required

#5257 1.5.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20230220_085551_kenneth.mackenzie_expose_optimisers.md
  plutus-core/changelog.d/20230324_110825_marty.stumpf_plt_1146_inline_sat_fns_imp.md
  plutus-core/changelog.d/20230328_124228_michael.peyton-jones_products_and_sums_4_real_batch_1.md
  plutus-core/changelog.d/20230328_150430_michael.peyton-jones_remove_flat_instances.md
  plutus-core/changelog.d/20230403_145946_effectfully_lazy_costing.md
  plutus-core/changelog.d/20230404_101543_bezirg_dbg_conform_eval.md
  plutus-core/changelog.d/20230404_120804_bezirg_fix_safeencodebits.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20230328_150603_michael.peyton-jones_remove_flat_instances.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#5258 [Test] [Costing] Add 'test_flattenCostRoseHandlesBottom'
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Costing.hs
Labels: Test, Costs, No Changelog Required

#5208 [Builtins] Optimize 'ToBinds'
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
Labels: Refactoring, Builtins, No Changelog Required

#5260 [Costing] 'newtype' 'intercept' and 'slope'
  plutus-core/changelog.d/20230418_193516_effectfully_newtype_intercept_and_slope.md
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
Labels: Costs

#5263 Add a note about global uniqueness in the inliner
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Inline.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Utils.hs
Labels: No Changelog Required

#5268 Address some comments on SOPs
  plutus-conformance/agda/Spec.hs
  plutus-conformance/test-cases/uplc/evaluation/term/case/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/case/case-8/case-8.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/case/case-8/case-8.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constr/constr-5/constr-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constr/constr-5/constr-5.uplc.expected
  plutus-core/plutus-core/src/PlutusCore/Check/Normal.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/test/Generators.hs
Labels: No Changelog Required

#5271 Small fixes after my review of SOP
  plutus-conformance/agda/Spec.hs
  plutus-conformance/test-cases/uplc/evaluation/term/case/case-9/case-9.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/case/case-9/case-9.uplc.expected
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNonTag.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNonTag.uplc.golden
Labels: No Changelog Required

#5272 A small code refactor to use foldrM
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Let.hs
Labels: No Changelog Required
