Repository IntersectMBO/plutus, pull requests merged in 2024-06, with the labels that each got.

#6162 Tests for the `preserve-logging` flag.
  plutus-core/plutus-ir/src/PlutusIR/Transform/EvaluateBuiltins.hs
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithPreservedLogging.hs
Labels: No Changelog Required

#6161 Quadratic costing for integer division functions
  plutus-benchmark/marlowe/test/semantics/9.6/004025fd712d6c325ffa12c16d157064192992faf62e0b991d7310a2f91666b8.budget.golden
  plutus-benchmark/marlowe/test/semantics/9.6/04000f0b04051006000e060f09080d0b090d0104050a0b0f0506070f0a070008.budget.golden
  plutus-benchmark/marlowe/test/semantics/9.6/119fbea4164e2bf21d2b53aa6c2c4e79414fe55e4096f5ce2e804735a7fbaf91.budget.golden
  plutus-benchmark/marlowe/test/semantics/9.6/1d56060c3b271226064c672a282663643b1b0823471c67737f0b076870331260.budget.golden
  plutus-benchmark/marlowe/test/semantics/9.6/70f65b21b77ddb451f3df9d9fb403ced3d10e1e953867cc4900cc25e5b9dec47.budget.golden
  plutus-benchmark/marlowe/test/semantics/9.6/7a758e17486d1a30462c32a5d5309bd1e98322a9dcbe277c143ed3aede9d265f.budget.golden
  plutus-benchmark/marlowe/test/semantics/9.6/a9a853b6d083551f4ed2995551af287880ef42aee239a2d9bc5314d127cce592.budget.golden
  plutus-benchmark/nofib/test/9.6/knights10-4x4.budget.golden
  plutus-benchmark/script-contexts/test/9.6/checkScriptContext1-20.budget.golden
  plutus-benchmark/script-contexts/test/9.6/checkScriptContext1-4.budget.golden
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/divideInteger/divideInteger-neg-neg/divideInteger-neg-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/divideInteger/divideInteger-neg-pos/divideInteger-neg-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/divideInteger/divideInteger-pos-neg/divideInteger-pos-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/divideInteger/divideInteger-pos-pos/divideInteger-pos-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/divideInteger/divideInteger1/divideInteger1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/modInteger/modInteger-neg-neg/modInteger-neg-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/modInteger/modInteger-neg-pos/modInteger-neg-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/modInteger/modInteger-pos-neg/modInteger-pos-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/modInteger/modInteger-pos-pos/modInteger-pos-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/modInteger/modInteger1/modInteger1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/quotientInteger/quotientInteger-neg-neg/quotientInteger-neg-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/quotientInteger/quotientInteger-neg-pos/quotientInteger-neg-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/quotientInteger/quotientInteger-pos-neg/quotientInteger-pos-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/quotientInteger/quotientInteger-pos-pos/quotientInteger-pos-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/quotientInteger/quotientInteger1/quotientInteger1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/remainderInteger/remainderInteger-neg-neg/remainderInteger-neg-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/remainderInteger/remainderInteger-neg-pos/remainderInteger-neg-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/remainderInteger/remainderInteger-pos-neg/remainderInteger-pos-neg.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/remainderInteger/remainderInteger-pos-pos/remainderInteger-pos-pos.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/remainderInteger/remainderInteger1/remainderInteger1.uplc.budget.expected
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/print-cost-model/Main.hs
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/DataFilePaths.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
  plutus-core/plutus-core/test/CostModelInterface/Spec.hs
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/test/Spec.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/test/Spec/Eval.hs
  plutus-metatheory/src/Cost/Model.lagda.md
  plutus-metatheory/src/Cost/Raw.lagda.md
  plutus-tx-plugin/test/Budget/9.6/filter.budget.golden
  plutus-tx-plugin/test/Budget/9.6/map1-budget.budget.golden
  plutus-tx-plugin/test/Budget/9.6/show.budget.golden
  plutus-tx-plugin/test/Plugin/Basic/9.6/ifOptEval.eval.golden
Labels: Builtins, Costing, No Changelog Required

#6166 Fix V2's costModelParamsForTesting
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-ledger-api/test/Spec.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V2/EvaluationContext.hs
Labels: No Changelog Required

#6170 Release 1.29.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240517_094957_unsafeFixIO_v2_new_prims.md
  plutus-core/changelog.d/20240517_191403_effectfully_polish_evaluation_errors.md
  plutus-core/changelog.d/20240520_192738_effectfully_remove_UnknownBuiltin.md
  plutus-core/changelog.d/20240522_211822_kenneth.mackenzie_provisional_conway_cost_model.md
  plutus-core/changelog.d/20240529_153319_effectfully_polish_handling_of_integral_types.md
  plutus-core/changelog.d/20240530_123928_kenneth.mackenzie_reduce_cek_cpu_step_costs_B.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20240429_121642_unsafeFixIO_69.md
  plutus-ledger-api/changelog.d/20240522_212027_kenneth.mackenzie_provisional_conway_cost_model.md
  plutus-ledger-api/changelog.d/20240530_113312_unsafeFixIO_unit.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20240513_014001_effectfully_split_FromBuiltin_and_ToBuiltin_into_IsBuiltin_and_IsOpaque.md
  plutus-tx/changelog.d/20240516_215552_ana.pantilie95_data_assoclist.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required, Release

#6176 Possible Fix for Ramsay View problem
  plutus-metatheory/src/VerifiedCompilation/UntypedViews.lagda.md
Labels: No Changelog Required

#6174 Update update-version.sh to match package names less greedily
  scripts/update-version.sh
Labels: bug, No Changelog Required

#6179 More error checking for update-vesion.sh
  scripts/update-version.sh
Labels: No Changelog Required

#6182 Initial version of new combined-haddock.yml workflow
  .github/workflows/combined-haddock.yml
Labels: No Changelog Required

#5885 [Builtins] Make 'BuiltinSuccess' the first constructor
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Evaluation, Builtins, Performance, No Changelog Required

#6178 [PlutusLedgerApi] [Refactoring] Polish imports and exports
  plutus-ledger-api/changelog.d/20240606_160839_effectfully_polish_imports_and_exports.md
  plutus-ledger-api/exe/analyse-script-events/Main.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/Scripts.hs
  plutus-tx/src/PlutusTx/IsData/Class.hs
Labels: Refactoring, Plutus Ledger API

#6187 Adding link to Haddock documentation to index.md
  docusaurus/docs/index.md
Labels: No Changelog Required

#6188 removing outdated and incorrect content from the Plutus platform page
  docusaurus/docs/essential-concepts/plutus-platform.mdx
Labels: No Changelog Required

#6190 added the term Haddock where the public Plutus code libraries are men…
  docusaurus/docs/index.md
Labels: No Changelog Required

#6146 Combined Haddock Generation
  .github/workflows/combined-haddock.yml
  .gitignore
  flake.lock
  flake.nix
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/MergeSort.hs
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6195 Run nightly tests on plutus-shared instead of plutus-benchmark
  .github/workflows/nightly.yml
Labels: No Changelog Required

#6196 Run combined-haddock.yml workflow on plutus-shared instead of plutus-runner
  .github/workflows/combined-haddock.yml
Labels: No Changelog Required

#6199 Fix combined_haddock.sh script
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6189 [Test] [Builtins] Add golden tests with unlifting errors
  plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/List/headList-empty.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/List/tailList-empty.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/consByteString-out-of-range.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/indexByteString-out-of-bounds-empty.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/indexByteString-out-of-bounds-non-empty.err.golden
Labels: Test, Builtins, No Changelog Required

#6200 Changed the term "Documentation" to "User guide" in the upper left area of the docs site
  docusaurus/.gitignore
  docusaurus/docusaurus.config.ts
  docusaurus/src/css/custom.css
  docusaurus/src/theme/Footer/index.js
  docusaurus/static/img/github.svg
  docusaurus/static/img/logo-footer.svg
Labels: No Changelog Required

#6201 Update Alert Message in longitudinal-benchmark.yml
  .github/workflows/longitudinal-benchmark.yml
Labels: No Changelog Required

#6204 [Test] Add missing bitwise builtins golden files
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/AndByteString.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/ComplementByteString.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/OrByteString.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/ReadBit.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/ReplicateByteString.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/WriteBits.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/XorByteString.plc.golden
Labels: Test

#6181 [Errors] Preserve operational unlifting errors
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/consByteString-out-of-range.err.golden
Labels: Evaluation, Errors

#6203 Docs raise visibility code libraries
  docusaurus/docs/index.md
  docusaurus/docs/reference/_category_.json
  docusaurus/docs/reference/haddock-documentation.md
Labels: No Changelog Required

#6202 [Test] [Builtin] Polish 'MakeRead' tests
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
Labels: Test, Refactoring

#6208 Remove PyF as it depends on GHC and causes depenecy conflicts downstream
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
Labels: No Changelog Required

#6209 Reduce coverage limits for signature verification tests
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SignatureVerification.hs
Labels: Test, Builtins, No Changelog Required

#6211 Moved the Getting Started page for higher visibility
  docusaurus/docs/getting-started-plutus-tx.md
Labels: No Changelog Required

#6156 [Evaluation] Move stuff under `enterComputeCek`
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
Labels: Evaluation, Refactoring, No Changelog Required

#6218 plutus-ir: fix redundant imports
  plutus-core/plutus-ir/src/PlutusIR/Pass.hs
Labels: No Changelog Required

#6217 Fix incorrect Note reference
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
Labels: No Changelog Required

#6220 Add documentation to `Data.Value`
  plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Value.hs
Labels: No Changelog Required

#5926 [Builtins] Replace 'EvaluationResult' with 'BuiltinResult'
  plutus-core/changelog.d/20240618_023306_effectfully_replace_EvaluationResult_with_BuiltinResult.md
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Crypto/Utils.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Interesting.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/List/headList-empty.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/List/tailList-empty.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/indexByteString-out-of-bounds-empty.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/String/indexByteString-out-of-bounds-non-empty.err.golden
  plutus-tx-plugin/test/Plugin/Basic/9.6/ifOptEval.eval.golden
Labels: Builtins, Errors, User experience

#6223 Add workflow for publishing Agda Metatheory site
  .github/workflows/plublish-metatheory-site.yml
  nix/plutus-metatheory-site.nix
  plutus-metatheory/src/Type/RenamingSubstitution.lagda.md
  plutus-metatheory/src/index.lagda.md
Labels: No Changelog Required

#6230 Update RELEASE.adoc with instructions to delete unused branches and tags
  RELEASE.adoc
Labels: No Changelog Required

#6232 Fix broken links in docusaurus docs
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/metatheory-site.yml
  README.adoc
  doc/docusaurus/docs/index.md
  doc/docusaurus/docs/reference/haddock-documentation.md
Labels: No Changelog Required

#6233 Add flake.nix for doc/docusaurus
  doc/docusaurus/README.md
  doc/docusaurus/docs/reference/haddock-documentation.md
  doc/docusaurus/flake.lock
  doc/docusaurus/flake.nix
  doc/docusaurus/yarn.lock
  nix/shell.nix
Labels: No Changelog Required

#6235 making a spelling correction on the doc/docusaurus README file
  doc/docusaurus/README.md
Labels: No Changelog Required

#6224 [Builtins] Remove 'Emitter' and 'MonadEmitter'
  plutus-core/changelog.d/20240620_025344_effectfully_remove_Emitter_and_MonadEmitter.md
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Builtin.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Emitter.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Crypto/Utils.hs
Labels: Refactoring, Builtins

#6124 Refactor GitHub Workflows
  .github/workflows/changelog-label.yml
  .github/workflows/cost-model-bench.yml
  .github/workflows/cost-model-benchmark.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/longitudinal-benchmark.yml
  .github/workflows/manual-benchmark.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/nightly-testsuite.yml
  .github/workflows/plutus-tx-template.yml
  .github/workflows/script-evaluation-test.yml
  .github/workflows/slack-message-broker.yml
  .github/workflows/triage-label.yml
Labels: No Changelog Required

#6231 Fix & simplify SOP encoding example comment
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
Labels: Documentation, No Changelog Required

#6079 Make it build with ghc 9.10
  cabal.project
  flake.lock
  plutus-benchmark/plutus-benchmark.cabal
  plutus-core/cost-model/budgeting-bench/Generators.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Name/UniqueMap.hs
  plutus-core/plutus-core/src/PlutusCore/Name/UniqueSet.hs
  plutus-core/plutus-core/src/Universe/Core.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Definitions.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Names.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RecSplit.hs
  plutus-core/prelude/PlutusPrelude.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Simplify.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Cse.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/ForceDelay.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/BLS12_381.hs
  plutus-core/untyped-plutus-core/test/Transform/Simplify.hs
  plutus-tx-plugin/test/AsData/Budget/9.6/patternMatching.uplc.golden
  plutus-tx-plugin/test/Budget/9.6/map2.uplc.golden
  plutus-tx-plugin/test/Budget/9.6/map3.uplc.golden
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
  plutus-tx/src/PlutusTx/IsData/TH.hs
Labels: No Changelog Required

#6236 Add workflows to check broken links and deploy papers to GH Pages
  .github/workflows/broken-links.yml
  .github/workflows/cost-model-benchmark.yml
  .github/workflows/papers-and-specs.yml
  README.adoc
  doc/docusaurus/docs/essential-concepts/plutus-foundation.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
  doc/plutus-core-spec/README.md
  plutus-core/docs/BuiltinsOverview.md
  plutus-metatheory/src/Type/RenamingSubstitution.lagda.md
  scripts/check-broken-links.sh
Labels: No Changelog Required

#6239 Cabal project to compile docusaurus examples.
  cabal.project
  doc/docusaurus/LICENSE
  doc/docusaurus/docs/using-plutus-tx/producing-a-blueprint.md
  doc/docusaurus/docusaurus-examples.cabal
  doc/docusaurus/plutus.json
  doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
  nix/project.nix
Labels: status: triaged, No Changelog Required, Internal

#6234 Added cardano-constitution package
  cabal.project
  cardano-constitution/.gitignore
  cardano-constitution/LICENSE
  cardano-constitution/NOTICE
  cardano-constitution/README.md
  cardano-constitution/cardano-constitution.cabal
  cardano-constitution/certification/documentation-traceability.md
  cardano-constitution/certification/testing-traceability.md
  cardano-constitution/data/defaultConstitution.json
  cardano-constitution/data/defaultConstitution.schema.json
  cardano-constitution/src/Cardano/Constitution/Config.hs
  cardano-constitution/src/Cardano/Constitution/Config/Instance/FromJSON.hs
  cardano-constitution/src/Cardano/Constitution/Config/Instance/TxLift.hs
  cardano-constitution/src/Cardano/Constitution/Config/Types.hs
  cardano-constitution/src/Cardano/Constitution/DataFilePaths.hs
  cardano-constitution/src/Cardano/Constitution/Validator.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Common.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Sorted.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Unsorted.hs
  cardano-constitution/src/PlutusTx/NonCanonicalRational.hs
  cardano-constitution/test/Cardano/Constitution/Config/Tests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/PropTests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/TestsCommon.hs
  cardano-constitution/test/Cardano/Constitution/Validator/UnitTests.hs
  cardano-constitution/test/Driver.hs
  cardano-constitution/test/Helpers/CekTests.hs
  cardano-constitution/test/Helpers/Farey.hs
  cardano-constitution/test/Helpers/Guardrail.hs
  cardano-constitution/test/Helpers/Intervals.hs
  cardano-constitution/test/Helpers/MultiParam.hs
  cardano-constitution/test/Helpers/Spec/FareySpec.hs
  cardano-constitution/test/Helpers/Spec/IntervalSpec.hs
  cardano-constitution/test/Helpers/TestBuilders.hs
  cardano-constitution/test/PlutusLedgerApi/V3/ArbitraryContexts.hs
  nix/project.nix
Labels: No Changelog Required

#6249 [Test] Turn off CSE for problematic tests
  plutus-tx-plugin/test/AssocMap/Spec.hs
  plutus-tx-plugin/test/Budget/9.6/map1-budget.budget.golden
  plutus-tx-plugin/test/Budget/9.6/map1.uplc.golden
  plutus-tx-plugin/test/Budget/9.6/map2-budget.budget.golden
  plutus-tx-plugin/test/Budget/9.6/map2.uplc.golden
  plutus-tx-plugin/test/Budget/9.6/map3-budget.budget.golden
  plutus-tx-plugin/test/Budget/9.6/map3.uplc.golden
Labels: Test, No Changelog Required, Plutus Tx Plugin, optimization

#6247 Spec that verifies various script sizes, also demostrates a lazy script context un-marshalling
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-ledger-api/test-plugin/Spec.hs
  plutus-ledger-api/test-plugin/Spec/ScriptSize.hs
Labels: No Changelog Required

#6253 Add cardano-constitution-tests and slack-message-broker workflows
  .github/workflows/cardano-constitution-tests.yml
  .github/workflows/slake-message-broker.yml
Labels: No Changelog Required

#6258 Updates to slack-message-broker.yml
  .github/workflows/slake-message-broker.yml
Labels: No Changelog Required

#6165 Fix "un-rolling" a list type.
  plutus-tx/src/PlutusTx/Blueprint/Definition/Unroll.hs
  plutus-tx/test/Blueprint/Spec.hs
Labels: No Changelog Required

#6267 constitution: Add executable that creates json envelope
  cardano-constitution/cardano-constitution.cabal
  cardano-constitution/create-json-envelope/Main.hs
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/UnitTests.hs
Labels: No Changelog Required
