Repository IntersectMBO/plutus, pull requests merged in 2024-11, with the labels that each got.

#6623 Improve specification of the Secp256k1 signature verification functions
  doc/plutus-core-spec/cardano/builtins3.tex
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: Specification, No Changelog Required

#6622 Extra conformance tests for `verifyEcdsaSecp256k1Signature`
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/README.md
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-01/test-vector-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-01/test-vector-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-01/test-vector-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-02/test-vector-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-02/test-vector-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-02/test-vector-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-03/test-vector-03.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-03/test-vector-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-03/test-vector-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-04/test-vector-04.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-04/test-vector-04.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-04/test-vector-04.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-05/test-vector-05.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-05/test-vector-05.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-05/test-vector-05.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-06/test-vector-06.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-06/test-vector-06.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-06/test-vector-06.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-07/test-vector-07.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-07/test-vector-07.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-07/test-vector-07.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-08/test-vector-08.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-08/test-vector-08.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-08/test-vector-08.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-09/test-vector-09.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-09/test-vector-09.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-09/test-vector-09.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-10/test-vector-10.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-10/test-vector-10.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-10/test-vector-10.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-11/test-vector-11.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-11/test-vector-11.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-11/test-vector-11.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-12/test-vector-12.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-12/test-vector-12.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-12/test-vector-12.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-13/test-vector-13.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-13/test-vector-13.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-13/test-vector-13.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-14/test-vector-14.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-14/test-vector-14.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-14/test-vector-14.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-15/test-vector-15.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-15/test-vector-15.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-15/test-vector-15.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-16/test-vector-16.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-16/test-vector-16.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-16/test-vector-16.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-17/test-vector-17.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-17/test-vector-17.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-17/test-vector-17.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-18/test-vector-18.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-18/test-vector-18.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/test-vector-18/test-vector-18.uplc.expected
Labels: Test, Builtins, Crypto, status: triaged, No Changelog Required, Internal

#6628 Amends to slack-message-broker
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#6629 Fix all dependabot alerts in doc/docusaurus/yarn.lock
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#6632 New amends to slack-message-broker
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#6635 Fix incorrect `fromDistinctAscList` in PlutusTx.ErrorCodes
  plutus-tx/src/PlutusTx/ErrorCodes.hs
Labels: No Changelog Required

#6619 [Test] Mark more 'Integer's as interesting
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Labels: Test, No Changelog Required

#6562 Use Agda Haskell lib instead of MAlonzo
  nix/agda-packages.nix
  nix/agda-project.nix
  nix/agda-with-stdlib.nix
  nix/agda.nix
  nix/build-latex-doc.nix
  nix/outputs.nix
  nix/plutus-metatheory-site.nix
  nix/project.nix
  nix/shell.nix
  nix/unraveling-recursion-paper.nix
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/plutus-executables.cabal
  plutus-executables/src/AgdaUnparse.hs
  plutus-metatheory/src/Certifier.agda
  plutus-metatheory/src/VerifiedCompilation.lagda.md
Labels: No Changelog Required

#6639 Enable Haddock for Agda
  nix/agda.nix
Labels: No Changelog Required

#6640 Remove extra-doc-files:README.md from plutus-executables.cabal
  plutus-executables/plutus-executables.cabal
Labels: No Changelog Required

#6641 Add github/workflows/cabal-build-all.yml
  .github/workflows/cabal-build-all.yml
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#6621 Embracing the Product Mindset
  doc/product-mindset.md
Labels: No Changelog Required

#6645 Upgrade iogx and fourmolu
  flake.lock
  nix/shell.nix
Labels: No Changelog Required

#6646 Use taskset in ci-plutu-benchmark.sh
  nix/shell.nix
  scripts/ci-plutus-benchmark.sh
Labels: Benchmarks, No Changelog Required

#6649 Swap cases for availability of taskset
  scripts/ci-plutus-benchmark.sh
Labels: Benchmarks, No Changelog Required

#6647 Remove doctest across whole repo
  cabal.project
  doc/docusaurus/static/code/BasicPlutusTx.hs
  nix/project.nix
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-tx/plutus-tx.cabal
  plutus-tx/src/PlutusTx/Prelude.hs
  prettyprinter-configurable/src/Text/PrettyBy/Internal.hs
Labels: No Changelog Required

#6642 Run cabal-build-all.yml on plutus-ci
  .github/workflows/cabal-build-all.yml
Labels: No Changelog Required

#6658 Add option to pass the CAPABILITY_NUM to manual-benchmarl.yml workflow
  .github/workflows/manual-benchmark.yml
Labels: No Changelog Required

#6659 Rename some conformance tests correctly
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/bls12_381_G1_scalarMul/mul-neg-one/mul-neg-one.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/bls12_381_G1_scalarMul/mul-neg-one/mul-neg-one.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/bls12_381_G1_scalarMul/mul-neg-one/mul-neg-one.uplc.expected
Labels: Test, Builtins, No Changelog Required

#6665 Avoid division by zero in benchmark comparisons
  plutus-benchmark/bench-compare-markdown
Labels: Benchmarks, No Changelog Required

#6666 add explicit type application on bls operations for G1/G2
  plutus-core/plutus-core/src/PlutusCore/Crypto/BLS12_381/G1.hs
  plutus-core/plutus-core/src/PlutusCore/Crypto/BLS12_381/G2.hs
Labels: Builtins, Crypto, No Changelog Required

#6673 Upgrade to newer Agda and agda-stdlib
  doc/papers/system-f-in-agda/paper.lagda
  nix/agda.nix
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/plutus-executables.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Algorithmic/Erasure.lagda.md
  plutus-metatheory/src/Cost.lagda.md
  plutus-metatheory/src/Main.lagda.md
  plutus-metatheory/src/Utils/List.lagda.md
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/Equality.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCSE.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseReduce.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UFloatDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UForceDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UntypedTranslation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UntypedViews.lagda.md
Labels: No Changelog Required

#6681 Add papi support to the nix shell
  nix/shell.nix
Labels: No Changelog Required

#6669 UPLC Inline certifier translation relation and decision procedure.
  plutus-metatheory/src/VerifiedCompilation/UInline.lagda.md
Labels: No Changelog Required, Internal

#6672 Refactor: reduce code duplication and make more uniform how plugin looks up GHC things (Names, Ids, etc.)
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Utils.hs
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
Labels: No Changelog Required

#6676 Expose `index-envs` library to public
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#6695 [Test] Disable 'prop_shrinkTermSound'
  plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
Labels: bug, Test, Plutus IR, No Changelog Required, Generators

#6663 [Evaluation] [Performance] Tweak 'safeIndexOne'
  plutus-core/changelog.d/20241119_201414_effectfully_tweak_safeIndexOne.md
  plutus-core/index-envs/src/Data/RandomAccessList/SkewBinary.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: Evaluation, Performance

#6704 Fix build ambiguous use of `show` with `text-2.1.2`
  plutus-core/executables/plutus/AnyProgram/Run.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
Labels: No Changelog Required

#6699 [Build] Drop 'prettyprinter-configurable'
  .github/workflows/plutus-tx-template.yml
  CONTRIBUTING.adoc
  RELEASE.adoc
  cabal.project
  cardano-constitution/README.md
  nix/project.nix
  plutus-core/plutus-core.cabal
  prettyprinter-configurable/LICENSE
  prettyprinter-configurable/NOTICE
  prettyprinter-configurable/README.md
  prettyprinter-configurable/changelog.d/scriv.ini
  prettyprinter-configurable/prettyprinter-configurable.cabal
  prettyprinter-configurable/src/Text/Fixity.hs
  prettyprinter-configurable/src/Text/Fixity/Internal.hs
  prettyprinter-configurable/src/Text/Pretty.hs
  prettyprinter-configurable/src/Text/PrettyBy.hs
  prettyprinter-configurable/src/Text/PrettyBy/Default.hs
  prettyprinter-configurable/src/Text/PrettyBy/Fixity.hs
  prettyprinter-configurable/src/Text/PrettyBy/Internal.hs
  prettyprinter-configurable/src/Text/PrettyBy/Internal/Utils.hs
  prettyprinter-configurable/src/Text/PrettyBy/Monad.hs
  prettyprinter-configurable/test/Default.hs
  prettyprinter-configurable/test/Expr.hs
  prettyprinter-configurable/test/Main.hs
  prettyprinter-configurable/test/NonDefault.hs
  prettyprinter-configurable/test/Universal.hs
  scripts/prepare-release.sh
Labels: Build, No Changelog Required

#6705 [Evaluation] [Performance] Strictify 'spend'
  plutus-core/changelog.d/20241126_024818_effectfully_strictify_spend.md
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
Labels: Evaluation, Performance

#6708 1.37.0.0 release
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20241001_232646_effectfully_add_pattern_matching_builtins.md
  plutus-core/changelog.d/20241119_201414_effectfully_tweak_safeIndexOne.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20241031_172446_Yuriy.Lazaryev_mint_value.md
  plutus-ledger-api/changelog.d/20241031_214048_ana.pantilie95_data_backed_list.md
  plutus-ledger-api/changelog.d/20241107_164059_Yuriy.Lazaryev_with_currency_symbol.md
  plutus-ledger-api/changelog.d/20241111_125402_Yuriy.Lazaryev_plutus_ledger_api_v1.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20241113_120551_Yuriy.Lazaryev_builtin_byte_string_literals.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20241031_213929_ana.pantilie95_data_backed_list.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required
