Repository IntersectMBO/plutus, pull requests merged in 2024-09, with the labels that each got.

#6435 Fix documentation typo
  plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
Labels: No Changelog Required

#6439 [Errors] Swap operational and structural errors
  plutus-core/changelog.d/20240903_180833_effectfully_swap_structural_and_operational_errors.md
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/plutus-core/test/Evaluation/Machines.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
Labels: Evaluation, Refactoring, Errors

#6444 Add a note in the Haddock of currencySymbolValueOf
  plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
Labels: No Changelog Required

#6447 Add packages to CHaP release docs
  RELEASE.adoc
Labels: No Changelog Required

#6449 Enable Chang+1 builtins at Chang+1 and add them to V3.ParamName
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/test/Spec/Data/CostModelParams.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Labels: No Changelog Required

#6452 Release 1.34.0.0
  cabal.project
  cardano-constitution/README.md
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240903_180833_effectfully_swap_structural_and_operational_errors.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20240708_134138_Yuriy.Lazaryev_has_schema_instances.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20240906_143413_unsafeFixIO_evaluate_builtins.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20240708_134238_Yuriy.Lazaryev_has_schema_instances.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#6458 Update RELEASE.adoc
  RELEASE.adoc
Labels: No Changelog Required

#6451 Revise and improve the troubleshooting guide
  doc/docusaurus/docs/troubleshooting.md
Labels: No Changelog Required

#6456 Put the TOTAL line for a benchmark comparison in a table of its own
  scripts/ci-plutus-benchmark.sh
Labels: Do not merge, EXPERIMENT, No Changelog Required

#6461 Fix regression, ensure it doesn't come back with a property test
  plutus-conformance/agda/Spec.hs
  plutus-conformance/haskell-steppable/Spec.hs
  plutus-conformance/haskell/Spec.hs
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Labels: Builtins, No Changelog Required

#6463 Fix printing of type variables in print-builtin-signatures
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
Labels: Plutus Exe, No Changelog Required

#6466 Fix Sprint Issues Rollover Workflow
  .github/workflows/sprint-issues-rollover.yml
Labels: No Changelog Required

#6465 Test
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Labels: Do not merge, EXPERIMENT, No Changelog Required

#6470 Kwxm/ci/visible total
  scripts/ci-plutus-benchmark.sh
Labels: No Changelog Required

#6472 Try yet again
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  scripts/ci-plutus-benchmark.sh
Labels: Benchmarks, No Changelog Required

#6467 [spec] update conway info
  doc/plutus-core-spec/cardano/versions.tex
Labels: No Changelog Required

#6475 Address Dependabot Alerts for Docusaurus
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#6474 Fix typo
  plutus-ledger-api/plutus-ledger-api.cabal
Labels: No Changelog Required

#6476 Blueprints: calculate script hash the right way.
  doc/docusaurus/docs/using-plutus-tx/producing-a-blueprint.md
  doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/test/Blueprint/Acme.golden.json
  plutus-tx-plugin/test/Blueprint/Tests.hs
  plutus-tx-plugin/test/Blueprint/Tests/CompiledValidator.hex
  plutus-tx-plugin/test/Spec.hs
  plutus-tx/src/PlutusTx/Blueprint/Validator.hs
Labels: No Changelog Required

#6460 Add a few more common mistakes to the troubleshooting guide
  doc/docusaurus/docs/troubleshooting.md
Labels: No Changelog Required

#6446 Align with the OSC Documentation Policy
  CHANGELOG.md
  CODEOWNERS.md
  CODE_OF_CONDUCT.md
  DESCRIPTION.md
  LICENSE
  LICENSE.md
  NOTICE
  NOTICE.md
  SECURITY.md
Labels: No Changelog Required

#6464 Updated blueprints documentation page.
  doc/docusaurus/docs/using-plutus-tx/producing-a-blueprint.md
  doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
  doc/docusaurus/static/plutus.json
Labels: Documentation, No Changelog Required, Blueprint

#6479 Address review comments on "Overview of Languages Compiling to UPLC"
  doc/docusaurus/docs/delve-deeper/languages.md
Labels: No Changelog Required

#6483 [Test] Remove uniques from 'Profiling' tests
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/test/Plugin/Profiling/9.6/addInt.pir.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/addInt3.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/argMismatch1.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/argMismatch2.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/fact4.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/fib.pir.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/fib4.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/id.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/idCode.pir.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/letInFun.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/letInFunMoreArg.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/letRecInFun.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/swap.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/typeclass.eval.golden
Labels: Test, No Changelog Required

#6484 [Test] Check in a forgotten golden file
  plutus-core/plutus-core/test/TypeSynthesis/Golden/ExtensionFun/IntNoIntegerNoWord.plc.golden
Labels: Test, No Changelog Required

#6485 Release 1.34.1.0
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240904_214017_ana.pantilie95_add_certification_component.md
  plutus-core/changelog.d/20240913_101059_kenneth.mackenzie.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required, Release

#6487 Remove delve-deeper/examples.md
  doc/docusaurus/docs/delve-deeper/examples.md
Labels: No Changelog Required

#6486 Remove "Exporting scripts, datums and redeemers" from user guide
  doc/docusaurus/docs/delve-deeper/upgrade-vasil-plutus-script-addresses.md
  doc/docusaurus/docs/working-with-scripts/exporting-scripts-datums-redeemers.md
  doc/docusaurus/docs/working-with-scripts/producing-a-blueprint.md
Labels: No Changelog Required

#6489 Update plutus-tx-template.yml
  .github/workflows/plutus-tx-template.yml
Labels: No Changelog Required

#6488 Rename and improve the Plutus foundation page
  doc/docusaurus/docs/essential-concepts/plutus-core-and-plutus-tx.md
  doc/docusaurus/docs/essential-concepts/plutus-foundation.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
Labels: No Changelog Required

#6493 Promote and improve the glossary page
  doc/docusaurus/docs/delve-deeper/glossary.md
  doc/docusaurus/docs/essential-concepts/ledger.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
  doc/docusaurus/docs/glossary.md
Labels: No Changelog Required

#6496 Separate Docusaurus Build & Deploy Workflow Steps
  .github/workflows/docusaurus-site.yml
Labels: No Changelog Required

#6495 Remove use of `--pure` in `scripts/prepare-bins.sh`
  nix/shell.nix
  scripts/prepare-bins.sh
Labels: No Changelog Required

#6501 Use NOINLINE on stringToBuiltinByteString and stringToBuiltinString
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx/plutus-tx.cabal
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
Labels: No Changelog Required

#6443 [Errors] Test that evaluation of a well-typed term doesn't fail with a structural error
  plutus-benchmark/nofib/exe/Main.hs
  plutus-core/executables/plutus/AnyProgram/Compile.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/Tests/Lib.hs
  plutus-core/prelude/PlutusPrelude.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/CommonAPI.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/MakeRead.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/Test.hs
  plutus-tx-test-util/testlib/PlutusTx/Test/Util/Compiled.hs
Labels: Test, Evaluation, Errors, No Changelog Required

#6509 [Refactoring] Tweak 'PlutusTx.Data.AssocMap'
  plutus-tx/src/PlutusTx/Data/AssocMap.hs
Labels: Plinth, Refactoring, No Changelog Required

#6507 [Refactoring] Replace 'NOINLINE' with 'OPAQUE'
  doc/adr/adr3.md
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-metatheory/Setup.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Plugin/Data/Spec.hs
  plutus-tx-plugin/test/Plugin/Laziness/Spec.hs
  plutus-tx-plugin/test/Plugin/Typeclasses/Spec.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Plugin/Utils.hs
Labels: Refactoring, No Changelog Required

#6514 Remove plutus-ghc-stub
  .gitattributes
  cabal.project
  plutus-tx-plugin/plutus-tx-plugin.cabal
  stubs/plutus-ghc-stub/LICENSE
  stubs/plutus-ghc-stub/NOTICE
  stubs/plutus-ghc-stub/README.md
  stubs/plutus-ghc-stub/plutus-ghc-stub.cabal
  stubs/plutus-ghc-stub/src/Class.hs
  stubs/plutus-ghc-stub/src/CoreSyn.hs
  stubs/plutus-ghc-stub/src/FV.hs
  stubs/plutus-ghc-stub/src/FamInstEnv.hs
  stubs/plutus-ghc-stub/src/Finder.hs
  stubs/plutus-ghc-stub/src/GhcPlugins.hs
  stubs/plutus-ghc-stub/src/Kind.hs
  stubs/plutus-ghc-stub/src/LoadIface.hs
  stubs/plutus-ghc-stub/src/MkId.hs
  stubs/plutus-ghc-stub/src/OccName.hs
  stubs/plutus-ghc-stub/src/Panic.hs
  stubs/plutus-ghc-stub/src/Plugins.hs
  stubs/plutus-ghc-stub/src/PrelNames.hs
  stubs/plutus-ghc-stub/src/PrimOp.hs
  stubs/plutus-ghc-stub/src/StubTypes.hs
  stubs/plutus-ghc-stub/src/TcRnMonad.hs
  stubs/plutus-ghc-stub/src/TcRnTypes.hs
  stubs/plutus-ghc-stub/src/TysPrim.hs
Labels: No Changelog Required

#6506 Remove the Plutus Platform page
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
Labels: No Changelog Required

#6477 Make the auction example end-to-end
  doc/docusaurus/docs/auction-smart-contract/_category_.json
  doc/docusaurus/docs/auction-smart-contract/end-to-end/_category_.json
  doc/docusaurus/docs/auction-smart-contract/end-to-end/closing-the-auction.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/generating-keys.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/getting-funds.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/mint.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/placing-bids.md
  doc/docusaurus/docs/auction-smart-contract/life-cycle.md
  doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
  doc/docusaurus/docs/essential-concepts/plutus-core-and-plutus-tx.md
  doc/docusaurus/docs/essential-concepts/versions.md
  doc/docusaurus/docs/glossary.md
  doc/docusaurus/docs/simple-example/_category_.json
  doc/docusaurus/docs/simple-example/alternatives-to-plutus-tx.md
  doc/docusaurus/docs/simple-example/auction-properties.md
  doc/docusaurus/docs/simple-example/eutxo-model.md
  doc/docusaurus/docs/simple-example/further-reading.md
  doc/docusaurus/docs/simple-example/libraries.md
  doc/docusaurus/docs/simple-example/off-chain-code.md
  doc/docusaurus/docs/simple-example/plutus-tx-code.md
  doc/docusaurus/docs/simple-example/simple-example.md
  doc/docusaurus/docs/using-plutus-tx/advanced-plutus-tx-concepts/optimizing-scripts-with-asData.md
  doc/docusaurus/static/code/AuctionMintingPolicy.hs
  doc/docusaurus/static/code/AuctionValidator.hs
  doc/docusaurus/static/code/bid.mjs
  doc/docusaurus/static/code/generate-keys.mjs
  doc/docusaurus/static/code/mint-token-for-auction.mjs
  doc/docusaurus/static/code/send-lovelace.mjs
Labels: No Changelog Required

#6482 Translation relation and decision procedure for the Float-Delay
  plutus-metatheory/src/VerifiedCompilation/Purity.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UFloatDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UForceDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UntypedTranslation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UntypedViews.lagda.md
Labels: No Changelog Required

#6513 This seems 'too easy' but to certify things I don't think it needs to be more complex?
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCSE.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UForceDelay.lagda.md
Labels: No Changelog Required, Internal

#6516 Rework the "Using Plutus Tx" section of the user guide
  doc/docusaurus/docs/auction-smart-contract/end-to-end/mint.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/placing-bids.md
  doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
  doc/docusaurus/docs/delve-deeper/languages.md
  doc/docusaurus/docs/essential-concepts/versions.md
  doc/docusaurus/docs/getting-started-plutus-tx.md
  doc/docusaurus/docs/glossary.md
  doc/docusaurus/docs/index.md
  doc/docusaurus/docs/troubleshooting.md
  doc/docusaurus/docs/using-plutus-tx/_category_.json
  doc/docusaurus/docs/using-plutus-tx/advanced-plutus-tx-concepts/_category_.json
  doc/docusaurus/docs/using-plutus-tx/advanced-plutus-tx-concepts/triggering-a-validation-failure.md
  doc/docusaurus/docs/using-plutus-tx/compiling-plutus-tx.md
  doc/docusaurus/docs/using-plutus-tx/differences-from-haskell.md
  doc/docusaurus/docs/using-plutus-tx/environment-setup.md
  doc/docusaurus/docs/using-plutus-tx/extensions-flags-pragmas.md
  doc/docusaurus/docs/using-plutus-tx/inspecting.md
  doc/docusaurus/docs/using-plutus-tx/optimizing-scripts-with-asData.md
  doc/docusaurus/docs/using-plutus-tx/overview-plutus-tx.md
  doc/docusaurus/docs/using-plutus-tx/special-functions-and-types.md
  doc/docusaurus/docs/using-plutus-tx/writing-plutus-tx-programs.md
  doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
  doc/docusaurus/docs/working-with-scripts/script-purposes.md
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Entity.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypedBuiltinGen.hs
Labels: No Changelog Required
