Repository IntersectMBO/plutus, pull requests merged in 2024-08, with the labels that each got.

#6353 [Refactoring] Use 'KnownBuiltinTypeIn' instead of 'HasConstant' consistently
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/TypesTests.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Labels: Refactoring, Builtins, No Changelog Required

#6373 Restore auto generation of compiler option table
  .gitignore
  doc/docusaurus/docs/reference/plutus-tx-compiler-options.md
  plutus-tx-plugin/app/GeneratePluginOptionsDoc.hs
  plutus-tx-plugin/src/PlutusTx/Options.hs
Labels: No Changelog Required

#6368 Add the bitwise builtins to the metatheory
  plutus-conformance/agda/Spec.hs
  plutus-conformance/haskell-steppable/Spec.hs
  plutus-conformance/haskell/Spec.hs
  plutus-conformance/src/PlutusConformance/Common.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-metatheory/src/Algorithmic/CEK.lagda.md
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Cost/Model.lagda.md
  plutus-metatheory/src/Cost/Raw.lagda.md
  plutus-metatheory/src/Cost/Size.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
Labels: Metatheory, Costing, No Changelog Required

#6376 Restore CI checks for doc site code
  doc/docusaurus/docusaurus-examples.cabal
  doc/docusaurus/static/code/AuctionValidator.hs
  doc/docusaurus/static/code/BasicPlutusTx.hs
  doc/docusaurus/static/code/BasicPolicies.hs
  doc/docusaurus/static/code/BasicValidators.hs
  doc/docusaurus/static/code/myscript.uplc
Labels: No Changelog Required

#6356 andByteString conformance cases
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-10/case-10.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-10/case-10.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-10/case-10.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-4/case-4.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-5/case-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-5/case-5.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-5/case-5.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-6/case-6.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-6/case-6.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-6/case-6.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-7/case-7.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-7/case-7.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-7/case-7.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-8/case-8.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-8/case-8.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-8/case-8.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-9/case-9.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-9/case-9.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/andByteString/case-9/case-9.uplc.expected
Labels: No Changelog Required

#6359 Conformance cases for complementByteString
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/complementByteString/case-3/case-3.uplc.expected
Labels: No Changelog Required

#6357 Conformance for orByteString
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-10/case-10.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-10/case-10.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-10/case-10.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-4/case-4.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-5/case-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-5/case-5.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-5/case-5.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-6/case-6.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-6/case-6.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-6/case-6.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-7/case-7.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-7/case-7.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-7/case-7.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-8/case-8.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-8/case-8.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-8/case-8.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-9/case-9.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-9/case-9.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/orByteString/case-9/case-9.uplc.expected
Labels: No Changelog Required

#6360 Conformance cases for readBit
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-10/case-10.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-10/case-10.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-10/case-10.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-11/case-11.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-11/case-11.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-11/case-11.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-12/case-12.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-12/case-12.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-12/case-12.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-13/case-13.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-13/case-13.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-13/case-13.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-14/case-14.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-14/case-14.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-14/case-14.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-15/case-15.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-15/case-15.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-15/case-15.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-4/case-4.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-5/case-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-5/case-5.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-5/case-5.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-6/case-6.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-6/case-6.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-6/case-6.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-7/case-7.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-7/case-7.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-7/case-7.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-8/case-8.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-8/case-8.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-8/case-8.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-9/case-9.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-9/case-9.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/readBit/case-9/case-9.uplc.expected
Labels: No Changelog Required

#6363 Conformance for shiftByteString
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-4/case-4.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-5/case-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-5/case-5.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-5/case-5.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-6/case-6.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-6/case-6.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/shiftByteString/case-6/case-6.uplc.expected
Labels: No Changelog Required

#6366 Conformance for findFirstSetBit
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/findFirstSetBit/case-4/case-4.uplc.expected
Labels: No Changelog Required

#6358 Conformance for xorByteString
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-10/case-10.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-10/case-10.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-10/case-10.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-4/case-4.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-5/case-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-5/case-5.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-5/case-5.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-6/case-6.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-6/case-6.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-6/case-6.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-7/case-7.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-7/case-7.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-7/case-7.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-8/case-8.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-8/case-8.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-8/case-8.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-9/case-9.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-9/case-9.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/xorByteString/case-9/case-9.uplc.expected
Labels: No Changelog Required

#6365 Conformance for countSetBits
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/countSetBits/case-4/case-4.uplc.expected
Labels: No Changelog Required

#6374 Release 1.32.0.0
  cabal.project
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240711_030856_kenneth.mackenzie_bitwise_4.md
  plutus-core/changelog.d/20240726_102834_bezirg_ratinteger.md
  plutus-core/changelog.d/20240726_165736_Yuriy.Lazaryev_nothunks_0_2.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20240731_145553_effectfully_add_general_mkNil.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#6388 Some comments on deprecated tests
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Denotation.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Term.hs
Labels: No Changelog Required

#6385 Fix Agda interface to `shiftByteString` and `rotateByteString`
  plutus-metatheory/src/Builtin.lagda.md
Labels: No Changelog Required

#6387 Update chap&hackage nix flake sha
  flake.lock
Labels: No Changelog Required

#6364 Conformance for rotateByteString
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-1/case-1.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-1/case-1.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-1/case-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-2/case-2.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-2/case-2.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-2/case-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-3/case-3.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-3/case-3.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-3/case-3.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-4/case-4.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-4/case-4.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-4/case-4.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-5/case-5.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-5/case-5.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-5/case-5.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-6/case-6.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-6/case-6.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-6/case-6.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-7/case-7.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-7/case-7.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-7/case-7.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-8/case-8.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-8/case-8.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/rotateByteString/case-8/case-8.uplc.expected
Labels: No Changelog Required

#6395 Update RELEASE.adoc
  RELEASE.adoc
Labels: No Changelog Required

#6386 Hide bitwise internals
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-metatheory/src/Builtin.lagda.md
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Builtins, No Changelog Required

#6375 Add a page about different notions of version
  doc/docusaurus/docs/essential-concepts/language-versions.md
  doc/docusaurus/docs/essential-concepts/ledger.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
  doc/docusaurus/docs/essential-concepts/versions.md
  doc/docusaurus/docs/reference/plutus-tx-compiler-options.md
Labels: No Changelog Required

#6402 Remove uniques from some golden files
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
  plutus-tx-plugin/test/Plugin/Debug/9.6/fib.pir.golden
  plutus-tx-plugin/test/Plugin/Debug/9.6/letFun.pir.golden
  plutus-tx-plugin/test/Plugin/Debug/Spec.hs
Labels: No Changelog Required

#6401 Remove ADRs from user documentation
  doc/adr/README.md
  doc/adr/adr1.md
  doc/adr/adr2.md
  doc/adr/adr3.md
  doc/adr/adr4.md
  doc/docusaurus/docs/adr/_category_.json
Labels: No Changelog Required

#6404 Kwxm/mlabs/koz/ed25519
  plutus-benchmark/bitwise/bench/Main.hs
  plutus-benchmark/bitwise/src/PlutusBenchmark/Ed25519.hs
  plutus-benchmark/bitwise/src/PlutusBenchmark/Ed25519/Compiled.hs
  plutus-benchmark/bitwise/src/PlutusBenchmark/NQueens/Compiled.hs
  plutus-benchmark/bitwise/src/PlutusBenchmark/SHA512.hs
  plutus-benchmark/bitwise/test/9.6/8 queens.budget.golden
  plutus-benchmark/bitwise/test/9.6/8 queens.eval.golden
  plutus-benchmark/bitwise/test/9.6/8 queens.pir.golden
  plutus-benchmark/bitwise/test/9.6/8 queens.size.golden
  plutus-benchmark/bitwise/test/9.6/Ed25519.budget.golden
  plutus-benchmark/bitwise/test/9.6/Ed25519.eval.golden
  plutus-benchmark/bitwise/test/9.6/Ed25519.pir.golden
  plutus-benchmark/bitwise/test/9.6/Ed25519.size.golden
  plutus-benchmark/bitwise/test/Main.hs
  plutus-benchmark/plutus-benchmark.cabal
Labels: Builtins, Benchmarks, No Changelog Required

#6403 Add a page explaining script purposes
  doc/docusaurus/docs/working-with-scripts/script-purposes.md
  doc/docusaurus/docs/working-with-scripts/writing-basic-minting-policies.md
  doc/docusaurus/docs/working-with-scripts/writing-basic-validator-scripts.md
Labels: No Changelog Required

#6400 Add a page comparing Plutus V1, V2 and V3
  doc/docusaurus/docs/working-with-scripts/exporting-scripts-datums-redeemers.md
  doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
Labels: No Changelog Required

#6405 Rename the "Reference" section to "Delve Deeper"
  doc/docusaurus/docs/delve-deeper/_category_.json
  doc/docusaurus/docs/delve-deeper/common-weaknesses.md
  doc/docusaurus/docs/delve-deeper/cost-model-parameters.md
  doc/docusaurus/docs/delve-deeper/examples.md
  doc/docusaurus/docs/delve-deeper/further-resources.md
  doc/docusaurus/docs/delve-deeper/glossary.md
  doc/docusaurus/docs/delve-deeper/haddock-documentation.md
  doc/docusaurus/docs/delve-deeper/plutus-language-changes.md
  doc/docusaurus/docs/delve-deeper/plutus-tx-compiler-options.md
  doc/docusaurus/docs/delve-deeper/script-optimization-techniques.md
  doc/docusaurus/docs/delve-deeper/upgrade-vasil-plutus-script-addresses.md
  doc/docusaurus/docs/essential-concepts/ledger.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
  doc/docusaurus/docs/reference/_category_.json
  doc/docusaurus/docs/using-plutus-tx/compiling-plutus-tx.md
Labels: No Changelog Required

#6410 Move comment below title in plutus-tx-compiler-options.md
  doc/docusaurus/docs/delve-deeper/plutus-tx-compiler-options.md
  plutus-tx-plugin/app/GeneratePluginOptionsDoc.hs
Labels: No Changelog Required

#6407 Add sprint-issues-rolloever.yml workflow
  .github/workflows/sprint-issues-rollover.yml
Labels: No Changelog Required

#6299 Move cross-compiling logic from project.nix to cabal
  cabal.project
  doc/docusaurus/docusaurus-examples.cabal
  nix/project.nix
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
Labels: No Changelog Required

#6418 Workarounds to make constitution executable optionally buildable.
  cabal.project
  cardano-constitution/README.md
  cardano-constitution/app/create-json-envelope/Main.hs
  cardano-constitution/cardano-constitution.cabal
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
Labels: No Changelog Required

#6414 Kwxm/metatheory/fix test2
  nix/project.nix
  plutus-core/executables/pir/Main.hs
  plutus-core/executables/plc/Main.hs
  plutus-core/executables/src/PlutusCore/Executable/AstIO.hs
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
  plutus-core/executables/src/PlutusCore/Executable/Types.hs
  plutus-core/executables/uplc/Main.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Pretty/Plc.hs
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/test/AddInteger.agda
  plutus-metatheory/test/IntegerLiteral.agda
  plutus-metatheory/test/IntegerOverflow.agda
  plutus-metatheory/test/NEAT/Spec.hs
  plutus-metatheory/test/Negation.agda
  plutus-metatheory/test/StringLiteral.agda
  plutus-metatheory/test/TestDetailed.hs
  plutus-metatheory/test/detailed/Spec.hs
  plutus-metatheory/test/ii.plc
  plutus-metatheory/test/ii.tplc
  plutus-metatheory/test/readme.txt
  plutus-metatheory/test/simple/Spec.hs
  plutus-metatheory/test/test.plc
Labels: Test, Metatheory, No Changelog Required

#6420 Remove PyF from plutus-tx-plugin
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/src/PlutusTx/Options.hs
Labels: No Changelog Required

#6417 update mesh
  doc/docusaurus/docs/getting-started-plutus-tx.md
  doc/docusaurus/docs/simple-example/off-chain-code.md
Labels: No Changelog Required

#6409 Add a page comparing languages targeting UPLC
  doc/docusaurus/docs/delve-deeper/languages.md
Labels: No Changelog Required

#6421 Backport #6420 to 1.32
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/src/PlutusTx/Options.hs
Labels: No Changelog Required

#6422 1.32.1.0
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#6427 Update hard fork names had Haddock
  plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
  plutus-ledger-api/test-plugin/Spec/ReturnUnit/V1.hs
  plutus-ledger-api/test-plugin/Spec/ReturnUnit/V2.hs
  plutus-ledger-api/test-plugin/Spec/ReturnUnit/V3.hs
  plutus-ledger-api/test/Spec.hs
  plutus-ledger-api/test/Spec/Data/Versions.hs
  plutus-ledger-api/test/Spec/ScriptDecodeError.hs
  plutus-ledger-api/test/Spec/Versions.hs
Labels: No Changelog Required

#6429 Release 1.33.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240726_124910_bezirg_modexp.md
  plutus-core/changelog.d/20240806_115314_kenneth.mackenzie.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20240716_124825_ana.pantilie95_data_value_ledger_api.md
  plutus-ledger-api/changelog.d/20240726_125029_bezirg_modexp.md
  plutus-ledger-api/changelog.d/20240806_115735_kenneth.mackenzie_ripemd_160.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20240726_125023_bezirg_modexp.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20240726_125008_bezirg_modexp.md
  plutus-tx/changelog.d/20240806_115427_kenneth.mackenzie.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: Release

#6430 Remove Haddock from inside data declaration
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
Labels: No Changelog Required

#6431 Release 1.33.1.0
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required
