Repository IntersectMBO/plutus, pull requests merged in 2024-12, with the labels that each got.

#6729 Revert flake update
  flake.lock
Labels: No Changelog Required

#6728 Disambiguate uc/lc filenames in conformance tests.
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bool/false-lc/false-lc.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bool/false-lc/false-lc.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bool/false-lc/false-lc.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bool/true-lc/true-lc.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bool/true-lc/true-lc.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bool/true-lc/true-lc.uplc.expected
Labels: Test, No Changelog Required

#6715 Set CPU frequency governor and frequency before running the benchmarks
  nix/shell.nix
  scripts/ci-plutus-benchmark.sh
Labels: No Changelog Required

#6434 [Builtins] Make unlifting lazy again
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
Labels: Builtins, Performance, No Changelog Required

#6702 [Evaluation] [Names] Define all lookups in terms of 'contIndexZero'
  plutus-core/changelog.d/20241126_020822_effectfully_define_1_indexing_via_0_indexing.md
  plutus-core/index-envs/src/Data/RandomAccessList/SkewBinary.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: Evaluation, Performance, Name handling

#6736 Release 1.38.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20241126_020822_effectfully_define_1_indexing_via_0_indexing.md
  plutus-core/changelog.d/20241126_024818_effectfully_strictify_spend.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20241121_161607_Yuriy.Lazaryev_IsString_instances.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#6741 Remove taskset usage from ci-plutus-benchmarks.sh
  .github/workflows/manual-benchmark.yml
  scripts/ci-plutus-benchmark.sh
Labels: No Changelog Required

#6739 Update hard fork name
  plutus-core/CHANGELOG.md
  plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
Labels: No Changelog Required

#6744 filip(fix): add config for trailing slashes
  doc/docusaurus/docusaurus.config.ts
Labels: No Changelog Required

#6735 nix flake update
  flake.lock
  flake.nix
  nix/agda.nix
  nix/build-latex-doc.nix
  nix/build-latex.nix
  nix/latex-documents.nix
  nix/outputs.nix
  nix/plutus-metatheory-site.nix
  nix/project.nix
  nix/shell.nix
  nix/unraveling-recursion-paper.nix
Labels: No Changelog Required

#6657 add `MINIMAL` pragma to ord
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Queens.hs
  plutus-tx/src/PlutusTx/Ord.hs
Labels: No Changelog Required

#6757 Release 1.39.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20241211_095642_1009751+Unisay_relax_crypto_upper_bound.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20241212_191319_ana.pantilie95_fully_data_backed_sc.md
  plutus-ledger-api/changelog.d/20241218_155419_ana.pantilie95_v2_data_scriptcontext.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#6760 Fix typos in Plutus Core Spec of Batch 5 builtins
  doc/plutus-core-spec/cardano/builtins5.tex
Labels: Specification, No Changelog Required

#6762 Fix issues from #6761
  doc/plutus-core-spec/cardano/builtins4.tex
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: bug, Specification, No Changelog Required

#6730 Kwxm/conformance/improve filename check
  plutus-conformance/README.md
  plutus-conformance/src/PlutusConformance/Common.hs
Labels: Test, No Changelog Required
