Repository IntersectMBO/plutus, pull requests merged in 2024-10, with the labels that each got.

#6536 [Builtins] Disable 'writeBits' for chang+1
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/test/Spec/Data/CostModelParams.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Labels: Builtins, No Changelog Required, Plutus Ledger API

#6538 Release 1.35.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240924_105256_unsafeFixIO_pretty.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#6542 [Meta] Add Slack and Discord to 'TRIAGE.md'
  doc/TRIAGE.md
Labels: No Changelog Required

#6537 Merge the "Plutus language changes" into other pages
  doc/docusaurus/docs/delve-deeper/plutus-language-changes.md
  doc/docusaurus/docs/glossary.md
  doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
Labels: No Changelog Required

#6532 Expand the optimization techniques page in the user guide
  doc/docusaurus/docs/delve-deeper/languages.md
  doc/docusaurus/docs/delve-deeper/optimizing-scripts-with-asData.md
  doc/docusaurus/docs/delve-deeper/other-optimization-techniques.md
  doc/docusaurus/docs/delve-deeper/script-optimization-techniques.md
  plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
Labels: No Changelog Required

#6533 Rename and rewrite "Upgrading to Vasil and Plutus script addresses"
  README.adoc
  doc/docusaurus/docs/delve-deeper/common-weaknesses.md
  doc/docusaurus/docs/delve-deeper/understanding-script-hashes.md
  doc/docusaurus/docs/delve-deeper/upgrade-vasil-plutus-script-addresses.md
Labels: No Changelog Required

#6549 Remove the common weaknesses page
  doc/docusaurus/docs/delve-deeper/common-weaknesses.md
Labels: No Changelog Required

#6548 Add a note in the user guide about avoiding the INLINE pragma
  doc/docusaurus/docs/delve-deeper/other-optimization-techniques.md
  doc/docusaurus/docs/using-plutus-tx/extensions-flags-pragmas.md
Labels: No Changelog Required

#6546 Update the Haddock Documentation page in the user guide
  doc/docusaurus/docs/delve-deeper/haddock-documentation.md
Labels: No Changelog Required

#6551 Add new URL exception to check-broken-links.sh
  scripts/check-broken-links.sh
Labels: No Changelog Required

#6552 Add new ignored urls and fix logic in check-broken-links.sh
  scripts/check-broken-links.sh
Labels: No Changelog Required

#6555 Plutus release 1.36.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20241008_220810_kenneth.mackenzie_new_semantics.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20241008_221415_kenneth.mackenzie_new_semantics.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required, Release

#6550 Redraw contract lifecycle images, remove the rest of the page
  doc/docusaurus/docs/auction-smart-contract/end-to-end/closing-the-auction.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/mint.md
  doc/docusaurus/docs/auction-smart-contract/end-to-end/placing-bids.md
  doc/docusaurus/docs/auction-smart-contract/life-cycle.md
  doc/docusaurus/static/img/closing-tx-simple-auction-v3.png
  doc/docusaurus/static/img/double-satisfaction.png
  doc/docusaurus/static/img/first-bid-simple-auction-v3.png
  doc/docusaurus/static/img/second-bid-simple-auction-v3.png
  doc/docusaurus/static/img/tx1.png
  doc/docusaurus/static/img/tx2.png
  doc/docusaurus/static/img/tx3.png
  doc/docusaurus/static/img/tx4.png
Labels: No Changelog Required

#6556 Fix haddock dropdown element in haddock index
  .github/workflows/haddock-site.yml
  .gitignore
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6426 Kwxm/specification/bitwise
  doc/plutus-core-spec/cardano/builtins1.tex
  doc/plutus-core-spec/cardano/builtins2.tex
  doc/plutus-core-spec/cardano/builtins3.tex
  doc/plutus-core-spec/cardano/builtins4.tex
  doc/plutus-core-spec/cardano/builtins5.tex
  doc/plutus-core-spec/cardano/cardano.tex
  doc/plutus-core-spec/cardano/versions.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/notation.tex
  doc/plutus-core-spec/plutus-core-specification.bib
  doc/plutus-core-spec/plutus-core-specification.tex
  doc/plutus-core-spec/untyped-reduction.tex
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Labels: Specification, Builtins, No Changelog Required

#6558 Expand "Overview of Languages Compiling to UPLC"
  doc/docusaurus/docs/delve-deeper/languages.md
Labels: No Changelog Required

#6557 [Meta] Add CIPs to 'TRIAGE.md'
  doc/TRIAGE.md
Labels: No Changelog Required

#6560 Explain Scott/Church/SOP/Data encoding in the user guide
  doc/docusaurus/docs/delve-deeper/encoding.md
Labels: No Changelog Required

#6559 Fix bug in haddock-site.yml
  .github/workflows/haddock-site.yml
Labels: No Changelog Required

#6561 Ramsay's add uplc opt tags
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
Labels: No Changelog Required

#6566 Polish the profiling guide
  doc/docusaurus/docs/delve-deeper/encoding.md
  doc/docusaurus/docs/working-with-scripts/optimizing-scripts-with-asData.md
  doc/docusaurus/docs/working-with-scripts/other-optimization-techniques.md
  doc/docusaurus/docs/working-with-scripts/profiling-budget-usage.md
Labels: No Changelog Required

#6567 Add a few references in the further resources page
  doc/docusaurus/docs/delve-deeper/further-resources.md
Labels: No Changelog Required

#6565 Update the Ledgers page in the user guide
  doc/docusaurus/docs/essential-concepts/eutxo.md
  doc/docusaurus/docs/essential-concepts/ledger.md
Labels: No Changelog Required

#6570 Add new ignore url to check-broken-links.sh
  scripts/check-broken-links.sh
Labels: No Changelog Required

#6568 Fix positioning of select element in combined-haddock.sh
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6564 Update and simplify the home page of the user guide
  doc/docusaurus/docs/index.md
Labels: No Changelog Required

#6576 Add new user to slack-message-broker.yml
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#6580 Fix typo
  doc/plutus-core-spec/cardano/builtins5.tex
Labels: Specification, No Changelog Required

#6498 Cost model overview document
  doc/cost-model-overview/Makefile
  doc/cost-model-overview/cost-model-overview.pdf
  doc/cost-model-overview/cost-model-overview.tex
Labels: Documentation, No Changelog Required

#6583 Remove mentions to @channel in slack-message-broker.yml
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#6540 Add simplifier tags in UPLC simplifier
  plutus-core/executables/plutus/AnyProgram/Compile.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Compiler.hs
  plutus-core/plutus-core/src/PlutusCore/Compiler/Types.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/Tests/Lib.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Simplify.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/CaseOfCase.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/CaseReduce.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Cse.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/FloatDelay.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/ForceDelay.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Simplifier.hs
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/Test.hs
  plutus-core/untyped-plutus-core/test/Transform/Simplify/Lib.hs
  plutus-executables/executables/pir/Main.hs
  plutus-executables/executables/uplc/Main.hs
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx/src/PlutusTx/Lift.hs
Labels: No Changelog Required

#6582 Add cost model page in the user guide
  doc/docusaurus/docs/delve-deeper/cost-model-parameters.md
  doc/docusaurus/docs/delve-deeper/cost-model.md
Labels: No Changelog Required

#6586 Don't run slack-message-broker on draft PRs
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#6589 Change references to plutus-shared in plutus-ci in the workflows
  .github/workflows/broken-links.yml
  .github/workflows/cardano-constitution-tests.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/nightly-testsuite.yml
  .github/workflows/papers-and-specs.yml
Labels: No Changelog Required

#6588 Update all Flake Inputs & Add texliveFull to the devShell
  .editorconfig
  cabal.project
  cardano-constitution/cardano-constitution.cabal
  flake.lock
  flake.nix
  nix/agda-packages.nix
  nix/latex-documents.nix
  nix/outputs.nix
  nix/plutus-metatheory-site.nix
  nix/shell.nix
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Queens.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/Setup.hs
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/VerifiedCompilation/UCaseReduce.lagda.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#6599 derive PlutusTx.Show for some ledger api types
  plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/DCert.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs
Labels: No Changelog Required

#6601 Fix latex errors in old specification
  doc/plutus-core-spec-old/figures/TypedCkMachine.tex
  doc/plutus-core-spec-old/figures/UntypedCekMachine.tex
  doc/plutus-core-spec-old/figures/UntypedCkMachine.tex
  doc/plutus-core-spec/README.md
  nix/latex-documents.nix
Labels: Specification, No Changelog Required

#6512 Add expModInteger to specification
  doc/plutus-core-spec/Makefile
  doc/plutus-core-spec/builtins.tex
  doc/plutus-core-spec/cardano/builtins1.tex
  doc/plutus-core-spec/cardano/builtins2.tex
  doc/plutus-core-spec/cardano/builtins3.tex
  doc/plutus-core-spec/cardano/builtins4.tex
  doc/plutus-core-spec/cardano/builtins5.tex
  doc/plutus-core-spec/cardano/builtins6.tex
  doc/plutus-core-spec/cardano/cardano.tex
  doc/plutus-core-spec/data-cbor.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/notation.tex
  doc/plutus-core-spec/plutus-core-specification.bib
  doc/plutus-core-spec/plutus-core-specification.tex
  doc/plutus-core-spec/untyped-cek-machine.tex
  doc/plutus-core-spec/untyped-grammar.tex
  doc/plutus-core-spec/untyped-reduction.tex
  doc/plutus-core-spec/untyped-values.tex
Labels: No Changelog Required

#6617 Add extra test vectors for verifySchnorrSecp256k1Signature
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-00/test-vector-00.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-00/test-vector-00.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-00/test-vector-00.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-01/test-vector-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-01/test-vector-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-01/test-vector-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-02/test-vector-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-02/test-vector-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-02/test-vector-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-03/test-vector-03.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-03/test-vector-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-03/test-vector-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-04/test-vector-04.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-04/test-vector-04.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-04/test-vector-04.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-05/test-vector-05.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-05/test-vector-05.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-05/test-vector-05.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-06/test-vector-06.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-06/test-vector-06.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-06/test-vector-06.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-07/test-vector-07.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-07/test-vector-07.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-07/test-vector-07.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-08/test-vector-08.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-08/test-vector-08.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-08/test-vector-08.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-09/test-vector-09.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-09/test-vector-09.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-09/test-vector-09.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-10/test-vector-10.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-10/test-vector-10.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-10/test-vector-10.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-11/test-vector-11.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-11/test-vector-11.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-11/test-vector-11.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-12/test-vector-12.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-12/test-vector-12.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-12/test-vector-12.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-13/test-vector-13.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-13/test-vector-13.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-13/test-vector-13.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-14/test-vector-14.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-14/test-vector-14.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-14/test-vector-14.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-15/test-vector-15.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-15/test-vector-15.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-15/test-vector-15.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-16/test-vector-16.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-16/test-vector-16.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-16/test-vector-16.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-17/test-vector-17.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-17/test-vector-17.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-17/test-vector-17.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-18/test-vector-18.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-18/test-vector-18.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature/test-vector-18/test-vector-18.uplc.expected
Labels: Test, Builtins, Crypto, status: triaged, No Changelog Required, Internal
