Repository IntersectMBO/plutus, pull requests merged in 2024-05, with the labels that each got.

#5950 Update CONTRIBUTING.adoc
  CONTRIBUTING.adoc
Labels: No Changelog Required

#5935 Add 'Note [Table of all possible ledger's states w.r.t. cost model parameters update]'
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
Labels: Docs, Ledger, Costing, No Changelog Required

#5956 Remove annoying error message
  plutus-core/cost-model/budgeting-bench/Benchmarks/Strings.hs
  plutus-core/cost-model/budgeting-bench/CriterionExtensions.hs
  plutus-core/cost-model/budgeting-bench/Main.hs
Labels: No Changelog Required

#5954 [PIR] Don't generate 'fixBy' if you don't need to
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Function.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Recursion.hs
  plutus-core/plutus-ir/test/PlutusIR/Compiler/Recursion/factorial.golden
  plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/strictLetRec.golden
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/GenTm.hs
Labels: enhancement, Plutus IR, No Changelog Required

#5965 Chore: formatting, imports, pragmas.
  plutus-core/plutus-core/test/Names/Spec.hs
Labels: No Changelog Required

#5960 CaseOfCase UPLC transformation tests.
  plutus-benchmark/nofib/test/9.6/knights10-4x4.budget.golden
  plutus-benchmark/nofib/test/9.6/knights10-4x4.size.golden
  plutus-core/plutus-core.cabal
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/CaseOfCase.hs
  plutus-core/untyped-plutus-core/test/Spec.hs
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/1.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/2.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/3.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/Test.hs
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/withError.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/Simplify.hs
  plutus-core/untyped-plutus-core/test/Transform/Simplify/Lib.hs
  plutus-core/untyped-plutus-core/test/Transform/caseOfCase1.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/caseOfCase2.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/caseOfCase3.uplc.golden
Labels: No Changelog Required

#5959 Improvements to plutus-metatheory site
  nix/plutus-metatheory-site.nix
  nix/shell.nix
  plutus-metatheory/.gitignore
  plutus-metatheory/README.md
  plutus-metatheory/html/_layouts/page.html
  plutus-metatheory/src/Algorithmic.lagda.md
  plutus-metatheory/src/Algorithmic/BehaviouralEquivalence/CCvsCK.lagda.md
  plutus-metatheory/src/Algorithmic/BehaviouralEquivalence/CKvsCEK.lagda.md
  plutus-metatheory/src/Algorithmic/CEK.lagda.md
  plutus-metatheory/src/Algorithmic/CK.lagda.md
  plutus-metatheory/src/Algorithmic/Completeness.lagda.md
  plutus-metatheory/src/Algorithmic/Erasure.lagda.md
  plutus-metatheory/src/Algorithmic/Erasure/RenamingSubstitution.lagda.md
  plutus-metatheory/src/Algorithmic/Evaluation.lagda.md
  plutus-metatheory/src/Algorithmic/Examples.lagda.md
  plutus-metatheory/src/Algorithmic/Properties.lagda.md
  plutus-metatheory/src/Algorithmic/Reduction.lagda.md
  plutus-metatheory/src/Algorithmic/ReductionEC.lagda.md
  plutus-metatheory/src/Algorithmic/ReductionEC/Determinism.lagda.md
  plutus-metatheory/src/Algorithmic/ReductionEC/Progress.lagda.md
  plutus-metatheory/src/Algorithmic/RenamingSubstitution.lagda.md
  plutus-metatheory/src/Algorithmic/Signature.lagda.md
  plutus-metatheory/src/Algorithmic/Soundness.lagda.md
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Builtin/Constant/AtomicType.lagda.md
  plutus-metatheory/src/Check.lagda.md
  plutus-metatheory/src/Cost.lagda.md
  plutus-metatheory/src/Cost/Base.lagda.md
  plutus-metatheory/src/Cost/Model.lagda.md
  plutus-metatheory/src/Cost/Raw.lagda.md
  plutus-metatheory/src/Cost/Size.lagda.md
  plutus-metatheory/src/Declarative/Examples/StdLib/ChurchNat.lagda.md
  plutus-metatheory/src/Declarative/Examples/StdLib/Function.lagda.md
  plutus-metatheory/src/Declarative/Examples/StdLib/Nat.lagda.md
  plutus-metatheory/src/Evaluator/Base.lagda.md
  plutus-metatheory/src/Evaluator/Program.lagda.md
  plutus-metatheory/src/Evaluator/Term.lagda.md
  plutus-metatheory/src/Main.lagda.md
  plutus-metatheory/src/Raw.lagda.md
  plutus-metatheory/src/RawU.lagda.md
  plutus-metatheory/src/Scoped.lagda.md
  plutus-metatheory/src/Scoped/Extrication.lagda.md
  plutus-metatheory/src/Scoped/Extrication/RenamingSubstitution.lagda.md
  plutus-metatheory/src/Scoped/RenamingSubstitution.lagda.md
  plutus-metatheory/src/Type/BetaNBE.lagda.md
  plutus-metatheory/src/Type/BetaNBE/Completeness.lagda.md
  plutus-metatheory/src/Type/BetaNBE/RenamingSubstitution.lagda.md
  plutus-metatheory/src/Type/BetaNBE/Soundness.lagda.md
  plutus-metatheory/src/Type/BetaNBE/Stability.lagda.md
  plutus-metatheory/src/Type/BetaNormal.lagda.md
  plutus-metatheory/src/Type/BetaNormal/Equality.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-metatheory/src/Untyped/CEKWithCost.lagda.md
  plutus-metatheory/src/Utils.lagda.md
  plutus-metatheory/src/Utils/Decidable.lagda.md
  plutus-metatheory/src/Utils/List.lagda.md
  plutus-metatheory/src/Utils/Reflection.lagda.md
Labels: No Changelog Required

#5974 [Build] Remove the doctests runner of 'prettyprinter-configurable'
  prettyprinter-configurable/Setup.hs
  prettyprinter-configurable/doctest/Main.hs
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: Build, No Changelog Required

#5973 Kwxm/mainnet script budgets
  plutus-ledger-api/exe/analyse-script-events/Main.hs
Labels: Costing, No Changelog Required

#5975 Release 1.28.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240503_135941_Yuriy.Lazaryev_strictify_fix.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20240509_114920_unsafeFixIO_index_budget.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5971 [PlutusTx] [Builtins] Split 'FromBuiltin' and 'ToBuiltin'
  plutus-core/plutus-core/src/PlutusCore/Builtin/Polymorphism.hs
  plutus-ledger-api/test-plugin/Spec/Value.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/test/Plugin/Primitives/9.6/deconstructorData2.pir.golden
  plutus-tx/changelog.d/20240513_014001_effectfully_split_FromBuiltin_and_ToBuiltin_into_IsBuiltin_and_IsOpaque.md
  plutus-tx/plutus-tx.cabal
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Class.hs
  plutus-tx/src/PlutusTx/Builtins/HasBuiltin.hs
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
  plutus-tx/src/PlutusTx/Lift/Class.hs
  plutus-tx/src/PlutusTx/Lift/TestInstances.hs
  plutus-tx/src/PlutusTx/Prelude.hs
Labels: Plutus Tx, Builtins

#5997 Update README.md
  doc/plutus-core-spec/README.md
Labels: No Changelog Required

#6015 Script to prepare binary executables for uploading to the github release page.
  RELEASE.adoc
  scripts/prepare-bins.sh
Labels: No Changelog Required

#6057 Kwxm/mainnet script budgets 2
  plutus-ledger-api/exe/analyse-script-events/Main.hs
Labels: No Changelog Required

#6064 [Refactoring] Remove 'UnknownBuiltin'
  plutus-core/changelog.d/20240520_192738_effectfully_remove_UnknownBuiltin.md
  plutus-core/plutus-core/src/PlutusCore/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
Labels: Evaluation, Refactoring

#6061 Conditionally add 'triage' label to new issues
  .github/workflows/add-triage-label.yml
Labels: No Changelog Required

#6065 Add integerToByteString and byteStringToInteger to V2.ParamName
  plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V2/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Labels: No Changelog Required

#6062 Let nightly.yml accept hedgehog-tests input
  .github/workflows/nightly.yml
Labels: No Changelog Required

#6086 Add a Plutus Tx test utility package
  cabal.project
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/test/AssocMap/Spec.hs
  plutus-tx-test-util/LICENSE
  plutus-tx-test-util/NOTICE
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx-test-util/testlib/PlutusTx/Test/Util/Compiled.hs
Labels: No Changelog Required

#6043 [Errors] polish evaluation errors
  doc/notes/plutus-core/cek-budgeting-profiling/CostingDetails.md
  plutus-benchmark/nofib/exe/Main.hs
  plutus-core/changelog.d/20240517_191403_effectfully_polish_evaluation_errors.md
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
  plutus-core/plutus-core/test/Evaluation/Machines.hs
  plutus-core/plutus-ir/test/PlutusIR/Compiler/Recursion/errorBinding.golden
  plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/Tests/Lib.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/CommonAPI.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Common.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex3.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex4.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNoBranch.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNoBranch.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNonTag.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/caseNonTag.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/diFullyApplied.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/diFullyApplied.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteAtIntegerAtInteger.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteAtIntegerAtInteger.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteAtIntegerWrongCondTypeSat.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteAtIntegerWrongCondTypeSat.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteTypeTermType.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteTypeTermType.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteUninstantiatedFullyApplied.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteUninstantiatedFullyApplied.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteUninstantiatedWithCond.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/iteUninstantiatedWithCond.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/mulInstError1.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/mulInstError1.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/mulInstError2.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/mulInstError2.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/mulInstError3.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/mulInstError3.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.uplc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
  plutus-core/untyped-plutus-core/test/Transform/CaseOfCase/Test.hs
  plutus-tx-plugin/test/Plugin/Basic/9.6/ifOptEval.eval.golden
  plutus-tx-plugin/test/Strictness/9.6/lambda-default.eval.golden
  plutus-tx-plugin/test/Strictness/9.6/lambda-nonstrict.eval.golden
  plutus-tx-plugin/test/Strictness/9.6/lambda-strict.eval.golden
  plutus-tx-test-util/testlib/PlutusTx/Test/Util/Compiled.hs
Labels: Evaluation, Refactoring, Error handling

#6091 Run nightly tests on plutus-benchmark
  .github/workflows/nightly.yml
  nix/project.nix
Labels: No Changelog Required

#5918 [Exe] Generalize 'withL' to 'withLangGeneral'
  plutus-core/executables/plutus/AnyProgram/IO.hs
  plutus-core/executables/plutus/AnyProgram/With.hs
Labels: Refactoring, Plutus Exe

#6037 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/security_report.yml
Labels: No Changelog Required

#6149 Remove reference to benching.csv in plutus-core.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#6153 Kwxm/costing/reduce CEK CPU step costs B
  plutus-core/changelog.d/20240530_123928_kenneth.mackenzie_reduce_cek_cpu_step_costs_B.md
  plutus-core/cost-model/data/cekMachineCostsB.json
Labels: Costing

#6152 Use the most recent evaluation context for most of the benchmarks
  plutus-benchmark/bls12-381-costs/bench/Bench.hs
  plutus-benchmark/cek-calibration/Main.hs
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/lists/bench/Bench.hs
  plutus-benchmark/marlowe/bench/BenchCek.hs
  plutus-benchmark/nofib/bench/BenchCek.hs
  plutus-benchmark/nofib/bench/Shared.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-benchmark/validation/bench/BenchCek.hs
  plutus-benchmark/validation/bench/BenchFull.hs
Labels: Benchmarks, No Changelog Required

#6036 [Builtins] Polish handling of integral types
  plutus-core/changelog.d/20240529_153319_effectfully_polish_handling_of_integral_types.md
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownTypeAst.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
Labels: Builtins, User experience
