Repository IntersectMBO/plutus, pull requests merged in 2024-07, with the labels that each got.

#6263 Fix bug in ./script/combined-haddock.sh
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6275 Update baseUrl in docusaurus.config.ts
  doc/docusaurus/docusaurus.config.ts
Labels: No Changelog Required

#6276 Improvements to haddock-site.yml (support auto-publish on push to master)
  .github/workflows/haddock-site.yml
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6280 Better messages in slack-message-broker.yml
  .github/workflows/slack-message-broker.yml
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6283 Add cabal update step in combined-haddock.sh
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6282 Fix CsvTable.tsx and LiteralInclde.tsx in docusaurus
  doc/docusaurus/docusaurus.config.ts
  doc/docusaurus/src/components/CsvTable.tsx
  doc/docusaurus/src/components/LiteralInclude.tsx
Labels: No Changelog Required

#6284 Fix haddock documentation for cardano-constitution
  .github/workflows/cardano-constitution-tests.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/nightly-testsuite.yml
  cardano-constitution/src/Cardano/Constitution/Validator/Sorted.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Unsorted.hs
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6287 Stronger docusaurus builds and general QOL improvements
  .github/workflows/changelog-label.yml
  .github/workflows/cost-model-benchmark.yml
  .github/workflows/manual-benchmark.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/nightly-testsuite.yml
  .github/workflows/slack-message-broker.yml
  doc/docusaurus/docs/reference/common-weaknesses.md
  doc/docusaurus/docusaurus.config.ts
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6289 Move package-lock.json from top-level to scripts/blueprints
  scripts/blueprints/check-json-schemas.js
  scripts/blueprints/package-lock.json
  scripts/blueprints/package.json
Labels: No Changelog Required

#6291 Fix editUrl in docusaurus.config.ts
  doc/docusaurus/docusaurus.config.ts
Labels: No Changelog Required

#6288 Fix typos
  doc/docusaurus/docs/index.md
  doc/docusaurus/docs/reference/common-weaknesses.md
  doc/docusaurus/docs/reference/plutus-language-changes.md
  doc/docusaurus/docs/simple-example/eutxo-model.md
Labels: No Changelog Required

#6294 Detect broken links for haddock,metatheory,docusaurus + local repo files
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/broken-links.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/longitudinal-benchmark.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/papers-and-specs.yml
  README.adoc
  doc/docusaurus/README.md
  doc/docusaurus/docs/essential-concepts/plutus-foundation.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
  doc/docusaurus/docs/index.md
  doc/docusaurus/docs/reference/haddock-documentation.md
  doc/docusaurus/docusaurus.config.ts
  doc/plutus-core-spec/README.md
  doc/read-the-docs-site/README.md
  plutus-core/docs/BuiltinsOverview.md
  plutus-metatheory/README.md
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Type/RenamingSubstitution.lagda.md
  scripts/check-broken-links.sh
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6295 Fix broken linkchecker workflows
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/metatheory-site.yml
  doc/docusaurus/README.md
  doc/docusaurus/docs/essential-concepts/plutus-foundation.md
  doc/docusaurus/docs/essential-concepts/plutus-platform.mdx
  doc/docusaurus/docs/index.md
  doc/docusaurus/docs/reference/haddock-documentation.md
Labels: No Changelog Required

#6297 Add .github/actions/linkchecker/action.yml
  .github/actions/linkchecker/action.yml
Labels: No Changelog Required

#6293 Add support for ghc910 to hydraJobs
  flake.lock
  nix/outputs.nix
  nix/project.nix
  plutus-metatheory/Setup.hs
Labels: No Changelog Required

#6298 Disable linkchecker on live sites
  .github/actions/linkchecker/action.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/metatheory-site.yml
Labels: No Changelog Required

#6272 [Bug] Fix 'isNormalType' and add 'prop_normalizedTypeIsNormal'
  plutus-core/changelog.d/20240701_104059_effectfully_fix_isNormalType.md
  plutus-core/plutus-core/src/PlutusCore/Check/Normal.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Eq.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Classic.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Pretty/Readable.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Scoping.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
  plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
  plutus-core/plutus-core/test/Check/Spec.hs
  plutus-core/plutus-core/test/Normalization/Check.hs
  plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/TypesTests.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Type.hs
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/ShrinkTypes.hs
  plutus-core/testlib/PlutusIR/Generators/QuickCheck/GenerateTerms.hs
  plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
  plutus-metatheory/src/Raw.hs
Labels: bug, Test, Builtins

#6300 Analyse script events supports PlutusLedgerLanguage V3
  plutus-ledger-api/exe/analyse-script-events/Main.hs
  plutus-ledger-api/exe/common/LoadScriptEvents.hs
  plutus-ledger-api/exe/test-onchain-evaluation/Main.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
Labels: No Changelog Required

#6305 Address guardrail script audit comments
  cardano-constitution/src/Cardano/Constitution/Validator/Common.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Unsorted.hs
  cardano-constitution/src/PlutusTx/NonCanonicalRational.hs
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
Labels: No Changelog Required

#6307 fix: types in defaultConstitution
  cardano-constitution/data/defaultConstitution.json
  cardano-constitution/src/Cardano/Constitution/Config/Instance/FromJSON.hs
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
Labels: No Changelog Required

#6309 Fix overflow bug in shiftByteString, rotateByteString, add tests to ensure it stays fixed
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Builtins, No Changelog Required

#6312 Release 1.31.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240510_200705_Yuriy.Lazaryev_4808_unique_names_roundtrip_tests.md
  plutus-core/changelog.d/20240618_023306_effectfully_replace_EvaluationResult_with_BuiltinResult.md
  plutus-core/changelog.d/20240620_025344_effectfully_remove_Emitter_and_MonadEmitter.md
  plutus-core/changelog.d/20240626_184002_effectfully_remove_case_of_case.md
  plutus-core/changelog.d/20240701_104059_effectfully_fix_isNormalType.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#6313 Re-export bitwise builtins from PlutusTx.Prelude
  plutus-tx/src/PlutusTx/Prelude.hs
Labels: No Changelog Required

#6285 [Costing] Increase the cost of constructors of '[]'
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Costing.hs
Labels: Costing, No Changelog Required

#6317 Change writeBits to take changelists as two separate lists
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/WriteBits.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Laws.hs
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: No Changelog Required

#6318 [Costing] Remove the 'ExMemoryUsage' instance for 'SomeTypeIn'
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
Labels: Costing, No Changelog Required

#6320 feat: New version of VT-CC-01
  cardano-constitution/certification/documentation-traceability.md
  cardano-constitution/certification/testing-traceability.md
  cardano-constitution/data/defaultConstitution.json
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
  cardano-constitution/test/Helpers/Guardrail.hs
Labels: No Changelog Required

#6286 [Test] Make tests take reasonable time
  plutus-core/plutus-core/test/Evaluation/Machines.hs
  plutus-core/plutus-core/test/Evaluation/Spec.hs
  plutus-core/plutus-core/test/Names/Spec.hs
  plutus-core/plutus-core/test/Normalization/Type.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/BuiltinsTests.hs
  plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/SubstitutionTests.hs
  plutus-core/plutus-ir/test/PlutusCore/Generators/QuickCheck/TypesTests.hs
  plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Parser/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/EvaluateBuiltins/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/Inline/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/LetFloatIn/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/LetFloatOut/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/NonStrict/Tests.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/testlib/PlutusIR/Pass/Test.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/BLS12_381.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Laws.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SignatureVerification.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
  plutus-core/untyped-plutus-core/test/Flat/Spec.hs
Labels: Test, Performance, No Changelog Required

#6323 fix: haddock error
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/EvaluationEvent.hs
Labels: No Changelog Required

#6324 Reverse hunk test_multiSplitSound
  plutus-core/plutus-core/test/Generators/QuickCheck/Utils.hs
Labels: No Changelog Required

#6301 Kwxm/costing/bitwise 4
  plutus-benchmark/bls12-381-costs/bench/Bench.hs
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/RunTests.hs
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
  plutus-core/changelog.d/20240711_030856_kenneth.mackenzie_bitwise_4.md
  plutus-core/cost-model/budgeting-bench/Benchmarks/Bitwise.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/ByteStrings.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Crypto.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Data.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Integers.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Strings.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/cost-model/budgeting-bench/Generators.hs
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching-conway.csv
  plutus-core/cost-model/data/builtinCostModelA.json
  plutus-core/cost-model/data/builtinCostModelB.json
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/print-cost-model/Main.hs
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/plutus-core/test/CostModelSafety/Spec.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Builtin.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Conversion.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Builtins, Costing

#6329 [Plinth] [Builtins] Fix 'writeBits'
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/test/Plugin/Debug/9.6/fib.pir.golden
  plutus-tx-plugin/test/Plugin/Debug/9.6/letFun.pir.golden
  plutus-tx-plugin/test/Plugin/Primitives/9.6/writeBits-integerToByteString.eval.golden
  plutus-tx-plugin/test/Plugin/Primitives/Spec.hs
  plutus-tx-plugin/test/Plugin/Profiling/9.6/addInt.pir.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/addInt3.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/argMismatch1.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/argMismatch2.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/fact4.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/fib.pir.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/fib4.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/id.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/idCode.pir.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/letInFun.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/letInFunMoreArg.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/letRecInFun.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/swap.eval.golden
  plutus-tx-plugin/test/Plugin/Profiling/9.6/typeclass.eval.golden
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: bug, Plutus Tx, Builtins, No Changelog Required

#6342 [Plinth] Ban using 'toBuiltin' and 'fromBuiltin'
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Plugin/Errors/9.6/fromBuiltinUsed.uplc.golden
  plutus-tx-plugin/test/Plugin/Errors/9.6/toBuiltinUsed.uplc.golden
  plutus-tx-plugin/test/Plugin/Errors/Spec.hs
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/HasBuiltin.hs
  plutus-tx/src/PlutusTx/IsData/Class.hs
Labels: Plutus Tx, Builtins, User experience, No Changelog Required

#6343 Kwxm/bitwise/enable nqueens benchmark
  plutus-benchmark/bitwise/bench/Main.hs
  plutus-benchmark/plutus-benchmark.cabal
Labels: Builtins, Benchmarks, No Changelog Required

#6314 Fix equality Agda <-> Haskell
  plutus-metatheory/src/Utils.lagda.md
  plutus-metatheory/src/VerifiedCompilation/Equality.lagda.md
Labels: No Changelog Required

#6350 Make NumBytesCostedAsNumWords use Integer instead of Int
  plutus-core/cost-model/budgeting-bench/Benchmarks/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Conversion.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Builtins, Costing, No Changelog Required

#6328 [Benchmark] Reduce the number of benchmarks
  plutus-benchmark/lists/bench/Bench.hs
  plutus-benchmark/nofib/bench/Shared.hs
Labels: Performance, Benchmarks, No Changelog Required

#6315 [Test] Improve distribution of generated integers
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Core/Plated.hs
  plutus-core/plutus-core/test/Parser/Spec.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Plated.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
  plutus-core/plutus-ir/test/PlutusIR/Parser/Tests.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/AST.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Builtin.hs
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/testlib/PlutusIR/Generators/AST.hs
  plutus-core/testlib/UntypedPlutusCore/Generators/Hedgehog.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Plated.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Costing.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Generators.hs
Labels: Test, Builtins, No Changelog Required, Generators
