Repository IntersectMBO/plutus, pull requests merged in 2024-04, with the labels that each got.

#5837 CIP-0057: Extend the Blueprint test case with the `AsData` example.
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/test/Blueprint/Acme.golden.json
  plutus-tx-plugin/test/Blueprint/Tests.hs
  plutus-tx-plugin/test/Blueprint/Tests/Lib.hs
  plutus-tx-plugin/test/Blueprint/Tests/Lib/AsData/Blueprint.hs
  plutus-tx-plugin/test/Blueprint/Tests/Lib/AsData/Decls.hs
  plutus-tx/plutus-tx.cabal
  plutus-tx/src/PlutusTx/AsData.hs
  plutus-tx/src/PlutusTx/Blueprint/Definition.hs
  plutus-tx/src/PlutusTx/Blueprint/Definition/Internal.hs
  plutus-tx/src/PlutusTx/Blueprint/Definition/Unroll.hs
  plutus-tx/src/PlutusTx/Blueprint/Schema.hs
  plutus-tx/test/Blueprint/Spec.hs
Labels: No Changelog Required

#5871 Improve formatting of output of check-Notes
  scripts/check-Notes.awk
  scripts/check-Notes.sh
Labels: No Changelog Required

#5854 Agda html
  plutus-metatheory/src/Type.lagda.md
  plutus-metatheory/src/Type/Equality.lagda.md
  plutus-metatheory/src/Type/RenamingSubstitution.lagda.md
  plutus-metatheory/src/Utils.lagda.md
Labels: No Changelog Required

#5873 Release 1.25.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240326_133744_Yuriy.Lazaryev_term_eval_order_builtin.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20240402_143807_Yuriy.Lazaryev_short_circuit_and_or.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5872 Remove obsolete edge case for GHC98/HSL from shell.nix
  flake.lock
  nix/shell.nix
Labels: No Changelog Required

#5867 [Bench] Fix arbitrary evaluation nonsense
  plutus-benchmark/README.md
  plutus-benchmark/cek-calibration/Main.hs
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/lists/bench/Bench.hs
  plutus-benchmark/nofib/bench/BenchCek.hs
  plutus-benchmark/nofib/bench/Shared.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-benchmark/validation/bench/BenchCek.hs
  plutus-benchmark/validation/bench/Common.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
Labels: bug, Benchmarks, No Changelog Required

#5878 nix flake update iogx
  flake.lock
Labels: No Changelog Required

#5879 Kwxm/flat/canonincal data encoding (PLT-9705)
  plutus-core/changelog.d/20240405_015609_kenneth.mackenzie_canonincal_data_encoding.md
  plutus-core/plutus-core/src/PlutusCore/Flat.hs
  plutus-core/untyped-plutus-core/test/Flat/Spec.hs
Labels: bug

#5882 Add some text about how to deal with bad CHaP timestamps in RELEASE.adoc
  RELEASE.adoc
Labels: No Changelog Required

#5876 Refer to && and || by their qualified TH names.
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Plugin/Coverage/9.6/coverageCode.pir.golden
  plutus-tx/src/PlutusTx/Bool.hs
Labels: No Changelog Required

#5875 Remove plutus-metatheory from plutus-benchmark-common
  plutus-benchmark/agda-common/PlutusBenchmark/Agda/Common.hs
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/cek-calibration/Main.hs
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Lookup/Compiled.hs
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/GhcSort.hs
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/InsertionSort.hs
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/MergeSort.hs
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sort/QuickSort.hs
  plutus-benchmark/lists/src/PlutusBenchmark/Lists/Sum/Compiled.hs
  plutus-benchmark/marlowe/bench/BenchAgdaCek.hs
  plutus-benchmark/nofib/bench/BenchAgdaCek.hs
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Clausify.hs
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Knights.hs
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/LastPiece.hs
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Prime.hs
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Queens.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-benchmark/script-contexts/src/PlutusBenchmark/ScriptContexts.hs
  plutus-benchmark/validation/bench/BenchAgdaCek.hs
Labels: Benchmarks, No Changelog Required

#5881 Add some tests that non-canonically encoded bytestrings decode correctly
  plutus-core/plutus-core.cabal
  plutus-core/untyped-plutus-core/test/Flat/Spec.hs
Labels: No Changelog Required

#5890 Refactor NoTrace spec
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/test/Plugin/NoTrace/9.6/trace.pir.golden
  plutus-tx-plugin/test/Plugin/NoTrace/9.6/traceComplex.pir.golden
  plutus-tx-plugin/test/Plugin/NoTrace/9.6/traceDirect.eval.golden
  plutus-tx-plugin/test/Plugin/NoTrace/9.6/tracePrelude.eval.golden
  plutus-tx-plugin/test/Plugin/NoTrace/9.6/traceRepeatedly.eval.golden
  plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithTraces.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithoutTraces.hs
Labels: No Changelog Required

#5874 How to handle builtins before they're costed (PLT-9686)
  plutus-core/cost-model/CostModelGeneration.md
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/test/CostModelSafety/Spec.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/CekMachineCosts.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
Labels: Builtins, Costing, No Changelog Required

#5857 Read model type from R (attempt number 2) [PLT-1174]
  plutus-core/changelog.d/20240326_184114_kenneth.mackenzie_read_model_type_from_R_2.md
  plutus-core/cost-model/budgeting-bench/Benchmarks/Strings.hs
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/create-cost-model/Main.hs
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/print-cost-model/Main.hs
  plutus-core/cost-model/test/TH.hs
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-metatheory/src/Cost/Model.lagda.md
  plutus-metatheory/src/Cost/Raw.lagda.md
Labels: Costing

#5897 Don't call `mustBeReplaced` in PlutusTx.Builtins.Internal
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Utils.hs
Labels: No Changelog Required

#5900 Add some more complex test cases for the remove-trace plugin option
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/test/Plugin/NoTrace/Lib.hs
  plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithTraces.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithoutTraces.hs
Labels: No Changelog Required

#5905 Update some more benchmarks to use correct evaluation context (PLT-9713) [fourth attempt]
  plutus-benchmark/bls12-381-costs/bench/Bench.hs
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/bls12-381-costs/test/9.6/bls12-381-costs.golden
  plutus-benchmark/cek-calibration/Main.hs
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/marlowe/bench/BenchCek.hs
  plutus-benchmark/plutus-benchmark.cabal
Labels: Benchmarks, No Changelog Required

#5907 Trace removal re-implemented as a IR rewrite rule
  plutus-core/plutus-core.cabal
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules/Internal.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules/RemoveTrace.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules/Rules.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Plugin/NoTrace/Lib.hs
  plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithTraces.hs
  plutus-tx-plugin/test/Plugin/NoTrace/WithoutTraces.hs
Labels: No Changelog Required

#5911 Kwxm/plc spec/bitwise conversions
  doc/plutus-core-spec/builtins.tex
  doc/plutus-core-spec/cardano/builtins4.tex
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: Specification, Docs, No Changelog Required

#5912 Change CMTooFewParamsError to a warning
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostModelInterface.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/ParamName.hs
  plutus-ledger-api/test/Spec.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/Examples.hs
Labels: No Changelog Required

#5851 [Costing] Provide support for multiple 'CostModel's
  plutus-benchmark/bls12-381-costs/bench/Bench.hs
  plutus-benchmark/cek-calibration/Main.hs
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/lists/bench/Bench.hs
  plutus-benchmark/marlowe/bench/BenchCek.hs
  plutus-benchmark/nofib/bench/BenchCek.hs
  plutus-benchmark/plutus-benchmark.cabal
  plutus-benchmark/validation/bench/BenchCek.hs
  plutus-benchmark/validation/bench/BenchFull.hs
  plutus-conformance/haskell/Spec.hs
  plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters/Default.hs
  plutus-core/testlib/PlutusIR/Pass/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/SignatureVerification.hs
  plutus-ledger-api/changelog.d/20240425_183853_effectfully_both_MajorProtocolVersion_and_multiple_CostModels.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
  plutus-ledger-api/test/Spec.hs
  plutus-ledger-api/test/Spec/Eval.hs
  plutus-ledger-api/test/Spec/NoThunks.hs
Labels: Builtins, Costing

#5923 CaseOfCase kind mismatch error fix
  plutus-core/plutus-core.cabal
  plutus-core/plutus-ir/src/PlutusIR/Contexts.hs
  plutus-core/plutus-ir/test/PlutusIR/Contexts/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/CaseOfCase/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/CaseOfCase/twoTyArgs
  plutus-core/plutus-ir/test/PlutusIR/Transform/CaseOfCase/twoTyArgs.golden
Labels: No Changelog Required

#5930 Fix some Notes so they pass the check
  plutus-tx-plugin/test/Plugin/NoTrace/Spec.hs
  plutus-tx/src/PlutusTx/Blueprint/Contract.hs
  plutus-tx/src/PlutusTx/Blueprint/Definition/Unroll.hs
  scripts/check-Notes.awk
Labels: No Changelog Required

#5932 Kwxm/costing/restore old cost model param names
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/builtinCostModel.json
  plutus-core/cost-model/data/models.R
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
  plutus-core/plutus-core/test/CostModelInterface/defaultCostModelParams.json
  plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
Labels: Ledger, Costing, No Changelog Required

#5936 Tidy up SimpleJSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
Labels: Costing, No Changelog Required

#5937 Chore: formatting
  plutus-tx-plugin/test/AsData/Budget/Spec.hs
  plutus-tx-plugin/test/Plugin/Basic/Spec.hs
Labels: No Changelog Required

#5938 1.27.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240421_114005_bezirg_exe_combined.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20240421_114811_bezirg_exe_combined.md
  plutus-ledger-api/changelog.d/20240423_155246_unsafeFixIO_int64.md
  plutus-ledger-api/changelog.d/20240425_183853_effectfully_both_MajorProtocolVersion_and_multiple_CostModels.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20240421_114911_bezirg_exe_combined.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5940 Do not build the plutus executable if GHC <9.6
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
Labels: No Changelog Required
