Repository IntersectMBO/plutus, pull requests merged in 2024-02, with the labels that each got.

#5756 PLT-9238 Export Simple JSON model from plutus-core
  plutus-core/cost-model/print-cost-model/Main.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/SimpleBuiltinCostModel.hs
  plutus-metatheory/data/builtinCostModel.json
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Builtin/Signature.lagda.md
  plutus-metatheory/src/Cost/Raw.lagda.md
  plutus-metatheory/src/Opts.hs
Labels: No Changelog Required

#5755 Kwxm/uplc-criterion
  plutus-core/executables/plc/Main.hs
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
  plutus-core/executables/uplc/Main.hs
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#5763 [Bug] [TypeCheck] Fix an off-by-maxBound error
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-core/test/type-errors/constrTooFew.plc
  plutus-core/plutus-core/test/type-errors/constrTooFew.plc.golden
  plutus-core/plutus-core/test/type-errors/constrTooMany.plc
  plutus-core/plutus-core/test/type-errors/constrTooMany.plc.golden
  plutus-core/prelude/PlutusPrelude.hs
Labels: bug, Type checking, No Changelog Required

#5767 Add Note [Short-circuit evaluation for `&&` and `||`]
  plutus-tx/src/PlutusTx/Bool.hs
Labels: No Changelog Required

#5773 Kwxm/agda conformance/better cost model (PLT-9449)
  plutus-conformance/agda/Spec.hs
  plutus-conformance/haskell/Spec.hs
  plutus-conformance/plutus-conformance.cabal
  plutus-conformance/src/PlutusConformance/Common.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/SimpleBuiltinCostModel.hs
Labels: Test, Metatheory, No Changelog Required

#5783 Remove ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: No Changelog Required

#5780 Add Note [Optimising Value]
  plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
  plutus-tx/src/PlutusTx/AssocMap.hs
Labels: No Changelog Required

#5785 Changes needed for constitution
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/Data/Aeson/THReader.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
  plutus-core/prelude/PlutusPrelude.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/CekMachineCosts.hs
  plutus-tx/src/PlutusTx/AssocMap.hs
Labels: No Changelog Required

#5789 Remove unnecessary for a library ghc options
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#5786 Add note on constant inlining
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Utils.hs
Labels: No Changelog Required

#5790 Add constant inlining to UPLC
  plutus-benchmark/nofib/test/9.6/clausify-F5.budget.golden
  plutus-benchmark/nofib/test/9.6/clausify-F5.size.golden
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Simplify.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
  plutus-core/untyped-plutus-core/test/Transform/floatDelay1.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/floatDelay3.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/inlinePure3.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/interveningLambda.uplc.golden
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
Labels: No Changelog Required

#5791 Document some variants for Plutus V3 ScriptContext
  plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
Labels: No Changelog Required

#5793 [Release] 1.22.0.0
  doc/read-the-docs-site/plutus-doc.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20240119_113221_kenneth.mackenzie_bitwise_costing.md
  plutus-core/plutus-core.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20240119_113712_kenneth.mackenzie_bitwise_costing.md
  plutus-ledger-api/changelog.d/20240202_125923_Yuriy.Lazaryev_PLT_9420_TxId_constructor.md
  plutus-ledger-api/changelog.d/20240218_090310_unsafeFixIO_currencySymbolValueOf.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20240119_114204_kenneth.mackenzie_bitwise_costing.md
  plutus-tx-plugin/changelog.d/20240213_184621_ana.pantilie95_plt_8176_inline_constants_pir.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20240119_114032_kenneth.mackenzie_bitwise_costing.md
  plutus-tx/changelog.d/20240201_123929_Yuriy.Lazaryev_PLT_9395_ratio_negative_denominator.md
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5795 JF/PLT-9460 Simple example caution message
  doc/read-the-docs-site/simple-example.rst
Labels: No Changelog Required

#5798 fix: haddock parse error in GHC 8.10
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Labels: No Changelog Required

#5784 Fix the Notes (PLT-9513)
  plutus-benchmark/common/PlutusBenchmark/Common.hs
  plutus-benchmark/nofib/src/PlutusBenchmark/NoFib/Knights/ChessSetList.hs
  plutus-benchmark/script-contexts/src/PlutusBenchmark/ScriptContexts.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Strings.hs
  plutus-core/executables/debugger/Main.hs
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/executables/traceToStacks/Main.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Data/InterList.hs
  plutus-core/plutus-core/src/PlutusCore/Bitwise/Convert.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Elaborate.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Eq.hs
  plutus-core/plutus-core/src/PlutusCore/Crypto/BLS12_381/G1.hs
  plutus-core/plutus-core/src/PlutusCore/Data.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/MachineParameters.hs
  plutus-core/plutus-core/src/PlutusCore/Flat.hs
  plutus-core/plutus-core/src/PlutusCore/Normalize/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Type.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Recursion.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Flat.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Pretty.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/CallSiteInline.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/Inline.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RecSplit.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules/UnConstrConstrData.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/AST.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Check/Scope.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Flat.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/DeBruijn.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/SerialisedScript.hs
  plutus-ledger-api/test/Spec/Eval.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
  plutus-tx-plugin/test/IntegerLiterals/NoStrict/NegativeLiterals/Spec.hs
  plutus-tx-plugin/test/IntegerLiterals/NoStrict/NoNegativeLiterals/Spec.hs
  plutus-tx-plugin/test/IntegerLiterals/Strict/NegativeLiterals/Spec.hs
  plutus-tx-plugin/test/IntegerLiterals/Strict/NoNegativeLiterals/Spec.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Lift/TH.hs
  plutus-tx/src/PlutusTx/Ratio.hs
  plutus-tx/src/PlutusTx/TH.hs
  scripts/check-Notes.awk
  scripts/check-Notes.sh
  scripts/list-Notes.awk
  scripts/list-Notes.sh
  stubs/plutus-ghc-stub/src/StubTypes.hs
Labels: Docs, No Changelog Required

#5800 fix: another haddock parse error in GHC 8.10
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Labels: No Changelog Required

#5797 [Generators] Fix 'LamAbs' handling in 'fixupTerm_'
  plutus-core/testlib/PlutusIR/Generators/QuickCheck/ShrinkTerms.hs
Labels: bug, Generators

#5794 Some docs on AssocMap
  plutus-tx/src/PlutusTx/AssocMap.hs
Labels: No Changelog Required

#5801 Fixing typo in new caution message - simple-example.rst
  doc/read-the-docs-site/simple-example.rst
Labels: No Changelog Required

#5804 PlutusLedgerApi.V3.TxInInfo
  plutus-ledger-api/src/PlutusLedgerApi/V3.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs
Labels: No Changelog Required

#5805 1.22.0.0 -> 1.22.1.0
  plutus-core/plutus-core.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/plutus-tx.cabal
  prettyprinter-configurable/prettyprinter-configurable.cabal
Labels: No Changelog Required

#5810 Update Plutus quick start guide, mention iogx template
  doc/read-the-docs-site/quick-start.rst
Labels: No Changelog Required

#5792 Sort out the comments on the ExMemoryUsage instance for ByteString
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
Labels: Docs, Costing, No Changelog Required
