Repository IntersectMBO/plutus, pull requests merged in 2025-07, with the labels that each got.

#7171 Tool to dump cost model parameters in order expected by ledger
  plutus-ledger-api/exe/dump-cost-model-parameters/Main.hs
  plutus-ledger-api/exe/dump-cost-model-parameters/Parsers.hs
  plutus-ledger-api/plutus-ledger-api.cabal
Labels: Costing, No Changelog Required, Plutus Ledger API

#7176 Add a note for `flattenValue`
  plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs
Labels: Documentation, No Changelog Required

#7181 Replace `hex-text` with `base16-bytestring` package
  cabal.project
  plutus-core/changelog.d/20250703_123351_erikd_drop_hex_text.md
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/test/CBOR/DataStability.hs
Labels: dependencies

#7184 Remove some placeholder comments
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
Labels: Costing, No Changelog Required

#7185 Fix broken Docusaurus preview links
  .github/workflows/docusaurus-site.yml
  doc/docusaurus/docusaurus.config.ts
Labels: No Changelog Required

#7199 [Builtins] Remove vestiges of 'caseData'
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
  plutus-benchmark/bitwise/test/9.6/Ed25519.uplc.golden
  plutus-benchmark/ed25519-costs/test/9.6/ed25519-costs.golden
  plutus-benchmark/lists/test/Sum/9.6/left-fold-data.eval.golden
  plutus-benchmark/lists/test/Sum/9.6/right-fold-data.eval.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.eval.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.pir.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.uplc.golden
  plutus-core/plutus-core/examples/PlutusCore/Examples/Data/Data.hs
  plutus-core/plutus-core/examples/PlutusCore/Examples/Everything.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/Data.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Everything.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/headEmpty.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/headOk.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/lastEmpty.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/lastEmpty.uplc.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/lastOk.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/lastOk.uplc.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/tailEmpty.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/tailOk.pir.golden
  plutus-tx-plugin/test/IsData/9.6/deconstructData.pir.golden
  plutus-tx-plugin/test/Plugin/Primitives/9.6/deconstructorData2.pir.golden
  plutus-tx-plugin/test/size/Golden/Rational/Serialization/fromBuiltinData.size.golden
  plutus-tx/src/PlutusTx/AssocMap.hs
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Data/List.hs
  plutus-tx/src/PlutusTx/IsData/Class.hs
Labels: Builtins, No Changelog Required

#7211 [Builtins] Remove 'HeadSpine' from 'BuiltinRuntime'
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/stdlib/PlutusCore/StdLib/Data/List.hs
  plutus-core/plutus-core/test/Evaluation/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/EvaluateBuiltins.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Test.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypedBuiltinGen.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/MakeRead.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Machines.hs
Labels: Builtins, No Changelog Required

#7216 fix: incorrectly named golden file
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/concat_operator.eval.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/concat_operator.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/concat_operator.uplc.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/cons_operator.eval.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/cons_operator.pir.golden
  plutus-tx-plugin/test/BuiltinList/Budget/9.6/cons_operator.uplc.golden
  plutus-tx-plugin/test/BuiltinList/Budget/Spec.hs
Labels: No Changelog Required

#7182 QuickCheck-2.16 support
  cabal.project
  doc/plutus-report/plutus.tex
  flake.lock
  nix/project.nix
  nix/shell.nix
  plutus-benchmark/cardano-loans/test/9.6/main.eval.golden
  plutus-benchmark/cardano-loans/test/9.6/main.pir.golden
  plutus-benchmark/cardano-loans/test/9.6/main.uplc.golden
  plutus-benchmark/linear-vesting/test/9.6/main.eval.golden
  plutus-benchmark/linear-vesting/test/9.6/main.pir.golden
  plutus-benchmark/linear-vesting/test/9.6/main.uplc.golden
  plutus-core/plutus-core.cabal
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/Builtin.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Costing.hs
Labels: No Changelog Required

#7222 Autodelete latest haddock build on new deployments
  .github/workflows/haddock-site.yml
Labels: No Changelog Required

#7218 More tests, conformance test cases for builtin integer, bool, list casing
  plutus-conformance/agda/Spec.hs
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-01/bool-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-01/bool-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-01/bool-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-02/bool-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-02/bool-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-02/bool-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-03/bool-03.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-03/bool-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-03/bool-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-04/bool-04.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-04/bool-04.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-04/bool-04.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-05/bool-05.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-05/bool-05.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-05/bool-05.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-06/bool-06.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-06/bool-06.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-06/bool-06.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-07/bool-07.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-07/bool-07.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/bool/bool-07/bool-07.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-01/integer-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-01/integer-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-01/integer-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-02/integer-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-02/integer-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-02/integer-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-03/integer-03.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-03/integer-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-03/integer-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-04/integer-04.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-04/integer-04.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/integer/integer-04/integer-04.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-01/list-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-01/list-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-01/list-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-02/list-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-02/list-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-02/list-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-03/list-03.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-03/list-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-03/list-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-04/list-04.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-04/list-04.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-04/list-04.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-05/list-05.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-05/list-05.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-05/list-05.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-06/list-06.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-06/list-06.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-06/list-06.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-07/list-07.uplc
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-07/list-07.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constant-case/list/list-07/list-07.uplc.expected
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
Labels: Test, No Changelog Required

#7223 Enable SoPs and all builtins in PlutusV1/V2 at PV11.
  plutus-ledger-api/changelog.d/20250718_072102_kenneth.mackenzie_enable_all_builtins_2.md
  plutus-ledger-api/src/PlutusLedgerApi/Common.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Eval.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/ProtocolVersions.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/MachineParameters.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/EvaluationContext.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/test/Spec/Data/CostModelParams.hs
  plutus-ledger-api/test/Spec/Data/Eval.hs
  plutus-ledger-api/test/Spec/Data/Versions.hs
  plutus-ledger-api/test/Spec/Eval.hs
  plutus-ledger-api/test/Spec/Versions.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Labels: Plutus Core, Builtins, Costing, Plutus Ledger API

#7234 Bump on-headers to 1.1.0 in doc/docusaurus/package.json
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#7236 Allow 'turtle' package to use a new version of 'optparse-applicative'
  cabal.project
Labels: No Changelog Required

#7240 Invert some error messages in plutus-ledger-api tests
  plutus-ledger-api/test/Spec/Versions.hs
Labels: Test, No Changelog Required, Plutus Ledger API

#7244 Update Values.md
  plutus-ledger-api/exe/analyse-script-events/Values.md
Labels: Documentation, No Changelog Required

#7245 Renumber multisig-sm validation scripts
  plutus-benchmark/validation/data/multisig-sm-01.flat
  plutus-benchmark/validation/data/multisig-sm-02.flat
  plutus-benchmark/validation/data/multisig-sm-03.flat
  plutus-benchmark/validation/data/multisig-sm-04.flat
  plutus-benchmark/validation/data/multisig-sm-05.flat
  plutus-benchmark/validation/data/multisig-sm-06.flat
  plutus-benchmark/validation/data/multisig-sm-07.flat
  plutus-benchmark/validation/data/multisig-sm-08.flat
  plutus-benchmark/validation/data/multisig-sm-09.flat
Labels: Benchmarks, No Changelog Required

#7251 Fix #7248
  .github/workflows/compare-golden-budgets.yaml
Labels: No Changelog Required
