Repository IntersectMBO/plutus, pull requests merged in 2025-01, with the labels that each got.

#6771 Fix an error related to mesh wallet
  doc/docusaurus/static/code/generate-keys.mjs
  doc/docusaurus/static/code/mint-token-for-auction.mjs
Labels: No Changelog Required

#6767 Use ignoreTest instead of expectFail in conformance tests
  plutus-conformance/src/PlutusConformance/Common.hs
Labels: bug, Test, No Changelog Required

#6759 Add docs on data-backed ScriptContext
  doc/docusaurus/docs/working-with-scripts/optimizing-scripts-with-asData.md
Labels: No Changelog Required

#6774 Fix a couple of small typos
  doc/plutus-core-spec/cardano/builtins1.tex
Labels: Specification, No Changelog Required

#5265 [Evaluation] Statically unroll 'itraverseCounter_'
  plutus-core/changelog.d/20241126_025636_effectfully_statically_unroll_itraverseCounter_.md
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/StepCounter.hs
Labels: Evaluation, Performance

#6775 Kwxm/specification/fix div rem txt
  doc/plutus-core-spec/cardano/builtins1.tex
Labels: Specification, No Changelog Required

#6781 Disable .js file minification in docusaurus build
  doc/docusaurus/package.json
Labels: No Changelog Required

#6743 docusaurus: plutus exe
  doc/docusaurus/docs/using-plutus-tx/cli-plutus.md
  doc/docusaurus/static/img/tui_debugger_screenshot.png
  plutus-core/executables/plutus/AnyProgram/IO.hs
  plutus-core/executables/plutus/GetOpt.hs
  plutus-core/executables/plutus/Mode/Compile.hs
  plutus-core/executables/plutus/Mode/HelpVersion.hs
Labels: Documentation, No Changelog Required

#6753 plutus exe: Also run a final check after the programs are applied tog…
  plutus-core/executables/plutus/AnyProgram/Compile.hs
  plutus-core/executables/plutus/Mode/Compile.hs
Labels: No Changelog Required

#6785 Regenerate constitution golden tests
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/GoldenTests/unsorted.uplc.golden
Labels: No Changelog Required

#6784 Data backed constitution script
  cardano-constitution/cardano-constitution.cabal
  cardano-constitution/src/Cardano/Constitution/Data/Validator.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Data/Common.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Data/Sorted.hs
  cardano-constitution/src/Cardano/Constitution/Validator/Data/Unsorted.hs
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/PropTests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/Data/TestsCommon.hs
  cardano-constitution/test/Cardano/Constitution/Validator/Data/UnitTests.hs
  cardano-constitution/test/Driver.hs
  plutus-ledger-api/src/PlutusLedgerApi/Data/V3.hs
Labels: No Changelog Required

#6796 Add new user guide page "Simplifying Code Before Compilation"
  doc/docusaurus/docs/working-with-scripts/simplifying-before-compilation.md
Labels: No Changelog Required

#6773 [UPLC] [Test] Add scoping tests
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Check/Scoping.hs
  plutus-core/plutus-core/src/PlutusCore/Core/Instance/Scoping.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Instance/Scoping.hs
  plutus-core/plutus-ir/test/PlutusIR/Scoping/Tests.hs
  plutus-core/prelude/PlutusPrelude.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Instance/Scoping.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Rename/Internal.hs
  plutus-core/untyped-plutus-core/test/Generators.hs
  plutus-core/untyped-plutus-core/test/Scoping/Spec.hs
  plutus-core/untyped-plutus-core/test/Spec.hs
Labels: Test, Name handling, Untyped Plutus Core, No Changelog Required

#6799 Finalize switch from cryptonite to crypton
  cabal.project
  doc/notes/model/UTxO.hsproj/UTxO.cabal
  flake.lock
  plutus-core/plutus-core.cabal
  plutus-metatheory/plutus-metatheory.cabal
Labels: No Changelog Required

#6791 conformance: Add budgeting for haskell steppable
  plutus-conformance/haskell-steppable/Spec.hs
  plutus-conformance/plutus-conformance.cabal
Labels: No Changelog Required

#6802 Add some golden tests on data-backed ScriptContext
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-ledger-api/test-plugin/Spec.hs
  plutus-ledger-api/test-plugin/Spec/Data/ScriptContext.hs
  plutus-ledger-api/test-plugin/Spec/Data/SriptContext/9.6/alwaysSucceeds.pir.golden
  plutus-ledger-api/test-plugin/Spec/Data/SriptContext/9.6/alwaysSucceeds.uplc.golden
  plutus-ledger-api/test-plugin/Spec/Data/SriptContext/9.6/succeedsIfHasDatum.pir.golden
  plutus-ledger-api/test-plugin/Spec/Data/SriptContext/9.6/succeedsIfHasDatum.uplc.golden
Labels: No Changelog Required

#6798 [Evaluation] Autocompute 'NumberOfStepCounters'
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Machines/NumberOfStepCounters.golden
  plutus-core/untyped-plutus-core/test/Spec.hs
Labels: Test, Evaluation, No Changelog Required

#6805 Update CIP-57 example to use AssocMap
  doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
  doc/docusaurus/static/plutus.json
Labels: No Changelog Required

#6811 Add nix/README.md
  nix/README.md
Labels: No Changelog Required

#6810 Bump katex version in docusaurus/package.json
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#6800 [Test] Add 'fix id'
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudget.hs
  plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Labels: Test, Evaluation, No Changelog Required

#6748 Add scripts/interactive-release.sh for automated releases
  .github/workflows/broken-links.yml
  .github/workflows/cabal-build-all.yml
  .github/workflows/cardano-constitution-tests.yml
  .github/workflows/changelog-label.yml
  .github/workflows/cost-model-benchmark.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/longitudinal-benchmark.yml
  .github/workflows/manual-benchmark.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/nightly-testsuite.yml
  .github/workflows/papers-and-specs.yml
  .github/workflows/plutus-tx-template.yml
  .github/workflows/slack-message-broker.yml
  .github/workflows/sprint-issues-rollover.yml
  .gitignore
  RELEASE.adoc
  nix/shell.nix
  scripts/assemble-changelog.sh
  scripts/interactive-release.sh
  scripts/prepare-bins.sh
  scripts/prepare-release.sh
  scripts/s3-sync-unzip.sh
  scripts/update-version.sh
Labels: No Changelog Required
