Repository IntersectMBO/plutus, pull requests merged in 2025-03, with the labels that each got.

#6889 Resolve dompurfy to version 3.2.4
  doc/docusaurus/package.json
Labels: No Changelog Required

#6891 Update docusaurus/yarn.lock
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#6893 Remove of irrefutable patterns makes script cheaper to evaluate.
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-budget-manual.budget.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.pir.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.uplc.golden
  plutus-tx-plugin/test/AsData/Budget/Types.hs
Labels: No Changelog Required

#6746 Ramsay t/translation efficiency 2
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-executables/changelog.d/20250222_080216_ramsay.taylor_translation_efficiency_2.rst
  plutus-executables/plutus-executables.cabal
  plutus-executables/src/AgdaUnparse.hs
  plutus-executables/test/certifier/Golden/inc.golden
  plutus-executables/test/certifier/Golden/len.golden
  plutus-executables/test/certifier/Spec.hs
  plutus-executables/test/certifier/UPLC/inc.uplc
  plutus-executables/test/certifier/UPLC/len.uplc
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/VerifiedCompilation/UForceDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UntypedTranslation.lagda.md
Labels: Metatheory

#6900 Release 1.42.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20241023_153400_cryptonite.md
  plutus-core/changelog.d/20250128_170723_unsafeFixIO_circuit.md
  plutus-core/changelog.d/20250203_144259_ramsay.taylor_add_dropList_2.md
  plutus-core/changelog.d/20250207_120412_Yuriy.Lazaryev_cip_0138_builtin_array.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20250130_1148_erikd_typeable.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20250130_190605_unsafeFixIO_preserve.md
  plutus-tx-plugin/changelog.d/20250212_132802_unsafeFixIO_inline__fix.md
  plutus-tx-plugin/changelog.d/20250228_083744_unsafeFixIO_inline_pragma_local.md
  plutus-tx-plugin/changelog.d/20250301_143559_unsafeFixIO_safe.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20250130_1148_erikd_typeable.md
  plutus-tx/changelog.d/20250206_144045_unsafeFixIO_fix.md
  plutus-tx/changelog.d/20250211_131033_unsafeFixIO_peel.md
  plutus-tx/changelog.d/20250211_170605_unsafeFixIO_null.md
  plutus-tx/changelog.d/20250213_105641_unsafeFixIO_magic_inline.md
  plutus-tx/changelog.d/20250226_231916_ana.pantilie95_complete_data_list.md
  plutus-tx/changelog.d/20250227_111229_unsafeFixIO_inline_local.md
  plutus-tx/changelog.d/20250303_201434_ana.pantilie95_asdata_remove_idx_check.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#6906 Delete garnix.yaml
  garnix.yaml
Labels: No Changelog Required

#6907 Remove cardano-constitution and plutus-executables from CHaP release
  scripts/interactive-release.sh
Labels: No Changelog Required

#6902 Remove plugin support for GHC < 9.6
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Kind.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
Labels: No Changelog Required, Plinth Plugin

#6924 Fix typo on term flat decoder for builtin term
  doc/plutus-core-spec/flat-serialisation.tex
Labels: Specification, No Changelog Required

#6930 Improvements to Haddock documentation in docusaurus website
  .gitignore
  doc/docusaurus/docs/delve-deeper/_category_.json
  doc/docusaurus/docs/delve-deeper/haddock-documentation.md
  doc/docusaurus/docs/delve-deeper/plinth-compiler-options.md
  doc/docusaurus/docs/haddock-documentation.md
  plutus-tx-plugin/app/GeneratePluginOptionsDoc.hs
Labels: No Changelog Required

#6935 Delete `plutus-metatheory/src/MAlonzo.Code.VerifiedCompilation.html` from generated haddock
  scripts/combined-haddock.sh
Labels: No Changelog Required

#6926 Reorganise bitwise tests a bit
  plutus-core/plutus-core.cabal
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise/CIP0122.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Bitwise/CIP0123.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Labels: Test, Builtins, No Changelog Required

#6928 Update costing instructions
  plutus-core/cost-model/CostModelGeneration.md
Labels: Documentation, Costing, No Changelog Required

#6938 Fix PrismJS DOM Clobbering Vulnerability
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#6927 Tests for `expModInteger` with modulus 1
  plutus-core/plutus-core/src/PlutusCore/Crypto/ExpMod.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
Labels: Test, Builtins, No Changelog Required

#6941 Make `generate-cost-model` work
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching-conway.csv
  plutus-core/cost-model/data/models.R
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
Labels: Builtins, Costing, No Changelog Required

#6939 Certifier: add the decision procedure for caseReduce into the certifier
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseReduce.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UInline.lagda.md
Labels: No Changelog Required

#6942 [Textual] Replace 'Simple' with 'Classic'
  plutus-core/executables/src/PlutusCore/Executable/Parsers.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
  plutus-core/plutus-core/test/TypeSynthesis/Golden/CaseData.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/CaseList.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/DropList.plc.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/DefaultFun/LengthOfArray.plc.golden
Labels: Textual representation, Plutus Exe, No Changelog Required

#6922 Run the cardano-constitution tests on each PR
  .github/workflows/cardano-constitution-tests.yml
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.pir.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/PropTests.hs
  cardano-constitution/test/Cardano/Constitution/Validator/PropTests.hs
  cardano-constitution/test/Driver.hs
  cardano-constitution/test/Helpers/MultiParam.hs
  cardano-constitution/test/Helpers/Spec/IntervalSpec.hs
  cardano-constitution/test/Helpers/TestBuilders.hs
  nix/project.nix
Labels: No Changelog Required

#6954 Fix dependabot alert 41,42,43
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#6948 Remove parameter names for array-related builtin functions
  plutus-ledger-api/CostModel/Data/Params/CostModelParams/costModelParamNames.txt.golden
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/test/Spec/CostModelParams.hs
  plutus-ledger-api/test/Spec/Data/CostModelParams.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Labels: No Changelog Required

#6953 Fix incomplete case pattern warning in plutus-metatheory/src/Raw.hs
  nix/project.nix
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Raw.hs
  plutus-metatheory/src/RawU.lagda.md
Labels: No Changelog Required

#6960 Replace tj-actions/changed-files with steo-security/changed-files in check-changelog.yml
  .github/workflows/changelog-label.yml
Labels: No Changelog Required

#6955 [Build] Add '-Werror' and make it work in GHC-8.10
  .github/workflows/cabal-build-all.yml
  nix/project.nix
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/plutus-ir/src/PlutusIR/Pass.hs
  plutus-core/plutus-ir/test/PlutusIR/Compiler/Let/Tests.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Contexts.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Tx.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/Data/Contexts.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/Data/Tx.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/Data/Contexts.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/Data/Tx.hs
  plutus-metatheory/Setup.hs
  plutus-tx-plugin/test/Plugin/Data/Spec.hs
  plutus-tx-plugin/test/Plugin/Laziness/Spec.hs
  plutus-tx-plugin/test/Plugin/Typeclasses/Spec.hs
  plutus-tx/src/PlutusTx/Bool.hs
  plutus-tx/src/PlutusTx/Builtins/HasBuiltin.hs
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
  plutus-tx/src/PlutusTx/Function.hs
  plutus-tx/src/PlutusTx/Optimize/Inline.hs
  plutus-tx/src/PlutusTx/Plugin/Utils.hs
Labels: Build, No Changelog Required

#6949 Make the Git revision available to pir/uplc/plc programs
  .gitignore
  nix/outputs.nix
  nix/project.nix
  nix/shell.nix
  nix/utils.nix
  plutus-core/executables/plutus/Mode/HelpVersion.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/Data/Version/Extras.hs
  plutus-core/plutus-core/src/Development/GitRev/Extras.hs
  plutus-executables/executables/pir/Main.hs
  plutus-executables/executables/plc/Main.hs
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/plutus-executables.cabal
Labels: No Changelog Required

#6962 Release 1.43.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/plutus-core.cabal
  plutus-executables/CHANGELOG.rst
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20250310_155927_ana.pantilie95_asdata_mintvalue.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20250304_163950_ana.pantilie95_more_datalist_functions.md
  plutus-tx/changelog.d/20250310_160119_ana.pantilie95_asdata_mintvalue.md
  plutus-tx/changelog.d/20250313_171040_ana.pantilie95_add_more_datamap_functions.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#6895 Add `caseData` and `caseList` to PLC specification
  doc/plutus-core-spec/builtins.tex
  doc/plutus-core-spec/cardano/builtins1.tex
  doc/plutus-core-spec/cardano/builtins5.tex
  doc/plutus-core-spec/cardano/builtins6.tex
  doc/plutus-core-spec/cardano/versions.tex
  doc/plutus-core-spec/data-cbor.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/notation.tex
  doc/plutus-core-spec/plutus-core-specification.tex
  doc/plutus-core-spec/untyped-cek-machine.tex
  doc/plutus-core-spec/untyped-reduction.tex
  doc/plutus-core-spec/untyped-values.tex
Labels: Specification, Builtins, No Changelog Required

#6966 chore: fourmolu
  plutus-core/untyped-plutus-core/test/Analysis/Spec.hs
Labels: No Changelog Required

#6968 Fix haddock docstring in Data.Version.Extras.hs
  plutus-core/plutus-core/src/Data/Version/Extras.hs
Labels: No Changelog Required

#6967 Add option to include the ghc version in manual-benchmark.yml
  .github/workflows/manual-benchmark.yml
Labels: No Changelog Required

#6969 Update specification date
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: Specification, No Changelog Required

#6972 Add plutus exec to release artifacts
  scripts/interactive-release.sh
Labels: No Changelog Required

#6976 Add windows builds to CI
  nix/outputs.nix
Labels: No Changelog Required

#6957 Agda decision tracing
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/src/AgdaUnparse.hs
  plutus-executables/test/certifier/Spec.hs
  plutus-metatheory/changelog.d/20250317_113127_ramsay.taylor_agda_decision_tracing.rst
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Untyped.lagda.md
  plutus-metatheory/src/Untyped/CEK.lagda.md
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/Certificate.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCSE.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseOfCase.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCaseReduce.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UFloatDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UForceDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UInline.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UntypedTranslation.lagda.md
Labels: Metatheory

#6959 Add ScriptContext test
  plutus-benchmark/plutus-benchmark.cabal
  plutus-benchmark/script-contexts/src/PlutusBenchmark/V2/Data/ScriptContexts.hs
  plutus-benchmark/script-contexts/src/PlutusBenchmark/V2/ScriptContexts.hs
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrick.budget.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrick.eval.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrick.pir.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrick.size.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrick.uplc.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.budget.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.eval.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.pir.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.size.golden
  plutus-benchmark/script-contexts/test/V2/9.6/dataFwdStakeTrickManual.uplc.golden
  plutus-benchmark/script-contexts/test/V2/9.6/sopFwdStakeTrick.budget.golden
  plutus-benchmark/script-contexts/test/V2/9.6/sopFwdStakeTrick.eval.golden
  plutus-benchmark/script-contexts/test/V2/9.6/sopFwdStakeTrick.pir.golden
  plutus-benchmark/script-contexts/test/V2/9.6/sopFwdStakeTrick.size.golden
  plutus-benchmark/script-contexts/test/V2/9.6/sopFwdStakeTrick.uplc.golden
  plutus-benchmark/script-contexts/test/V2/Spec.hs
Labels: No Changelog Required

#6981 Fix the incorrect lens in inline-fix
  plutus-tx-plugin/src/PlutusTx/Options.hs
Labels: No Changelog Required

#6990 Distribute and release plutus-metatheory as an Agda Library
  nix/metatheory-agda-library.nix
  nix/outputs.nix
  plutus-metatheory/AGDA.md
  plutus-metatheory/LICENSE.txt
  plutus-metatheory/Plutus.agda-lib
  plutus-metatheory/plutus-metatheory.cabal
  scripts/interactive-release.sh
Labels: No Changelog Required

#6995 Remove plinth-template.yml Workflow
  .github/workflows/plinth-template.yml
Labels: No Changelog Required

#6994 Confine recursion to inner functions in PlutusTx.List
  plutus-benchmark/bls12-381-costs/test/9.6/bls12-381-costs.golden
  plutus-benchmark/nofib/test/9.6/knights10-4x4.budget.golden
  plutus-benchmark/nofib/test/9.6/knights10-4x4.pir.golden
  plutus-benchmark/nofib/test/9.6/knights10-4x4.size.golden
  plutus-tx-plugin/test/Budget/9.6/show.budget.golden
  plutus-tx-plugin/test/Budget/9.6/show.pir.golden
  plutus-tx-plugin/test/Budget/9.6/show.uplc.golden
  plutus-tx/src/PlutusTx/List.hs
Labels: No Changelog Required

#6993 Some budget tests for PlutusTx.Data.List
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs
  plutus-tx-plugin/test/DataList/Budget/Spec.hs
  plutus-tx-plugin/test/List/Budget/9.6/any.budget.golden
  plutus-tx-plugin/test/List/Budget/9.6/any.eval.golden
  plutus-tx-plugin/test/List/Budget/9.6/any.pir.golden
  plutus-tx-plugin/test/List/Budget/9.6/any.uplc.golden
  plutus-tx-plugin/test/List/Budget/9.6/elem.budget.golden
  plutus-tx-plugin/test/List/Budget/9.6/elem.eval.golden
  plutus-tx-plugin/test/List/Budget/9.6/elem.pir.golden
  plutus-tx-plugin/test/List/Budget/9.6/elem.uplc.golden
  plutus-tx-plugin/test/List/Budget/9.6/filter.budget.golden
  plutus-tx-plugin/test/List/Budget/9.6/filter.eval.golden
  plutus-tx-plugin/test/List/Budget/9.6/filter.pir.golden
  plutus-tx-plugin/test/List/Budget/9.6/filter.uplc.golden
  plutus-tx-plugin/test/List/Budget/9.6/length.budget.golden
  plutus-tx-plugin/test/List/Budget/9.6/length.eval.golden
  plutus-tx-plugin/test/List/Budget/9.6/length.pir.golden
  plutus-tx-plugin/test/List/Budget/9.6/length.uplc.golden
  plutus-tx-plugin/test/List/Budget/9.6/makeList.budget.golden
  plutus-tx-plugin/test/List/Budget/9.6/makeList.eval.golden
  plutus-tx-plugin/test/List/Budget/9.6/makeList.pir.golden
  plutus-tx-plugin/test/List/Budget/9.6/makeList.uplc.golden
  plutus-tx-plugin/test/List/Budget/9.6/partition.budget.golden
  plutus-tx-plugin/test/List/Budget/9.6/partition.eval.golden
  plutus-tx-plugin/test/List/Budget/9.6/partition.pir.golden
  plutus-tx-plugin/test/List/Budget/9.6/partition.uplc.golden
  plutus-tx-plugin/test/Spec.hs
Labels: No Changelog Required

#6992 Add nil and singleton to PlutusTx.Data.List
  plutus-tx/src/PlutusTx/Data/List.hs
Labels: No Changelog Required

#6996 Restore `OPTIONS_GHC -fplugin PlutusTx.Plugin` in docusaurus-examples
  .github/workflows/cabal-build-all.yml
  doc/docusaurus/docusaurus-examples.cabal
  doc/docusaurus/static/code/AuctionMintingPolicy.hs
  doc/docusaurus/static/code/AuctionValidator.hs
  doc/docusaurus/static/code/Example/Cip57/Blueprint/Main.hs
  nix/project.nix
Labels: No Changelog Required
