Repository IntersectMBO/plutus, pull requests merged in 2025-10, with the labels that each got.

#7375 Enable the Agda conformance tests for the array builtins.
  plutus-conformance/agda/Spec.hs
Labels: Test, Builtins, Metatheory, No Changelog Required

#7092 Builtin Array example
  doc/docusaurus/docs/upcoming-features/_category_.json
  doc/docusaurus/docs/upcoming-features/builtin-arrays.md
  doc/docusaurus/docs/working-with-scripts/other-optimization-techniques.md
  doc/docusaurus/docusaurus-examples.cabal
  doc/docusaurus/static/code/Example/Builtin/Array/Main.hs
  doc/docusaurus/static/code/Example/Builtin/Array/Screenshot.png
Labels: No Changelog Required

#7378 Enable BLS12-381 MSM builtins at PV11
  plutus-ledger-api/changelog.d/20251002_130633_kenneth.mackenzie_enable_bls_msm.md
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
Labels: Builtins, Crypto, Plutus Ledger API
