Repository IntersectMBO/plutus, pull requests merged in 2025-06, with the labels that each got.

#7116 [Refactoring] Remove prismatic error handling from Ck/Cek machines
  plutus-core/cost-model/budgeting-bench/Benchmarks/Nops.hs
  plutus-core/docs/BuiltinsOverview.md
  plutus-core/plutus-core/examples/PlutusCore/Examples/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/HasConstant.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Crypto/Utils.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Result.hs
  plutus-core/plutus-core/test/TypeSynthesis/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Core/Type.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Interesting.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Core/Type.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-ledger-api/test-plugin/Spec/Data/Value.hs
  plutus-ledger-api/test-plugin/Spec/Value.hs
  plutus-tx/src/PlutusTx/Lift.hs
Labels: Refactoring, No Changelog Required

#7122 Publish `plutus-metatheory` on CHaP release
  scripts/interactive-release.sh
Labels: No Changelog Required

#7117 Rewrite PlutusLedgerApi.V3.Data.MintValue.filterQuantities
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed-4.eval.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed.pir.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed.size.golden
  plutus-ledger-api/src/PlutusLedgerApi/V3/Data/MintValue.hs
  plutus-ledger-api/test-plugin/Spec/Data/Budget.hs
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/mintValueBurned.eval.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/mintValueMinted.eval.golden
Labels: No Changelog Required

#7132 Bump webpack-dev-server to 5.2.1 in docusaurus website
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#7133 Apply the spec naming conventions to `plutus-core/untyped-plutus-core/testlib`
  plutus-core/plutus-core.cabal
  plutus-core/untyped-plutus-core/test/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Generators/Lib.hs
  plutus-core/untyped-plutus-core/testlib/Generators/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Scoping/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Transform/CaseOfCase/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Transform/Simplify/Spec.hs
  plutus-metatheory/test/certifier/Test/Certifier/Optimizer.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Plugin/Basic/Spec.hs
  plutus-tx/plutus-tx.cabal
  plutus-tx/src/PlutusTx/Lift.hs
  plutus-tx/testlib/PlutusTx/Test/Golden.hs
Labels: No Changelog Required

#7109 Amend documentation in Builtins.Internal about budgeting and invariants on Bytestring builtins
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: No Changelog Required

#7137 Release/1.47.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20250520_160112_effectfully_make__OperationalEvaluationError_work_in_the_machines.md
  plutus-core/changelog.d/20250521_140320_effectfully_cut_Evaluation_from_Structural_and_Operational.md
  plutus-core/changelog.d/20250530_195904_kenneth.mackenzie_deprecate_caseList_caseData.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/CHANGELOG.rst
  plutus-metatheory/changelog.d/20230420_135648_mjaskelioff_untypedbuiltins.rst
  plutus-metatheory/changelog.d/20240502_122129_ramsay.taylor_verified_compilation.rst
  plutus-metatheory/changelog.d/20241023_153400_cryptonite.md
  plutus-metatheory/changelog.d/20250317_113127_ramsay.taylor_agda_decision_tracing.rst
  plutus-metatheory/changelog.d/20250411_131306_ana.pantilie95_fix_certifier_builtin_deceq.rst
  plutus-metatheory/changelog.d/20250428_130712_ana.pantilie95_haskell_builtinEq.rst
  plutus-metatheory/changelog.d/20250502_184000_ana.pantilie95_certifier_plugin.rst
  plutus-metatheory/changelog.d/20250507_213709_ana.pantilie95_fix_some_agda_unparsing.rst
  plutus-metatheory/changelog.d/20250512_141822_ana.pantilie95_split_certificates_2.rst
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20250513_120055_ana.pantilie95_certifier_plugin_2.md
  plutus-tx-plugin/changelog.d/20250523_172915_seungheon.ooh_7065_2.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20250509_110706_Yuriy.Lazaryev_run_compiled_code.md
  plutus-tx/changelog.d/20250526_182207_Yuriy.Lazaryev_lookup_builtin_list_cheaper.md
  plutus-tx/changelog.d/20250527_092743_lorenzo.calegari_list_api.md
  plutus-tx/changelog.d/20250602_214427_seungheon.ooh_7115.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required, Release

#7141 Kwxm/spec/indices start at one
  doc/plutus-core-spec/cardano/builtins1.tex
  doc/plutus-core-spec/notation.tex
  doc/plutus-core-spec/plutus-core-specification.tex
  doc/plutus-core-spec/untyped-cek-machine.tex
  doc/plutus-core-spec/untyped-grammar.tex
  doc/plutus-core-spec/untyped-reduction.tex
Labels: Specification, Builtins, No Changelog Required

#7152 Narrow down files added by the release script
  scripts/interactive-release.sh
Labels: No Changelog Required

#7143 cabal.project: Update index-states and drop un-needed SRPs
  cabal.project
  flake.lock
  nix/shell.nix
Labels: No Changelog Required

#7158 Kwxm/conformance/update test results
  plutus-conformance/README.md
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/bytestring/bytestring-02/bytestring-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/string/string-03/string-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/interleaving/iteWrongCondTypePartiallyApplied/iteWrongCondTypePartiallyApplied.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/bls12_381_G1_uncompress/on-curve-bit3-set/on-curve-bit3-set.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/big-endian/all-zeros/all-zeros.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/big-endian/correct-output/correct-output.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/big-endian/empty/empty.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/big-endian/leading-zeros/leading-zeros.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/both-endian/both-endian.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/little-endian/all-zeros/all-zeros.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/little-endian/correct-output/correct-output.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/little-endian/empty/empty.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/byteStringToInteger/little-endian/trailing-zeros/trailing-zeros.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataByteString/chooseDataByteString.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataConstr/chooseDataConstr.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataInteger/chooseDataInteger.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataList/chooseDataList.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseDataMap/chooseDataMap.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseList/chooseList-03/chooseList-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseList/chooseList-04/chooseList-04.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/chooseUnit/chooseUnit-02/chooseUnit-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/consByteString/consByteString-03/consByteString-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-01/ifThenElse-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/ifThenElse/ifThenElse-02/ifThenElse-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/bounded/correct-output-exact-width/correct-output-exact-width.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/bounded/correct-output-extra-width/correct-output-extra-width.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/bounded/max-input-fits-max-width/max-input-fits-max-width.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/bounded/maximum-width-zero/maximum-width-zero.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/bounded/zero/zero.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/unbounded/correct-output/correct-output.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/unbounded/maximum-input/maximum-input.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/big-endian/unbounded/zero/zero.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/little-endian/bounded/correct-output-exact-width/correct-output-exact-width.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/little-endian/bounded/correct-output-extra-width/correct-output-extra-width.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/little-endian/bounded/zero/zero.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/little-endian/unbounded/correct-output/correct-output.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/integerToByteString/little-endian/unbounded/zero/zero.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/example/churchSucc/churchSucc.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/example/churchZero/churchZero.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/example/force-lam/force-lam.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/example/succInteger/succInteger.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/app/app-6/app-6.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/app/app-7/app-7.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/closure/closure.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/constr/constr-03/constr-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/delay/delay-error-2/delay-error-2.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/delay/delay-lam/delay-lam.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/lam/lam-1/lam-1.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/term/lam/lam-2/lam-2.uplc.expected
Labels: Test, Textual representation, No Changelog Required

#7159 [Refac] Make UPLC and TPLC tests more uniform
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Subst.hs
  plutus-core/plutus-core/test/Names/Spec.hs
  plutus-core/plutus-core/test/Parser/Spec.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
  plutus-core/plutus-ir/src/PlutusIR/Subst.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/Inline/CallSiteInline.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/NonStrict.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/Substitute.hs
  plutus-core/plutus-ir/test/PlutusIR/Parser/Tests.hs
  plutus-core/prelude/PlutusPrelude.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/AST.hs
  plutus-core/testlib/PlutusCore/Test.hs
  plutus-core/testlib/PlutusIR/Generators/AST.hs
  plutus-core/testlib/UntypedPlutusCore/Generators/Hedgehog.hs
  plutus-core/testlib/UntypedPlutusCore/Generators/Hedgehog/AST.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Subst.hs
  plutus-core/untyped-plutus-core/testlib/Generators/Lib.hs
  plutus-core/untyped-plutus-core/testlib/Generators/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Scoping/Spec.hs
Labels: Test, Refactoring, No Changelog Required

#7166 Benchmark: Linear Vesting
  plutus-benchmark/linear-vesting/exe/Main.hs
  plutus-benchmark/linear-vesting/src/LinearVesting/Test.hs
  plutus-benchmark/linear-vesting/src/LinearVesting/Validator.hs
  plutus-benchmark/plutus-benchmark.cabal
Labels: No Changelog Required
