Repository IntersectMBO/plutus, pull requests merged in 2025-04, with the labels that each got.

#6989 Agda certificate Serialisation tests and some fixes
  nix/agda-tools.nix
  nix/build-latex-doc.nix
  nix/metatheory-agda-library.nix
  nix/metatheory-site.nix
  nix/outputs.nix
  nix/project.nix
  nix/shell.nix
  nix/unraveling-recursion-paper.nix
  plutus-executables/plutus-executables.cabal
  plutus-executables/test/certifier/Golden/MinBS.golden
  plutus-executables/test/certifier/Spec.hs
  plutus-executables/test/certifier/UPLC/MinBS.uplc
  plutus-metatheory/.gitignore
  plutus-metatheory/Setup.hs
  plutus-metatheory/plutus-metatheory.cabal
Labels: Do not merge, Metatheory

#6999 Add script context test: purposeIsWellFormed
  plutus-benchmark/script-contexts/src/PlutusBenchmark/V3/Data/ScriptContexts.hs
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed-4.budget.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed-4.eval.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed.pir.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/purposeIsWellFormed.size.golden
  plutus-benchmark/script-contexts/test/V3/Spec.hs
Labels: No Changelog Required

#7001 Use cabal flags instead of template haskell to get the git rev
  nix/project.nix
  nix/utils.nix
  plutus-core/executables/plutus/Mode/HelpVersion.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/Data/Version/Extras.hs
  plutus-core/plutus-core/src/Development/GitRev/Extras.hs
  plutus-executables/executables/pir/Main.hs
  plutus-executables/executables/plc/Main.hs
  plutus-executables/executables/uplc/Main.hs
Labels: No Changelog Required

#7005 Bump image-size to 1.2.1 in docusaurus/yarn.lock
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#7006 Release 1.44.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20250322_155229_unsafeFixIO_callsite.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20250326_131800_unsafeFixIO_inline_threshold.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20250311_183212_unsafeFixIO_th_utils.md
  plutus-tx/changelog.d/20250320_234602_ana.pantilie95_remove_toDataList.md
  plutus-tx/changelog.d/20250325_130544_unsafeFixIO_lift_opt.md
  plutus-tx/changelog.d/20250327_143008_unsafeFixIO_plutustx_prelude.md
  plutus-tx/changelog.d/20250331_101218_unsafeFixIO_caselist.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#7007 Use CLEAN instead of MERGEABLE when detecting PR merge state statuses in interactive-release.sh
  scripts/interactive-release.sh
Labels: No Changelog Required

#7016 Doc-fix, Add required dependency for the off-chain example code
  doc/docusaurus/docs/auction-smart-contract/end-to-end/generating-keys.md
Labels: No Changelog Required

#7019 Bump estree-util-value-to-estree to 3.3.3 for docusaurus site
  doc/docusaurus/package.json
  doc/docusaurus/yarn.lock
Labels: No Changelog Required

#7020 Code Formatting: UPLC's Inline module.
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Transform/Inline.hs
Labels: No Changelog Required

#6964 Updated Pure definition in the metatheory
  plutus-executables/test/certifier/Spec.hs
  plutus-executables/test/certifier/UPLC/AA2-CSE.uplc
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Builtin.lagda.md
  plutus-metatheory/src/Untyped/Purity.lagda.md
  plutus-metatheory/src/VerifiedCompilation.lagda.md
  plutus-metatheory/src/VerifiedCompilation/Purity.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UCSE.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UFloatDelay.lagda.md
  plutus-metatheory/src/VerifiedCompilation/UInline.lagda.md
Labels: Metatheory, No Changelog Required

#6974 Proper purity check for unsaturated builtins
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/sorted.uplc.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.cbor.size.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.large.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.small.budget.golden
  cardano-constitution/test/Cardano/Constitution/Validator/Data/GoldenTests/unsorted.uplc.golden
  plutus-benchmark/bls12-381-costs/test/9.6/bls12-381-costs.golden
  plutus-benchmark/marlowe/test/data.budgets.golden.tsv
  plutus-benchmark/script-contexts/test/V1/Data/9.6/checkScriptContext1-20.budget.golden
  plutus-benchmark/script-contexts/test/V1/Data/9.6/checkScriptContext1-4.budget.golden
  plutus-benchmark/script-contexts/test/V1/Data/9.6/checkScriptContext1.size.golden
  plutus-benchmark/script-contexts/test/V2/Data/9.6/checkScriptContext1-20.budget.golden
  plutus-benchmark/script-contexts/test/V2/Data/9.6/checkScriptContext1-4.budget.golden
  plutus-benchmark/script-contexts/test/V2/Data/9.6/checkScriptContext1.size.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/checkScriptContext1-20.budget.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/checkScriptContext1-4.budget.golden
  plutus-benchmark/script-contexts/test/V3/Data/9.6/checkScriptContext1.size.golden
  plutus-core/changelog.d/20250407_170833_Yuriy.Lazaryev_builtin_purity.md
  plutus-core/plutus-core.cabal
  plutus-core/plutus-ir/test/PlutusIR/Purity/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Purity/ifThenElse
  plutus-core/plutus-ir/test/PlutusIR/Purity/ifThenElse.golden
  plutus-core/testlib/Test/Tasty/Extras.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Contexts.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Purity.hs
  plutus-core/untyped-plutus-core/test/Analysis/Lib.hs
  plutus-core/untyped-plutus-core/test/Analysis/Spec.hs
  plutus-core/untyped-plutus-core/test/Analysis/evalOrder/ifThenElse.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/geq1.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/geq2.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/geq3.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/geq4.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/geq5.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/gt1.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/gt2.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/gt3.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/gt4.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/Budget/9.6/gt5.budget.golden
  plutus-ledger-api/test-plugin/Spec/Data/SriptContext/9.6/succeedsIfHasDatum.uplc.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.budget.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.uplc.golden
Labels: No Changelog Required

#7023 Explain lifting in the user guide
  doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
  doc/docusaurus/docs/troubleshooting.md
  doc/docusaurus/docs/using-plinth/lifting.md
Labels: No Changelog Required

#7028 UPLC Term construction functions for testing
  plutus-core/plutus-core.cabal
  plutus-core/testlib/UntypedPlutusCore/Test/Term/Construction.hs
  plutus-core/untyped-plutus-core/test/Transform/Inline/Spec.hs
  plutus-core/untyped-plutus-core/test/Transform/Simplify.hs
  plutus-core/untyped-plutus-core/test/Transform/cse2.uplc.golden
Labels: No Changelog Required

#7027 Explain compile-time evaluation in the user guide
  doc/docusaurus/docs/working-with-scripts/compile-time-evaluation.md
Labels: No Changelog Required

#7035 fix: error message for the `listToArray` builtin meaning.
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Labels: No Changelog Required

#7036 Replace broken link in CONTRIBUTING.adoc
  CONTRIBUTING.adoc
Labels: No Changelog Required

#7044 refactor: apply fourmolu to plutus-conformance
  plutus-conformance/agda/Spec.hs
  plutus-conformance/haskell-steppable/Spec.hs
  plutus-conformance/haskell/Spec.hs
  plutus-conformance/src/PlutusConformance/Common.hs
Labels: No Changelog Required

#7033 Specification of dropList
  doc/plutus-core-spec/cardano/builtins6.tex
  doc/plutus-core-spec/flat-serialisation.tex
Labels: Specification, Builtins, No Changelog Required

#7043 Release 1.45.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20250407_170833_Yuriy.Lazaryev_builtin_purity.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20250410_095704_unsafeFixIO_builtinlist.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#7034 Add certifier tests for UPLC simplifier test inputs
  plutus-core/plutus-core.cabal
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Simplify.hs
  plutus-core/untyped-plutus-core/test/Transform/callsiteInline.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/forceDelayComplex.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/forceDelayMultiApply.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/inlineImpure4.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/inlinePure1.uplc.golden
  plutus-core/untyped-plutus-core/test/Transform/inlinePure2.uplc.golden
  plutus-core/untyped-plutus-core/testlib/Analysis/Lib.hs
  plutus-core/untyped-plutus-core/testlib/Analysis/Spec.hs
  plutus-core/untyped-plutus-core/testlib/DeBruijn/FlatNatWord.hs
  plutus-core/untyped-plutus-core/testlib/DeBruijn/Scope.hs
  plutus-core/untyped-plutus-core/testlib/DeBruijn/Spec.hs
  plutus-core/untyped-plutus-core/testlib/DeBruijn/UnDeBruijnify.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381/TestClasses.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381/Utils.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Bitwise/CIP0122.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Bitwise/CIP0123.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Common.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Conversion.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Costing.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/MakeRead.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/SignatureVerification.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Debug.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/FreeVars.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Golden.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Helpers.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Machines.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Regressions.hs
  plutus-core/untyped-plutus-core/testlib/Flat/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Generators.hs
  plutus-core/untyped-plutus-core/testlib/Scoping/Spec.hs
  plutus-core/untyped-plutus-core/testlib/Transform/CaseOfCase/Test.hs
  plutus-core/untyped-plutus-core/testlib/Transform/Simplify.hs
  plutus-core/untyped-plutus-core/testlib/Transform/Simplify/Lib.hs
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/plutus-executables.cabal
  plutus-executables/src/AgdaTrace.hs
  plutus-executables/test/certifier/Spec.hs
  plutus-metatheory/src/VerifiedCompilation.lagda.md
Labels: No Changelog Required

#7045 builtin array conformance tests
  plutus-conformance/agda/Spec.hs
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/emptyArray/emptyArray.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/emptyArray/emptyArray.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/emptyArray/emptyArray.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/illTypedArray-01/illTypedArray-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/illTypedArray-01/illTypedArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/illTypedArray-01/illTypedArray-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/illTypedArray-02/illTypedArray-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/illTypedArray-02/illTypedArray-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/illTypedArray-02/illTypedArray-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/simpleArray/simpleArray.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/simpleArray/simpleArray.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/simpleArray/simpleArray.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/unitArray/unitArray.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/unitArray/unitArray.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/constant/array/unitArray/unitArray.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-01/indexArray-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-01/indexArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-01/indexArray-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-02/indexArray-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-02/indexArray-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-02/indexArray-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-03/indexArray-03.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-03/indexArray-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-03/indexArray-03.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-01/lengthOfArray-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-01/lengthOfArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-01/lengthOfArray-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-02/lengthOfArray-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-02/lengthOfArray-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-02/lengthOfArray-02.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-01/listToArray-01.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-01/listToArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-01/listToArray-01.uplc.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-02/listToArray-02.uplc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-02/listToArray-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-02/listToArray-02.uplc.expected
Labels: No Changelog Required

#7049 Fix memory usage for polymorphic types.
  plutus-conformance/agda/Spec.hs
  plutus-core/cost-model/budgeting-bench/Benchmarks/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/plutus-core/test/CostModelSafety/Spec.hs
  plutus-core/plutus-core/test/TypeSynthesis/Golden/Signatures/DefaultFun/WriteBits.sig.golden
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Builtin.hs
  plutus-metatheory/src/Cost/Size.lagda.md
Labels: Builtins, Costing, No Changelog Required

#7051 Restructure certifier test modules; add unit testing capability
  plutus-executables/plutus-executables.cabal
  plutus-executables/test/certifier/Spec.hs
  plutus-executables/test/certifier/Test/Certifier/AST.hs
  plutus-executables/test/certifier/Test/Certifier/Executable.hs
  plutus-executables/test/certifier/Test/Certifier/Optimizer.hs
Labels: No Changelog Required

#7037 Drop Support for GHC 8.10
  .github/workflows/cabal-build-all.yml
  .github/workflows/manual-benchmark.yml
  CONTRIBUTING.adoc
  cabal.project
  doc/notes/plutus-debugger/srcspan.md
  nix/outputs.nix
  nix/project.nix
  nix/shell.nix
  plutus-benchmark/bls12-381-costs/src/PlutusBenchmark/BLS12_381/Scripts.hs
  plutus-benchmark/ed25519-costs/src/PlutusBenchmark/Ed25519/Common.hs
  plutus-benchmark/marlowe/README.md
  plutus-conformance/haskell-steppable/Spec.hs
  plutus-conformance/haskell/Spec.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/Data/Aeson/THReader.hs
  plutus-core/plutus-core/src/PlutusCore/Annotation.hs
  plutus-core/plutus-core/src/PlutusCore/Bitwise.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Meaning.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Runtime.hs
  plutus-core/plutus-core/src/PlutusCore/Crypto/ExpMod.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Universe.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Contexts.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/Data/Tx.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/Data/Contexts.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/Data/Tx.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/Data/Contexts.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/Data/Tx.hs
  plutus-metatheory/Setup.hs
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx-plugin/test/Plugin/Data/Spec.hs
  plutus-tx-plugin/test/Plugin/Laziness/Spec.hs
  plutus-tx-plugin/test/Plugin/Patterns/9.6/psym1.pir.golden
  plutus-tx-plugin/test/Plugin/Patterns/Spec.hs
  plutus-tx-plugin/test/Plugin/Typeclasses/Spec.hs
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/plutus-tx.cabal
  plutus-tx/src/PlutusTx/AsData/Internal.hs
  plutus-tx/src/PlutusTx/Bool.hs
  plutus-tx/src/PlutusTx/Builtins/HasBuiltin.hs
  plutus-tx/src/PlutusTx/Builtins/HasOpaque.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
  plutus-tx/src/PlutusTx/Function.hs
  plutus-tx/src/PlutusTx/Lift/TH.hs
  plutus-tx/src/PlutusTx/Lift/TestInstances.hs
  plutus-tx/src/PlutusTx/Optimize/Inline.hs
  plutus-tx/src/PlutusTx/Optimize/SpaceTime.hs
  plutus-tx/src/PlutusTx/Plugin/Utils.hs
  plutus-tx/src/PlutusTx/TH.hs
Labels: No Changelog Required

#7063 Forgot changelog entries
  plutus-core/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
  plutus-ledger-api/changelog.d/20250429_201143_kenneth.mackenzie_changelog.md
  plutus-tx-plugin/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
  plutus-tx/changelog.d/20250429_201150_kenneth.mackenzie_changelog.md
Labels: GHC, status: triaged

#7062 Add issues to a few fixmes
  plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-executables/test/certifier/Test/Certifier/Executable.hs
Labels: No Changelog Required

#6950 Costing of BuiltinArray functions
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/indexArray/indexArray-01/indexArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-01/lengthOfArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/lengthOfArray/lengthOfArray-02/lengthOfArray-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-01/listToArray-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/listToArray/listToArray-02/listToArray-02.uplc.budget.expected
  plutus-core/cost-model/budgeting-bench/Benchmarks/Arrays.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/cost-model/budgeting-bench/Main.hs
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/data/benching-conway.csv
  plutus-core/cost-model/data/builtinCostModelA.json
  plutus-core/cost-model/data/builtinCostModelB.json
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/Builtin.hs
Labels: No Changelog Required

#7064 Fix `expModInteger` bug
  plutus-core/plutus-core/src/PlutusCore/Crypto/ExpMod.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/exp-neg-non-inverse1.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/exp-neg-non-inverse2.err.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/mod-zero.err.golden
Labels: bug, Builtins, No Changelog Required
