Repository IntersectMBO/plutus, pull requests merged in 2025-05, with the labels that each got.

#7066 Property tests for `expModInteger`
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Crypto/ExpMod.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/exp-neg-non-inverse0.err.golden
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381/TestClasses.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/BLS12_381/Utils.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Common.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Integer/ExpModInteger.hs
Labels: bug, Builtins, No Changelog Required

#7070 Explicit imports and fourmolu formatting for the `PlutusTx.Test`
  plutus-tx/testlib/PlutusTx/Test.hs
Labels: No Changelog Required

#7080 Costing for `expModIntger`, take two.
  plutus-conformance/agda/Spec.hs
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/expModInteger/expMod-01/expMod-01.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/expModInteger/expMod-02/expMod-02.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/expModInteger/expMod-03/expMod-03.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/expModInteger/expMod-04/expMod-04.uplc.budget.expected
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/expModInteger/expMod-05/expMod-05.uplc.budget.expected
  plutus-core/cost-model/budgeting-bench/Benchmarks/Integers.hs
  plutus-core/cost-model/budgeting-bench/Common.hs
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching-conway.csv
  plutus-core/cost-model/data/builtinCostModelA.json
  plutus-core/cost-model/data/builtinCostModelB.json
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/cost-model/data/models.R
  plutus-core/cost-model/print-cost-model/Main.hs
  plutus-core/cost-model/test/TestCostModels.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/Core.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/JSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/CostingFun/SimpleJSON.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemory.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExMemoryUsage.hs
  plutus-core/plutus-core/test/TypeSynthesis/Golden/Signatures/DefaultFun/ExpModInteger.sig.golden
  plutus-core/satint/src/Data/SatInt.hs
  plutus-core/satint/test/TestSatInt.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Golden/Integer/ExpMod/mod-neg.err.golden
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-metatheory/src/Cost/Model.lagda.md
  plutus-metatheory/src/Cost/Raw.lagda.md
Labels: Builtins, Crypto, Costing, No Changelog Required

#7089 Add missing example to docusaurus cabal file
  doc/docusaurus/docusaurus-examples.cabal
Labels: No Changelog Required

#7078 Enable & Publish Project Coverage Reports For plutus-core
  .github/workflows/code-coverage-report.yml
  .github/workflows/slack-message-broker.yml
  nix/outputs.nix
  nix/project.nix
  plutus-core/plutus-core.cabal
  plutus-core/testlib/Test/Tasty/Extras.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/test/Spec/Data/Eval.hs
  plutus-ledger-api/test/Spec/Eval.hs
Labels: No Changelog Required

#7083 Release 1.46.0.0
  cardano-constitution/cardano-constitution.cabal
  doc/docusaurus/docusaurus-examples.cabal
  plutus-benchmark/plutus-benchmark.cabal
  plutus-conformance/plutus-conformance.cabal
  plutus-core/CHANGELOG.md
  plutus-core/changelog.d/20250415_124450_yuriy.lazaryev_1492_test_isFirstVarBeforeEffects.md
  plutus-core/changelog.d/20250415_161534_effectfully_force_ifThenElse_delay.md
  plutus-core/changelog.d/20250423_112457_unsafeFixIO_strictify.md
  plutus-core/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
  plutus-core/plutus-core.cabal
  plutus-executables/plutus-executables.cabal
  plutus-ledger-api/CHANGELOG.md
  plutus-ledger-api/changelog.d/20250429_201143_kenneth.mackenzie_changelog.md
  plutus-ledger-api/plutus-ledger-api.cabal
  plutus-metatheory/plutus-metatheory.cabal
  plutus-tx-plugin/CHANGELOG.md
  plutus-tx-plugin/changelog.d/20250429_201142_kenneth.mackenzie_changelog.md
  plutus-tx-plugin/changelog.d/20250502_105910_Yuriy.Lazaryev_from_string_inscruitable.md
  plutus-tx-plugin/plutus-tx-plugin.cabal
  plutus-tx-test-util/plutus-tx-test-util.cabal
  plutus-tx/CHANGELOG.md
  plutus-tx/changelog.d/20250429_201150_kenneth.mackenzie_changelog.md
  plutus-tx/plutus-tx.cabal
Labels: No Changelog Required

#7095 Update slack-github-action to 2.1.0
  .github/workflows/slack-message-broker.yml
Labels: No Changelog Required

#7054 Add array built-in functions to the spec
  doc/plutus-core-spec/cardano/builtins6.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/header.tex
  doc/plutus-core-spec/plutus-core-specification.tex
Labels: No Changelog Required

#7100 Enable Code Coverare Report for plutus-metatheory
  nix/project.nix
Labels: No Changelog Required

#7085 [Docs] Add 'BuiltinResult' to 'BuiltinsOverview.md'
  plutus-core/docs/BuiltinsOverview.md
Labels: Documentation, No Changelog Required

#7101 pre-commit run --all-files
  plutus-core/plutus-core.cabal
Labels: No Changelog Required

#7106 [Errors] Make '_OperationalEvaluationError' work in the machines
  plutus-core/changelog.d/20250520_160112_effectfully_make__OperationalEvaluationError_work_in_the_machines.md
  plutus-core/plutus-core/src/PlutusCore/Evaluation/ErrorWithCause.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-ir/test/PlutusIR/Compiler/Recursion/errorBinding.golden
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex3.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Debug/ex4.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.plc.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/polyErrorInst.uplc.golden
  plutus-tx-plugin/test/Strictness/9.6/lambda-default.eval.golden
  plutus-tx-plugin/test/Strictness/9.6/lambda-nonstrict.eval.golden
  plutus-tx-plugin/test/Strictness/9.6/lambda-strict.eval.golden
Labels: Evaluation, Errors

#7107 Prevent `nix develop` from building the metatheory
  nix/project.nix
  nix/shell.nix
Labels: No Changelog Required

#7110 [Refactoring] Cut 'Evaluation' from 'Structural' and 'Operational'
  doc/notes/plutus-core/cek-budgeting-profiling/CostingDetails.md
  plutus-core/changelog.d/20250521_140320_effectfully_cut_Evaluation_from_Structural_and_Operational.md
  plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs
  plutus-core/plutus-core/src/PlutusCore/Builtin/Result.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/testlib/PlutusCore/Generators/NEAT/Spec.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/ExBudgetMode.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Definition.hs
Labels: Refactoring, Errors

#7111 [Refectoring] Remove Prism from type checking/compiler error handling
  plutus-core/executables/plutus/AnyProgram/Compile.hs
  plutus-core/executables/plutus/AnyProgram/IO.hs
  plutus-core/executables/plutus/AnyProgram/Parse.hs
  plutus-core/executables/plutus/Debugger/TUI/Main.hs
  plutus-core/executables/src/PlutusCore/Executable/Common.hs
  plutus-core/plutus-core/src/PlutusCore.hs
  plutus-core/plutus-core/src/PlutusCore/Check/Normal.hs
  plutus-core/plutus-core/src/PlutusCore/Check/Uniques.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn.hs
  plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
  plutus-core/plutus-core/src/PlutusCore/Error.hs
  plutus-core/plutus-core/src/PlutusCore/Parser.hs
  plutus-core/plutus-core/src/PlutusCore/Parser/ParserCommon.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck.hs
  plutus-core/plutus-core/src/PlutusCore/TypeCheck/Internal.hs
  plutus-core/plutus-core/test/Names/Spec.hs
  plutus-core/plutus-core/test/Parser/Spec.hs
  plutus-core/plutus-core/test/Spec.hs
  plutus-core/plutus-core/test/TypeSynthesis/Spec.hs
  plutus-core/plutus-ir/src/PlutusIR/Check/Uniques.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Datatype.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Error.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Let.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Lower.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Recursion.hs
  plutus-core/plutus-ir/src/PlutusIR/Compiler/Types.hs
  plutus-core/plutus-ir/src/PlutusIR/Error.hs
  plutus-core/plutus-ir/src/PlutusIR/Parser.hs
  plutus-core/plutus-ir/src/PlutusIR/Pass.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck.hs
  plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs
  plutus-core/plutus-ir/test/PlutusIR/Compiler/Let/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Generators/QuickCheck/Tests.hs
  plutus-core/plutus-ir/test/PlutusIR/Transform/StrictLetRec/Tests/Lib.hs
  plutus-core/prelude/PlutusPrelude.hs
  plutus-core/testlib/PlutusCore/Generators/Hedgehog/TypeEvalCheck.hs
  plutus-core/testlib/PlutusCore/Generators/QuickCheck/Common.hs
  plutus-core/testlib/PlutusIR/Generators/QuickCheck/Common.hs
  plutus-core/testlib/PlutusIR/Pass/Test.hs
  plutus-core/testlib/PlutusIR/Test.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Check/Scope.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Check/Uniques.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/DeBruijn.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Parser.hs
  plutus-core/untyped-plutus-core/testlib/DeBruijn/UnDeBruijnify.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Builtins/Common.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Debug.hs
  plutus-core/untyped-plutus-core/testlib/Evaluation/Golden.hs
  plutus-core/untyped-plutus-core/testlib/Generators.hs
  plutus-executables/executables/pir/Main.hs
  plutus-executables/executables/plc/Main.hs
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/plutus-executables.cabal
  plutus-tx-plugin/src/PlutusTx/Compiler/Error.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Utils.hs
  plutus-tx-plugin/src/PlutusTx/Plugin.hs
  plutus-tx/src/PlutusTx/Lift.hs
Labels: Refactoring, No Changelog Required

#7128 Move `caseList` and `caseData` to the end of the flat encoding
  doc/plutus-core-spec/cardano/builtins6.tex
  doc/plutus-core-spec/flat-serialisation.tex
  doc/plutus-core-spec/plutus-core-specification.tex
  plutus-core/changelog.d/20250530_195904_kenneth.mackenzie_deprecate_caseList_caseData.md
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
Labels: Plutus Core, Specification, Builtins
