Repository IntersectMBO/plutus, pull requests merged in 2025-02, with the labels that each got.

#6820 Rename job -> workflow in .github + add interactive-release script to the shell
  .github/workflows/broken-links.yml
  .github/workflows/cabal-build-all.yml
  .github/workflows/cardano-constitution-tests.yml
  .github/workflows/changelog-label.yml
  .github/workflows/cost-model-benchmark.yml
  .github/workflows/docusaurus-site.yml
  .github/workflows/haddock-site.yml
  .github/workflows/longitudinal-benchmark.yml
  .github/workflows/manual-benchmark.yml
  .github/workflows/metatheory-site.yml
  .github/workflows/nightly-testsuite.yml
  .github/workflows/papers-and-specs.yml
  .github/workflows/plutus-tx-template.yml
  .github/workflows/slack-message-broker.yml
  .github/workflows/sprint-issues-rollover.yml
  .github/workflows/triage-label.yml
  nix/shell.nix
Labels: No Changelog Required

#6821 Add nicer changelog to plutus release notes
  scripts/interactive-release.sh
Labels: No Changelog Required

#6795 Refactor Nix Code (remove iogx)
  .github/workflows/metatheory-site.yml
  .github/workflows/papers-and-specs.yml
  flake.lock
  flake.nix
  garnix.yaml
  nix/agda-with-stdlib.nix
  nix/build-latex-doc.nix
  nix/build-latex.nix
  nix/latex-documents.nix
  nix/metatheory-site.nix
  nix/outputs.nix
  nix/pkgs.nix
  nix/project.nix
  nix/r-with-packages.nix
  nix/shell.nix
  nix/unraveling-recursion-paper.nix
  nix/utils.nix
  plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs-boot
  plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs-boot
Labels: No Changelog Required

#6817 Add the 'dropList' builtin, take 2
  plutus-core/changelog.d/20250203_144259_ramsay.taylor_add_dropList_2.md
  plutus-core/cost-model/CostModelGeneration.md
  plutus-core/cost-model/budgeting-bench/Benchmarks/Lists.hs
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/benching-conway.csv
  plutus-core/cost-model/data/builtinCostModelA.json
  plutus-core/cost-model/data/builtinCostModelB.json
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/cost-model/data/models.R
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules/CommuteFnWithConst.hs
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins.hs
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Plutus Core, Plinth, Builtins, Costing

#6824 Downgrade cabal version from 3.14.1.0 to 3.12.1.0
  nix/shell.nix
Labels: No Changelog Required

#6818 Add apply-to-cbor-data option to uplc
  plutus-executables/executables/uplc/Main.hs
  plutus-executables/plutus-executables.cabal
Labels: Plutus Exe, No Changelog Required

#6831 [Docs] [Bug] Replace 'minting' with 'spending'
  doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
Labels: bug, Documentation, No Changelog Required

#6830 fix: typos in documentation files
  STYLEGUIDE.adoc
  plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature/README.md
  plutus-metatheory/Setup.hs
  plutus-tx-plugin/test/Plugin/Data/Spec.hs
Labels: No Changelog Required

#6850 User guide: Plutus Tx -> Plinth
  doc/docusaurus/docs/auction-smart-contract/_category_.json
  doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
  doc/docusaurus/docs/delve-deeper/_category_.json
  doc/docusaurus/docs/delve-deeper/encoding.md
  doc/docusaurus/docs/delve-deeper/haddock-documentation.md
  doc/docusaurus/docs/delve-deeper/languages.md
  doc/docusaurus/docs/delve-deeper/plinth-compiler-options.md
  doc/docusaurus/docs/delve-deeper/understanding-script-hashes.md
  doc/docusaurus/docs/essential-concepts/_category_.json
  doc/docusaurus/docs/essential-concepts/eutxo.md
  doc/docusaurus/docs/essential-concepts/plinth-and-plutus-core.md
  doc/docusaurus/docs/essential-concepts/versions.md
  doc/docusaurus/docs/glossary.md
  doc/docusaurus/docs/index.md
  doc/docusaurus/docs/troubleshooting.md
  doc/docusaurus/docs/using-plinth/_category_.json
  doc/docusaurus/docs/using-plinth/cli-plutus.md
  doc/docusaurus/docs/using-plinth/compiling-plutus-tx.md
  doc/docusaurus/docs/using-plinth/differences-from-haskell.md
  doc/docusaurus/docs/using-plinth/environment-setup.md
  doc/docusaurus/docs/using-plinth/extensions-flags-pragmas.md
  doc/docusaurus/docs/using-plinth/inspecting.md
  doc/docusaurus/docs/using-plinth/special-functions-and-types.md
  doc/docusaurus/docs/working-with-scripts/ledger-language-version.md
  doc/docusaurus/docs/working-with-scripts/optimizing-scripts-with-asData.md
  doc/docusaurus/docs/working-with-scripts/other-optimization-techniques.md
  doc/docusaurus/docs/working-with-scripts/simplifying-before-compilation.md
  doc/docusaurus/docusaurus.config.ts
  plutus-tx-plugin/app/GeneratePluginOptionsDoc.hs
Labels: No Changelog Required

#6853 s/lengthArray/lengthOfArray/
  plutus-core/changelog.d/20250207_120412_Yuriy.Lazaryev_cip_0138_builtin_array.md
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/create-cost-model/CreateBuiltinCostModel.hs
  plutus-core/cost-model/data/builtinCostModelA.json
  plutus-core/cost-model/data/builtinCostModelB.json
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/BuiltinCostModel.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/ExBudgetingDefaults.hs
  plutus-core/plutus-ir/src/PlutusIR/Transform/RewriteRules/CommuteFnWithConst.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Builtins/Definition.hs
  plutus-ledger-api/CostModel/Data/Params/CostModelParams/costModelParamNames.txt.golden
  plutus-ledger-api/src/PlutusLedgerApi/Common/Versions.hs
  plutus-ledger-api/src/PlutusLedgerApi/V1/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V2/ParamName.hs
  plutus-ledger-api/src/PlutusLedgerApi/V3/ParamName.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/Data/EvaluationContext.hs
  plutus-ledger-api/testlib/PlutusLedgerApi/Test/V3/EvaluationContext.hs
  plutus-tx-plugin/src/PlutusTx/Compiler/Builtins.hs
  plutus-tx-plugin/test/Array/9.6/compiledLengthArray.pir.golden
  plutus-tx-plugin/test/Array/9.6/compiledLengthArray.uplc.golden
  plutus-tx-plugin/test/Array/Spec.hs
Labels: No Changelog Required

#6848 Kwxm/crypto/remove ed25519-donna
  doc/notes/model/UTxO.hsproj/Examples/Keys.hs
  doc/notes/model/UTxO.hsproj/Types.hs
  doc/notes/model/UTxO.hsproj/UTxO.cabal
  doc/notes/model/UTxO.hsproj/Witness.hs
  plutus-core/plutus-core.cabal
  plutus-core/plutus-core/src/PlutusCore/Crypto/Ed25519.hs
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-metatheory/plutus-metatheory.cabal
  plutus-metatheory/src/Builtin.lagda.md
  plutus-tx/src/PlutusTx/Builtins/Internal.hs
Labels: Builtins, Crypto, No Changelog Required

#6861 Update logo in user guide
  doc/docusaurus/static/img/logo.svg
Labels: No Changelog Required

#6867 Replace the remaining Plutus Tx references with Plinth
  doc/docusaurus/docs/auction-smart-contract/on-chain-code.md
  doc/docusaurus/docs/using-plinth/cli-plutus.md
  doc/docusaurus/docs/using-plinth/compiling-plinth.md
  doc/docusaurus/docs/using-plinth/differences-from-haskell.md
  doc/docusaurus/docs/using-plinth/environment-setup.md
  doc/docusaurus/docs/using-plinth/extensions-flags-pragmas.md
  doc/docusaurus/docs/using-plinth/inspecting.md
  doc/docusaurus/docs/using-plinth/special-functions-and-types.md
Labels: No Changelog Required

#6862 [Builtins] [Bug] Tweak 'dropList' costing and else
  plutus-core/cost-model/create-cost-model/BuiltinMemoryModels.hs
  plutus-core/cost-model/data/builtinCostModelA.json
  plutus-core/cost-model/data/builtinCostModelB.json
  plutus-core/cost-model/data/builtinCostModelC.json
  plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs
  plutus-core/plutus-core/test/TypeSynthesis/Golden/Signatures/DefaultFun/DropList.sig.golden
  plutus-core/plutus-core/test/TypeSynthesis/Golden/Signatures/DefaultFun/LengthOfArray.sig.golden
Labels: bug, Builtins, No Changelog Required

#6873 Fix .gitignore pattern for flat files generated by exe:marlowe-validators
  plutus-benchmark/.gitignore
Labels: No Changelog Required

#6872 Use more TH quotations in PlutusTx.IsData.TH
  plutus-tx/src/PlutusTx/IsData/TH.hs
Labels: No Changelog Required

#6874 chore: fourmolize PlutusBenchmark/Marlowe
  plutus-benchmark/marlowe/exe/Main.hs
  plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/RolePayout.hs
  plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Semantics.hs
  plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Util.hs
  plutus-benchmark/marlowe/test/Spec.hs
  plutus-benchmark/plutus-benchmark.cabal
Labels: No Changelog Required

#6878 chore: reformat more marlowe code with fourmolu
  plutus-benchmark/marlowe/bench/BenchAgdaCek.hs
  plutus-benchmark/marlowe/bench/BenchCek.hs
  plutus-benchmark/marlowe/bench/Shared.hs
  plutus-benchmark/marlowe/exe/Main.hs
  plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/RolePayout.hs
  plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Semantics.hs
  plutus-benchmark/marlowe/exe/PlutusBenchmark/Marlowe/Util.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/BenchUtil.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics/Types.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Core/V1/Semantics/Types/Address.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/RolePayout.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Scripts/Semantics.hs
  plutus-benchmark/marlowe/src/PlutusBenchmark/Marlowe/Types.hs
Labels: No Changelog Required

#6880 Add sum type test cases for AsData
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-budget-manual.budget.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-budget.budget.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.eval.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.pir.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum-manual.uplc.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum.eval.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum.pir.golden
  plutus-tx-plugin/test/AsData/Budget/9.6/destructSum.uplc.golden
  plutus-tx-plugin/test/AsData/Budget/Spec.hs
  plutus-tx-plugin/test/AsData/Budget/Types.hs
Labels: No Changelog Required

#6876 [Evaluation] Catch more exceptions
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Ck.hs
  plutus-core/plutus-core/src/PlutusCore/Evaluation/Machine/Exception.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/Cek/Internal.hs
  plutus-core/untyped-plutus-core/src/UntypedPlutusCore/Evaluation/Machine/SteppableCek/Internal.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden.hs
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/headSingletonException.type.golden
  plutus-core/untyped-plutus-core/test/Evaluation/Golden/headSingletonException.uplc.golden
Labels: Evaluation, No Changelog Required

#6884 Restore LOCALE_ARCHIVE when glibc is available
  nix/shell.nix
Labels: No Changelog Required

#6726 chore: remove redundant words in comment
  doc/papers/system-f-in-agda/paper.lagda
  doc/plutus-core-spec/flat-serialisation.tex
Labels: No Changelog Required

#6885 Fix AssocMap.Spec
  plutus-tx-plugin/test/AssocMap/Spec.hs
  plutus-tx-plugin/test/Budget/9.6/map3-budget.budget.golden
  plutus-tx-plugin/test/Budget/9.6/map3.eval.golden
  plutus-tx-plugin/test/Budget/9.6/map3.pir.golden
  plutus-tx-plugin/test/Budget/9.6/map3.uplc.golden
Labels: No Changelog Required
